### ISSUE TITLE
Better suport for custom code

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1968]
**Reported by beutlich on 29 Mar 2016 08:05 UTC**
https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Blocks/Tables.mo#L1313-L1314 gives a "hackish" example how to include user code in the generated C code by means of a declaration and call of a dummy (pure) function.

Simulink Coder(TM) fka Real-Time Workshop(R) from The MathWorks has the concept of custom code (within the model). In order to move from a standard-conform hack to a better standard it may be considered to adopt this concept by e.g. extending the experiment annotation to add custom code files or directories.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1968

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 29 Mar 2016 08:05 UTC**

**Comment by beutlich** [comment]
I am confused why this was closed without any feedback.

The given examle above really is far from ideal, but I can live with it if there is no general interest to better support custom code.

**Comment by HansOlsson** [comment]
> I am confused why this was closed without any feedback.
> 
> The given examle above really is far from ideal, but I can live with it if there is no general interest to better support custom code.

I agree that this (and many other of the old issues) indicated situations that were far from ideal, but it seemed no-one was interested in working on them. The idea was to close them, and if people actually want to work on the issues they should put effort into them.

However, instead of rushing through these closed old issues - please consider looking at the ones that _weren't closed_ and try to give proposals there.
