### ISSUE TITLE
Variability of input formal parameters

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2243]
**Reported by sjoelund&#x2e;se on 27 Mar 2018 10:01 UTC**
The specification does not seem to have any special rule that allows input formal parameters to be used. Dymola seems to allow bindings to parameters from input formal parameters (which are just discrete-time variables that do not change during the function's execution as far as I can tell). Some sample code that triggers this from PowerSystems:

```mo
  // from: PowerSystems
  function machineSyn3rd

    input AC3ph.Machines.Parameters.Synchron3rd p
      "parameters synchronous machine 3rd order";
    input Integer scale=1 "scaling factor topology (Y:1, Delta:3)";
    output AC3ph.Machines.Coefficients.Synchron3rd c
      "coefficient matrices synchronous machine 3rd order";
  protected
    final parameter SI.AngularFrequency omega_nom=2*pi*p.f_nom;
    final parameter Real[2] RL_base=Utilities.Precalculation.baseRL(
                                           p.puUnits, p.V_nom, p.S_nom, omega_nom, scale)
      "base resistance inductance";
  end machineSyn3rd;
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2243

**Comment by modelica-trac-importer** [comment]
**Modified by sjoelund&#x2e;se on 27 Mar 2018 10:02 UTC**

**Comment by HansOlsson** [comment]
Ticket is a bit unclear.

To allow the example:
One possibility raised was for "final" to forbid assignment as well (but problematic) - so change the example to remove "parameter".
Another possibility was to change so that formal inputs of functions behave as if they were parameter-expressions. (But non-input still behave as if they are discrete-time expressions.)

**Comment by henrikt-ma** [comment]
I probably missed some important part of the discussion, but it seems very strange to say that formal input parameters (which I take to mean the same as _formal input arguments_ in this context) have parameter variability; I'm sure the intention was not to just evaluate `sin(time)` once during initialization, and then use that value throughout the rest of the simulation since `time` is assumed to have parameter variability inside the function.

To me, having an `input parameter Integer` would make perfect sense in this case, so I'd be very interested to hear the conclusion regarding why it was used in the past.

**Comment by miscco** [comment]
@henrikt-ma The point is precisely that it has _parameter_ variability **inside** the function.

So `sin(time)` would still generate the expected behavior, but **inside** `sin` the user is forbidden to **change** the _formal  input parameter_ `time`

So it does not have any effect on the variability of the passed argument, it only clarifies that inputs should not be modified inside the function.

**Comment by henrikt-ma** [comment]
In that case, aren't there less confusing ways of saying that they can't be changed?  To me, having parameter variability means that it doesn't change after simulation initialization.

**Comment by gkurzbach** [comment]
Inside of functions "parameter variability" means "it does noch change inside the function during function execution".

The primary reason for saying inputs have parameter variability was, that then it is clear that they can referenced inside local parameters and local dimension specifications.

**Comment by henrikt-ma** [comment]
Sorry, I'm not familiar with that quote, and I'm unable to find it (a Git grep gives no results for _function execution_).  In which section should I look?

**Comment by gkurzbach** [comment]
This was not from the spec, but "common understanding". Sorry, for not marking that as such.

**Comment by henrikt-ma** [comment]
OK, I see.  To me, variability of variables is an important concept for understanding Modelica, and at the same time it is something that generally takes some time for new users to get accustomed to, so I think it would be better if we could avoid using the related terms with other meanings than the correct ones.
