### ISSUE TITLE
Grammar for function partial application.

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2250]
**Reported by stefanv on 28 May 2018 20:30 UTC**
The Modelica grammar (concrete syntax) currently contains:

```
function-arguments :
	expression [ "," function_arguments-non-first | for for_indices ]
	| function name "(" [ named_arguments ] ")" [ "," function-arguments-non-first ]
	| named-arguments

function-arguments-non-first :
	function-argument [ "," function-arguments-non-first ]
	| named-arguments

...

named-arguments :
	named-argument [ "," named-arguments ]

named-argument :
	IDENT "=" function-argument

function-argument :
	function name "(" [ named-arguments ] ")" | expression
```

I'd like to suggest that function partial application be factored out to avoid repetition and aid clarity:

```
function-arguments :
	expression [ "," function_arguments-non-first | for for_indices ]
	| function-partial-application [ "," function-arguments-non-first ]
	| named-arguments

function-arguments-non-first :
	function-argument [ "," function-arguments-non-first ]
	| named-arguments

...

named-arguments :
	named-argument [ "," named-arguments ]

named-argument :
	IDENT "=" function-argument

function-argument :
	function-partial-application | expression

function-partial-application :
	function name "(" [ named-arguments ] ")"
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2250

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 28 May 2018 20:54 UTC**
Also, I believe the `name` in the function partial application, whether we factor it out or not, should be `component-reference`, shouldn't it?

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 29 May 2018 07:43 UTC**
I agree with refactoring the grammar, and that the "name" should be changed - but to type-specifier #2176 - so that we can have a leading dot `integrate(function .f())`, without allowing  `integrate(function a[1].f())`. 

I'm not totally against generalizing to component-reference, but think it would need some additional motivation and analysis.

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 29 May 2018 08:17 UTC**
Replying to [comment:3 Martin Sjölund]:
> Replying to [comment:1 Stefan Vorkoetter]:
> > Also, I believe the `name` in the function partial application, whether we factor it out or not, should be `component-reference`, shouldn't it?
> 
> I don't think we should change it to `component-reference`. Calls are `component-reference` only because it is problematic for some formalism / parser generators to handle the conflict between the prefixes for `component-reference` and `name` in `x` and `x()`.

In Modelica 3.4 it's also allowed to have subscripts in function calls, as long as they can be evaluated at translation time. That only applies to calls though and not function partial application, so only changing `name` to `component-reference` would not be enough to allow subscripted function partial application names.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 29 May 2018 10:15 UTC**
Yes, the ability to specify a leading "." was why I suggested the change to `component-reference`. I wasn't aware that there was conscious decision to allow subscripts on calls, but not on partial applications, but if that is the case, then `type-specifier` instead of `component-reference` would be the better choice.

I think the use of `name` was an oversight, possibly since the leading "." was formerly part of `name`.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 4 Jun 2018 13:39 UTC**
Ah, yes, I see now that there was already a ticket for that. _This_ ticket can remain for what I originally reported/requested then, that function partial application be factored out.

**Comment by sjoelund** [comment]
I was messing with the function calls for MCP-0031, implementing the grammar in ANTLR and needed to resolve this (and some additional things). For example, ANTLRv4 said for the old grammar when parsing `f(a, b=3)`, `Got 'f(a, b', expected ')'`. I resolved that by changing `function_arguments_non_first` to recognize `IDENT` `=` and then return `named_arguments`. This may not be desirable since the "output" of the rule is then different. But it sort of was before as well.

```antlr
function_call_args :
  '(' function_arguments? ')'
  ;

function_arguments
  : expression ( function_arguments_non_first | 'for' for_indices )
  | function_partial_application function_arguments_non_first
  | named_arguments
  ;

function_arguments_non_first
  : ( ','
    ( IDENT '=' function_argument named_arguments_non_first
    | expression function_arguments_non_first
    | function_partial_application function_arguments_non_first
    )
    )?
  ;

named_arguments :
  named_argument named_arguments_non_first
  ;

named_arguments_non_first :
  ( ',' named_argument )*
  ;

named_argument :
  IDENT '=' function_argument
  ;

function_argument
  : function_partial_application
  | expression
  ;

function_partial_application
  : 'function' name '(' named_arguments? ')'
  ;
```

**Comment by christoff-buerger** [comment]
> For example, ANTLRv4 said for the old grammar when parsing f(a, b=3), Got 'f(a, b', expected ')'. I resolved that by changing function_arguments_non_first to recognize IDENT = and then return named_arguments.

@sjoelund: I do not understand why these additional refactorings are required. As far as I can see, the grammar is well-suited for top-down parsing if required (we use exactly the specification's grammar). And factoring out `function-partial-application` as proposed by @svorkoetter will not require any further refactoring due to new conflicts.

The only adjustment I see for @svorkoetter's proposal is to change the `name` to `type-specifier`, such that we have two changed grammar rules and one new as follows:
```
/*
    Changed `function-arguments` rule replacing
        function name "(" [ named-arguments ] ")"
    by
        function-partial-application:
*/
function-arguments :
      expression [ "," function_arguments-non-first | for for_indices ]
    | function-partial-application [ "," function-arguments-non-first ]
    | named-arguments

/*
    Changed `function-argument` rule replacing
        function name "(" [ named-arguments ] ")"
    by
        function-partial-application:
*/
function-argument :
    function-partial-application | expression

/*
    New `function-partial-application` rule:
*/
function-partial-application :
    function type-specifier "(" [ named-arguments ] ")"
```

**Comment by sjoelund** [comment]
This particular rule I think ANTLRv3 (`LL(k=2)`) was happy with, but ANTLRv4 was not happy with. However, when trying to rewrite it to the old style, it seems to work fine so it might have been some conflict with expression it was not happy with... https://github.com/modelica/ModelicaSpecification/pull/2378/commits/09ef9089631e86501e0826fa90e735fb4b7a0d0a should put it in the old style in the specificaiton.

You cannot be using exactly the grammar was written since it is not suited for an `LL(k)` top-down parser. Especially the ambiguity for equality equations and function calls in equations is impossible to deal with without backtracking or rewriting and checking with some semantic rule (which I would hope to avoid). That part is still disabled in #2378 (which we will need to resolve soon if EMPHYSIS is going to finish on time).
