### ISSUE TITLE
Meaning of "integer number" in array concatenation

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2273]
**Reported by henrikt on 15 Oct 2018 08:09 UTC**
Section 10.4.2 _Array Concatenation_ says:
> k shall be an integer number.

It doesn't seem right that this should simply mean that `k` shall be an expression of type `Integer`, which would make the type of the `cat` expression depend on argument values in a non-constant fashion.  Isn't this a more precise way of phrasing the intention of the restriction:
> k shall be a literal integer.

A more general formulation would be to say that
| k shall be a constant variability `Integer` expression.
However, that seems more general and more complicated to implement than the original intention.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2273

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2018 08:39 UTC**
Cleaning up unspecified tickets to prepare for move to GitHub

**Comment by HansOlsson** [comment]
Poll for `cat(j, ....)` (`size(A,j)` has no restriction for j):
Constant: 3
Parameter: 5
Literal: 0
Any integer expression: 1
-
Conclusion: Parameter seems like the desired one.

**Comment by henrikt-ma** [comment]
A little, late, but I'd like to point out that the fact that `size(A, j)` doesn't have any restriction on `j` is an entirely different matter to me, since the type of the expression is known to be `Integer` under all circumstances.

If the specification would say _parameter expression_, I think it would make sense than just _parameter_, since _parameter expression_ just means constant variability to me.

**Comment by miscco** [comment]
@henrikt-ma That is what is meant. The specification currently required `integer number`, which was not really clear wrt to the variability. It should be a *parameter expression* of type *integer*
