### ISSUE TITLE
Introduce propagate keyword

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2277]
**Reported by marco&#46;kessler on 29 Oct 2018 16:10 UTC**
If a parameter is passed up one level, the parameter definition must be copied and a modifier must be added to the component, which originally defined the parameter.

The example below shows how the code looks like, if the parameter `strict` of the class `LimIntegrator` is propagated with all its properties.

```
model X
  Modelica.Blocks.Continuous.LimIntegrator limIntegrator(strict=strict);
  parameter Boolean strict=false "= true, if strict limits with noEvent(..)"
    annotation (Evaluate=true, choices(checkBox=true), Dialog(tab="Advanced"));
end X;
```

Dymola eases that process, by providing a _Propagate_ command in the GUI. However, we end up with duplicated code. So later modifications are not reflected in the propagated parameter and the user must update the propagated parameter by himself.

Hence a new keyword could be introduced: `propagate`.
The keyword could be used as follows:

```
model Y
  Modelica.Blocks.Continuous.LimIntegrator limIntegrator(propagate strict);
end Y;
```

Now the model `Y` would contain the parameter `strict`, exactly as it is defined in `LimIntegrator`: including all annotations, start values, default value, etc.

If the parameter `strict` in `LimIntegrator` is modified, this modification is automatically passed to the higher level.

If the parameter shall be propagated without some of its properties (e.g. if a different dialog group shall be specified in the annotation) the old mechanism can still be used: define a new parameter with the desired group annotation and set a modifier equation.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2277

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 29 Oct 2018 16:22 UTC**
The need for this is not clear to me. Parameters generally aren't propagated upward, they are propagated downward. That is, the modification `strict = strict` specifies that limIntegrator's `strict` parameter should take on the same value as Y's `strict` parameter, not the other way around.

If the value of `Modelica.Blocks.Continuous.LimIntegrator.strict` were to change, one wouldn't want that to affect `Y.strict`. Instead, the modification should still apply, replacing `limIntegrator.strict` with the desired value.

**Comment by modelica-trac-importer** [comment]
**Comment by marco&#46;kessler on 30 Oct 2018 10:10 UTC**
The need for this: Everytime a parameter of a nested component shall be settable at top level.

Let us take `Modelica.Mechanics.Rotational.Components.Gearbox` for example.
The user shall be able to set the parameters `ratio` and `lossTable` of `lossyGear` and the parameters `c`, `d` and `b`, of `elastoBacklash`. Hence, `Gearbox` contains copies of said parameters and passes the parameter values to the components with modifier equations. So we have duplicated code for the parameter declarations and if e.g. a typo in the parameter description of `lossTable` is fixed in the class `LossyGear`, it must be also fixed in the class `Gearbox`.

With this enhancement request, the situation could be handled much more elegant. The new keyword `propagate` (or name it differently, see below) would specify that a parameter of a nested component is available at top level.

Regarding propagation: 
You are using the term propagate different than I did. So maybe propagate is not the right term in this context and the new keyword should be named different.
In my understanding propagate meant to bring parameters from a nested component up one level to the class - as Dymola does, if you click _Propagate_ in the parameter gui.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 2 Nov 2018 10:38 UTC**
We would need to take care when specifying what happens if there are several parameters of the same name being propagated from different components.

**Comment by HansOlsson** [comment]
Jesper: Need to allow modifier for "strict" as well. An interesting case is if "LimIntegrator" is redeclared and "propagate strict" wasn't in the constraining type - in that case the parameter would be gone from "Y".
A hierarchical "propagate strict" modifier will introduce "strict" at the top-level (the lexical scope of the modifier).
Gerd: What is the gain? 
Jesper: Less code duplication. And new changes in LimIntegrator will automatically apply. Hans: And avoid loss of traceability.
Henrik: Also need to rename and modify the declaration in some cases. Can we refer to it in the current class? (Yes.)
What if we have several parameters with the same name? Or only if different?
Henrik: An alternative would be "alias strict=limIntegrator.strict" (un-directed alias), so you can modify "Y.strict".

Not clear if needed, but might be possible and has some advantages.

Hans & Jesper: An alternative would be to have an annotation in "strict" saying that it is propagated in this way, so that any change of "LimIntegrator.strict" can be propagated.

```
model Z
  Modelica.Blocks.Continuous.LimIntegrator limIntegrator(strict=strict);
  parameter Boolean strict=false "= true, if strict limits with noEvent(..)"
    annotation (Evaluate=true, choices(checkBox=true), Dialog(tab="Advanced"),     
     propagatedFrom=limIntegrator.strict);
end Z;
```
Could use a vendor-specific annotation for experimentation.

Stefan: If we do anything at all, I prefer a clear declaration (import strict from limIntegrator.strict). But not in favor.

Poll:
Yes: 0 
Revisit later (with more information and possible test-implementation): 8
No: 3
(9 present)

**Comment by HansOlsson** [comment]
The conclusion was "Revisit later (with more information and possible test-implementation)".
Closing until that happens to keep back-log clearer.
