### ISSUE TITLE
Clarification on array of components having different size

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2282]
Is it legal to have an array of components of different size? Example:

```mo
model M "Legal or not?"
  record R
    Integer n;
    Real v[n] = linspace(1,n,n);
  end R;
  parameter R r[:] = {R(n=2), R(n=3)};
end M;
```

This is not conform to the Modelica language specification (3.4), section 10.1: "The number of dimensions and the dimensions sizes are part of the type". This leads to a different record type at each element of the array. This in turn violates the first sentence of section 10 "An array can be regarded as a collection of values, all of the same type".

@gkurzbach FYI
See also #1432

**Comment by gkurzbach** [comment]
> `parameter R r[:] = {R(n=2), R(n=3)};`

Yes, If this would be written as modification 

> `parameter R r[2](n={2,3});`

then the rule 7.2.5 to nested modifiers would apply and the expression is split and assigned seperately to the array components. But here there is a solid value on the right side which needs be heterogeneous, which is not allowed.
May be this difference could be made clearer in the spec.

**Comment by gkurzbach** [comment]
There are also further consequences of this restriction on value expressions: it is not possible to give them as arguments to functions, because a value is needed then.

**Comment by jespermattsson** [comment]
So would you argue that `f(r)` would be illegal then?

That would be a major usability concern. The user would likely have a hard time understanding why they are not allowed to pass an array of records to a function in some specific cases. 

I understand that allowing it complicates the type system, we also have some problems with such types. If we want to forbid it, can it really be done in a consistent way without being so brutal as to forbid non-constant array sizes in record declarations? Two instances of the same record class not being of the same type is not exactly something that you would expect.

**Comment by gkurzbach** [comment]
We have a third party library which uses this, but basically as a replacement of a heterogenous array.
instead of 
`Real r[3,:]={1:3,4:8,9:15}; `
(because it is rejected) they write
```
record R 
    Real r[:]; 
end R;
R r[3]={R(1:3),R(4:8),R(9:15)};
```
and it seems to work, atleast in Dymola.

**Comment by jespermattsson** [comment]
> Yes, or any other use of a heterogeneous array. E.g. we already forbid the case where the slicing operator `m.a` when an array of components, m, each containing an array 'a' would create a heterogeneous array (i.e. the different a have different sizes).
I do think that there is some difference between a jagged array and an array of records containing differently sized arrays. When you write `r.v`, it is more clear that you are making a slice, and that the rules in 10.6.9 "Slice Operation" applies. It is however a bit weird that the simple access `r` is an error, despite the declaration being valid.

> Forbidding the declaration just for records seems odd (seems like such an arbitrary restriction) , but on the other hand I'm unsure what an heterogenous array of records will be used for.
> 
> Thus I'm unsure whether this will be an issue in practical - or primarily a language-lawyering issue.
The example Gerd is referring to is in one of Modelon's libraries. I think it is used to describe complex geometries. I'll see if I can get more information on why it was needed.

My main concerns are ease of understanding the semantics and expressiveness. 
You _can_ likely express anything that this would be used for in other ways - the question is how cumbersome it would be.
As for the ease of understanding, I'd prefer forbidding this also in record declarations over only forbidding it in expressions. Then it would at least be consistent - if you can declare `r`, then you can also refer to it. Also that would also mean that you can actually simplify the type system - otherwise you'd still need to be able to represent the complex record type arrays for the component.

**Comment by HansOlsson** [comment]
> My main concerns are ease of understanding the semantics and expressiveness.
> You can likely express anything that this would be used for in other ways - the question is how cumbersome it would be.

My concern is that we are creating a restriction for array of records that isn't present for array of models.  However, I still believe we need to understand whether this is practical - or primarily a language-lawyering issue.

@gkurzbach Dymola handling that was unexpected. I guess the reason is that we have skipped a check in that case.

I don't know how important that use-case is. We could, obviously, change to allow heterogeneous array of records. The implications would need to be analyzed.

**Comment by HansOlsson** [comment]
Ragged arrays in general would allow handling of array of StateSpace where the different StateSpace-components have different sizes of A-matrices.
 
`  StateSpace arr[2](A={ [1,2;3,4], [5] });`
so that `arr[1].A=[1,2;3,4]` and `arr[2].A=[5]`.

Would be a large tool implementation cost and problem with getting it right in the specification, and unclear if needed. Just for records:  `{R(n=2), R(n=3)}` and `{R(A=[1,2;3,4]), R(A=[5])}`, only the first one could be written as modifier for record array, the second one needs the extended semantics.
(Pure ragged array seems to be rejected.)

Allow this for record expressions by changing the type-system (assuming it works): 4
Allow this for record variables (need to use modifier to construct, unclear how to use): 1
Require record variables to be homogeneous: 5

With more convincing use-case more people could go for first option. Jesper will investigate.

Operations on array of records: indexing (what is the type?), passing to function, (slicing already specified), array concatenation, and if-expressions selecting between them.

**Comment by jespermattsson** [comment]
The general use case is data sets - some list of grouped data, where each entry may contain arrays of differing sizes. 

The specific use case that Gerd ran into in our library was that we have a complex shape described by a mesh (i.e. a list of connected triangles that form the surface area of a body). The surface of this shape is then divided into different "heat transfer areas". Each area is described by a record that among other things contains an array listing the triangles that comprise that area, as indices into the array that contains the mesh. Naturally, these areas may consist of different number of triangles.

We have tried to find an alternate representation for this that would avoid the problem, but we have so far not been able to find one where the areas are specified in a way that is reasonable for the user.

**Comment by HansOlsson** [comment]
Language group:

Seems to still need more investigation. One possibility would be to use a different syntax for creating ragged arrays that differs from the one creating homogenous arrays.

@jespermattsson was previously assigned to the ticket.

**Comment by beutlich** [comment]
Seems to be releated to #655 (if not even a duplicate), which was not closed with a usable resolution.

**Comment by HansOlsson** [comment]
It would be good to have this resolved. We now have some use cases for this; meshes as above, parameter sweeps (a record for each variable - and different number of values for each variable).

The proposal to generalize is:

An array can be regarded as a collection of values, all of the same type
->
A non-record array can be regarded as a collection of values, all of the same type.
An array of records may contain scalar record values those elements different in their dimension sizes, but apart from that they must be of the same type. Such heterogenous arrays may only be used completely, sliced as specified, or indexed.
An array of arrays must have the same dimension sizes for all of the arrays (with the same exception for records).

**Comment by perost** [comment]
Perhaps it's outside the scope of this issue, but I would prefer "collection of type compatible values" (or expressions) rather than "collection of values, all of the same type". "All of the same type" implies that they must be exactly the same type as defined by 6.3, while it's actually 6.7 (Type Compatible Expressions) that applies to arrays. Same applies to the "An array of records"-sentence.

Also, it seems odd to have 6.7 say it applies to arrays but then have 10 say that there are exceptions for arrays of records, I think we should try to avoid such conflicts if possible.

**Comment by HansOlsson** [comment]
> Perhaps it's outside the scope of this issue, but I would prefer "collection of type compatible values" (or expressions) rather than "collection of values, all of the same type".

Good point, and with reference to 6.7.

> Also, it seems odd to have 6.7 say it applies to arrays but then have 10 say that there are exceptions for arrays of records, I think we should try to avoid such conflicts if possible.

Ok, should add the exception in the first bullet point of 6.7 as well.

**Comment by beutlich** [comment]
Summarizing by example:

```mo
model M "Legal in Modelica 3.5"
  record R
    Integer n;
    Real v[n] = linspace(1,n,n);
  end R;
  parameter R r[:] = {R(n=2), R(n=3)} "Heterogenous array of records";
end M;
```

**Comment by henrikt-ma** [comment]
@beutlich, that looks like an example we should have in the specification, ideally extended with some examples of the legal and illegal operations on `r`.
