### ISSUE TITLE
ModelicaCompliance doesn't parse due to variability prefix in short class definition

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2309]
It could be argued that this is a problem with ModelicaCompliance, but I'd like to try the idea that the error is in the specification.

In [ModelicaCompliance](https://github.com/modelica/Modelica-Compliance/blob/master/ModelicaCompliance/Inheritance/Restrictions/PrefixedClassWithExtends.mo), one finds this piece of code:
```
model PrefixedClassWithExtends
  extends Icons.TestCase;

  model A
    Real x = 1.0;
  end A;

  model CA = constant A;
…
```

According to the grammar in the specification, the definition of `CA` is illegal, since a short class definition has `base-prefix`, (that is, `[ input | output ]`) instead of all the prefixes allowed by `type-prefix` (including `[ discrete | parameter | constant]`).

This restriction also makes the following very handy short class definition illegal:
```
connector Real_DiscreteInput = discrete input Real "'input discrete Real' as connector";
```
The workaround for this is rather inconvenient since it forces the introduction of an arbitrary name for the single signal in the connector:
```
connector Real_DiscreteInput "'input discrete Real' as connector"
  discrete input Real x;
end Real_DiscreteInput;
```
(By the way, would it even be legal to use this connector as an input to a class with `block` restriction?)

The two situations above, in combination with believing that other tools manage to parse the ModelicaCompliance source, make me think that it is an omission in the specification to not allow variability prefixes in short class definitions.

**Comment by henrikt-ma** [comment]
On the same theme, [ModelicaCompliance](https://github.com/modelica/Modelica-Compliance/blob/master/ModelicaCompliance/Components/Prefixes/PrefixConflictFlowStreamShort.mo) contains this piece of code:
```
model PrefixConflictFlowStreamShort
…
  connector FlowC = flow C;
…
```
which is also using an illegal prefix that belongs in `type-prefix`.  (I'm beginning to think that I must have misread the specification…)

**Comment by HansOlsson** [comment]
It was changed in Modelica 3.4: #917 
And currently ModelicaCompliance is on Modelica 3.2r2 I think, so we shouldn't update it yet.

**Comment by henrikt-ma** [comment]
That's right, but it seems like we missed to consider the prefix `discrete` in #917.

Then what remains for the present issue is to suggest to let `discrete` back in, like so:
```
base-prefix :
  [ discrete ] [ input | output ]
```

**Comment by HansOlsson** [comment]
> That's right, but it seems like we missed to consider the prefix discrete in #917.

It is true that we didn't include it, but I'm not sure that it was missed. 

I believe there was some discussion about it, that I couldn't find, - the basic problem is that 'discrete Real' is a bit counter-intuitive, and only rarely makes sense. Thus there seems to be less need for it as a base-prefix.

E.g. the following connector
`connector Real_DiscreteInput = discrete input Real "'input discrete Real' as connector";`
is practically unusable.

The reason is that section 4.4.4 says "If a Real variable is declared with the prefix discrete it must in a simulation model be assigned in a when-clause, either by an assignment or an equation." But normally you connect a signal to the input, you don't set the input signal directly in a when-clause (there are even rules against this).

Or in other words: we might consider removing the discrete keyword altogether.

The logic is that 'discrete' marks the variables that are given by when-clauses, not all variables that only vary at events. That means that discrete-ness doesn't require structural analysis, which can be seen as a simplification.

For synchronous models we on the other hand require structural analysis, but variables are not only "clocked" (corresponding to "discrete") but "clocked with a certain clock" so that we don't mix them.

**Comment by henrikt-ma** [comment]
OK, then we fail to enforce the rule in 4.4.4.  Our interpretation, which I argue is a very useful one, is that the `discrete` prefix makes it explicit that the variable has discrete variability.  This can be very helpful for understanding the semantics of the model.

As a better alternative to removing `discrete`, I think we should consider introducing `continuous` as a way of making it explicit that a variable has continuous variability.

**Comment by henrikt-ma** [comment]
The MCP has now been allocated an MCP number, and I've made an initial commit with documents for the MCP branch:
https://github.com/modelica/ModelicaSpecification/tree/MCP/0033/RationaleMCP/0033

Please feel free to engage in discussions on that branch!

**Comment by HansOlsson** [comment]
Two parts:
* Changing discrete - should have a separate issue for that
* Clarifying the issue with ModelicaCompliance; that is now done
