### ISSUE TITLE
Access.icon protected variables

### ISSUE THREAD

**Issue by thorade** [modelica/ModelicaSpecification#2318]
In section 18.9.1 Protection of Classes the different levels are described. 
https://github.com/modelica/ModelicaSpecification/blob/1da1aede83b633656ab613e37556e837a8c53e72/chapters/annotations.tex#L1755-L1760

For clarification, it would be helpful to explicitly state that **protected** variables must not be accessible. 
Also, it might be helpful to state what "access" includes: storing of values in results, access via dot notation and assign to another variable, printing values and/or variable names from error messages or asserts.

**Comment by HansOlsson** [comment]
Language group:

Instead of specifying that protected variables cannot be accessed specify that in general only the parts explicitly listed as visible can be accessed.

A class may have the following annotations to define what parts of a class are visible (...)
->
A class may have the following annotations to define what parts of a class are visible, and only the parts explicitly listed as visible below can be accessed (...)

Agreement by acclamation.
