### ISSUE TITLE
Is missingInnerMessage restricted to a literal string?

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2334]
Is the value of the missingInnerMessage annotation restricted to a literal string, or may one write something like:

    annotation (missingInnerMessage =
        "there is no inner declaration corresponding to" + getInstanceName());

**Comment by svorkoetter** [comment]
By the way, my guess is that the answer is "no" (the spec only gives an example, which is a literal string, and I suspect no tool implements more than that). In that case, I would suggest that, analogous to Text annotations, one can embed "%name" in the message to achieve the above.

**Comment by HansOlsson** [comment]
I agree with the analysis that it is not currently intended.
I would prefer not to have that, but let tools automatically handle that when needed.

The reason is that there are sometimes multiple outer components referring to the same missing inner components, and in that case having "there is no inner declaration corresponding to comp1.world", "there is no inner declaration corresponding to comp2.world", "there is no inner declaration corresponding to comp2.a[1].world", etc. would be annoying. 
A tool can in a better way collect them.

**Comment by HansOlsson** [comment]
Language group:

Clarify that tool is expected to give context for the error message, thus there is no problem with restricting missingInnerMessage to a literal string.

Agreement by acclamation.
