### ISSUE TITLE
Ambiguities in definition of % parameters in Text annotations

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2335]
The documentation of the %xyz parameters in text annotations is somewhat ambiguous. The following questions arise in my mind:

1. For the %par form (as opposed to the %{par} form), can quoted names be used? I.e., can one write, "blah blah %'foo bar' blah blah", or must one use the %{par} form for this?
2. %class is "replaced by the name of the class". Which class? The enclosing class (as mentioned in the point just before it), or the class of the component? The fully qualified name, or just the last part of the name?

**Comment by HansOlsson** [comment]
Language group:

"%'a.b'" or is "%{'a.b'}" required? Should also work for "%'a.b'" since no ambiguity in where it ends. "%{a.b}"
However, change example to not use "%{par}m" due to decision about displayUnit, where "m", but use e.g."%{w}x%{h}"
"%class" is only last part of the name. (Clarify in spec.)
(It can only be used directly in a class, so which class is unambiguous.)

Agreement by acclamation.
