### ISSUE TITLE
Obsolete base classes

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2338]
See the following example package and model for a plain demonstration about warning on obsolete base classes.
```mo
package P
  model A annotation(obsolete="I am obsolete."); end A;
  model B extends A; end B;
end P;
```
and
```mo
model M
  P.B b;
  annotation(uses(P));
end M;
```
1. When should a Modelica tool warn about **loading** of obsolete types?
In the [equivalent C++14 code](https://godbolt.org/z/0FnJ3g), Clang 8.0.0 explicitely warns about the deprecated base class `A` when defining `B`. There is no such warning in GCC 8.3. 

2. When should a Modelica tool warn about **usage** of obsolete types?
In the equivalent C++14 code, neither Clang 8.0.0 nor GCC 8.3 warn about using the deprecated class `B`.

Should we clarify this? Or is warning verbosity always a tool issue?

**Comment by HansOlsson** [comment]
To some degree warning verbosity is a tool issue. The question is if there is a portability issue that requires specifying more.

And it is interesting to see that the tools differ regarding base-class and component use.
When being clear I think we need to consider that there are two kinds of uses:

- An existing model that is translated/check/... uses the obsolete model.
- The user directly uses the obsolete model to add a component, base-class, in redeclaring a component,... (note that this can be both using drag'n'drop and just typing text).

In the second point I added "directly" - the reason is that if someone built a model, `M`, using an obsolete model, `O`, I don't see a point in making it too difficult to reuse `M `before it is improved to replace the obsolete model by a better alternative; but I see a point in not using `O` directly.

**Comment by HansOlsson** [comment]
Language group:

Seems too complicated to specify fully.

**Comment by HansOlsson** [comment]
Language group:

Do not inherit, so if you want to tell end-users to not use "B" you have to put obsolete in B as well. One reason is that "B" could be developed separately - and should be corrected. If that is not the case we need the annotation in "B".

Agreement by acclamation.
