### ISSUE TITLE
Enhance textString macros by formatting options and displayUnit

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2339]
It would be convenient if the String formating options of section 3.7.1, particularly `significantDigits` and `format`, are also available for the text macros `%par` / `%{par}` of section 18.6.5.5.

```mo
model M
  model DisplayTime "Display time in icon (with custom unit and formatting)"
    Real displayTime(displayUnit="ms") = time "Display time";
    annotation(Icon(graphics={Text(extent={{-100,60},{100,-60}}, textString="%displayTime")}));
  end DisplayTime;
  DisplayTime d annotation(Placement(transformation(extent={{-60,40},{-40,60}})));
end M;
```

Additionally, it would be also convenient, if the `displayUnit` could optionally be displayed in the textString.

**Comment by HansOlsson** [comment]
I agree about the underlying issues, and some variant of `significantDigits `and/or format could be helpful. I assume something like `%{par,significantDigits=7} `would work.

For `displayUnit `Dymola 2019 added an option `Advanced.UseDisplayUnitInDiagram=true;` that automatically displays numeric values with their corresponding `displayUnit `in the diagram - so that "%displayTime" will show "1 s" as "1000 ms". 

Standardizing that would be a good way of using the displayUnit in the display, and I see the following benefits compared to attempting to manually use displayUnit for the variable
- No need to update libraries, it just works.
- Non-literal values will not have misleading displayUnit.
- It is easier to get good formatting of the numeric value with displayUnit according to bipm-recommendations; in particular the spacing related to the degree symbol takes care.

![CoupledClutches](https://user-images.githubusercontent.com/13217430/55540169-aeee2e80-56c2-11e9-8423-67980c32de8c.png)

**Comment by beutlich** [comment]
Formatting even is possible by means of DynamicSelect (but does not respect the displayUnit).

```
model M
  model DisplayTime "Display time in icon (with custom unit and formatting)"
    Real displayTime(displayUnit="ms") = time "Display time";
    annotation(Icon(graphics={Text(extent={{-100,60},{100,-60}}, textString=DynamicSelect("%displayTime", String(displayTime, significantDigits=3)))}));
  end DisplayTime;
  DisplayTime d annotation(Placement(transformation(extent={{-60,40},{-40,60}})));
end M;
```

**Comment by HansOlsson** [comment]
Language group:

Tools shall display numerical values with displayUnit, formatted according to bipm-specification.

Agreement by acclamation.

Significant digits:
Possibility to explicitly specify maximum number of significant digits: 
Favor: 1
Against: 2
Abstain: 5

Does not seem like a great interest in adding it; so do not add at this time.
