### ISSUE TITLE
Should cells in an array of expandable connectors be required to have the same members?

### ISSUE THREAD

**Issue by zimonkuhsmodelon** [modelica/ModelicaSpecification#2345]
Connecting to an expandable connector's non-declared member such as here:

    model M
        expandable connector EC
        end EC;

        connector C = Real;

        EC ec;
        C c;

    equation
        connect(c, ec.x);
        c = time;
    end M;

introduces `ec`'s member `x`. However, would `ec` be an array of expandable connectors:

    model M
        expandable connector EC
        end EC;

        connector C = Real;

        EC ec[3];
        C c;
    equation
        connect(c, ec[1].x);
        c = time;
    end M;

then the specification does not detail whether or not this would introduce `x` for `ec[1]`, `ec[2]`, and `ec[3]` as well. If this is unwanted, I assume the below would be required to have all cells in `ec` have `x`:

    model M
        expandable connector EC
        end EC;

        connector C = Real;

        EC ec[3];
        C c;
    equation
        connect(c, ec[1].x);
        connect(ec[1], ec[2]);
        connect(ec[2], ec[3]);
        c = time;
    end M;

This could be a bit cumbersome, but might be wanted since it would mean that the user has to be explicit in introducing `x` for all of the cells.
Should there be an introduction of expandable connector members for cells in the same array?

Edit: Removed mention of "implicitly connected array cells" due to comment by @jespermattsson . Clarified some parts.

**Comment by jespermattsson** [comment]
There is a distinction between if they are implicitly connected and it they should all contain the same elements. If they would be connected, then equations would also be generated for them, and that would make the array largely irrelevant - a single expandable connector would do.

The question if they must contain the same elements is more interesting, and is somewhat related to #2282. Is there any general requirement that the cells of an array contain the same elements?

**Comment by zimonkuhsmodelon** [comment]
@jespermattsson 
Thank you for your input! You are correct in that it would make the array redundant, now that I actually think about it... I will revise the issue to reflect this.

**Comment by HansOlsson** [comment]
Language group:

An argument for modifying all array elements would be that modifying the array type, but if they were "EC ec1, ec2, ec3;" the different elements could have different type - and we have ragged arrays for some cases.

A use case could be 4 wheels; and e.g. adding a sensor for one wheel. Requiring the other 3 wheels to also have a sensor just seems like a complication - even if in most cases all 4 wheels are identical with identical expandable connectors. But arrays of expandable connectors seem odd in general - and not compelling use case.

Ragged arrays should not matter - since you cannot use the array as e.g. argument to a function.

Seems that conclusion is that the array elements can be different; and should be clarified in some way.

In case you have an array of expandable connectors it is natural for this array to become ragged.

**Comment by jespermattsson** [comment]
This seems done.
