### ISSUE TITLE
Remove empty enumeration `enumeration()` from the language

### ISSUE THREAD

**Issue by axelmartenssonmodelon** [modelica/ModelicaSpecification#2349]
Modelica has two overlapping enumeration constructs: unspecified enumeration, e.g. `type E = enumeration(:)`, and empty enumeration, e.g. `type E = enumeration()`. I find it unclear what empty enumeration `enumeration()` means, and I cannot find any use cases for it that isn't also covered by unspecified enumeration `enumeration(:)`. I propose we simplify the language by removing empty enumeration `enumeration()`.

[The grammar](https://modelica.org/documents/ModelicaSpec34.pdf#page=266) specifies the two enumeration constructs in the production:

```
short-class-specifier :
   IDENT "=" base-prefix type-specifier [ array-subscripts ]
   [ class-modification ] comment
   | IDENT "=" enumeration "(" ( [enum-list] | ":" ) ")" comment
```

where the optional `[enum-list]` makes empty enumeration possible.
If we remove the optionality so that `[enum-list]` becomes `enum-list`, then we remove empty enumeration `enumeration()` from the language.

Alternatives:
* specify what empty enumeration means, and allow both empty enumeration `enumeration()` and unspecified enumeration `enumeration(:)` in the language.
* remove empty enumeration `enumeration()` from the language by modifying the grammar.

**Comment by HansOlsson** [comment]
This should ideally be handled together with #1010 since extending an empty enumeration seems like a straightforward use for them.

If we don't want to add the possibility of extending enumerations then we might as well remove empty enumerations as they cannot be used.

With "cannot be used" I mean even if you can declare the `type E=enumeration();` it is practically useless as:

- There are no valid values of that type, so a variable of that type will not work.
- You cannot extend from it.
(Obviously there are some esoteric uses of it, but...)

**Comment by sjoelund** [comment]
It seems the OpenModelica implementation of the Modelica grammar does not actually allow `enumeration()`. We have never encountered any code using the construct either (all libraries parse or use really weird things not part of any Modelica standard)... So it should be relatively safe to remove it if we want.

**Comment by jespermattsson** [comment]
> This should ideally be handled together with #1010 since extending an empty enumeration seems like a straightforward use for them.
Why would you want to extend from an empty enumeration? I can't really see a use-case where a replaceable unspecified enumeration wouldn't work just as well.

**Comment by sjoelund** [comment]
```mo
model N
  replaceable type E = enumeration(A);
  function f
    input E e;
    output Boolean b;
  algorithm
    b := e == E.A;
  end f;
end N;

model M
  extends N(redeclare type E = enumeration(A, B));
  E e;
  Boolean b = f(e);
end M;
```

Dymola 2018 says for this `This is for some reason not allowed in Modelica, use enumeration(:)`. Old OpenModelica front-end happily accepts it (new one does not).

**Comment by HansOlsson** [comment]
> Why would you want to extend from an empty enumeration? I can't really see a use-case where a replaceable unspecified enumeration wouldn't work just as well.

For extended enumeration there seems to be a programming idiom of extending the enumeration by adding one new value "a" and handling it - and relying on the base-implementation to handle the other cases. That naturally leads to starting from an empty enumeration.

As far as I can tell `enumeration(:)` isn't widely used either. As far as I recall it was introduced because there were discussions about co- vs. contra-variance for sub-typing for enumeration, and it sort of avoided the issue.

**Comment by jespermattsson** [comment]
You could simply define extending `enumeration(:)` as a no-op, then you could start with that instead. As a bonus, the rules for unspecified enumeration mean that you get a check that you don't try to use it un-extended.

**Comment by HansOlsson** [comment]
Language group:

Conclusion: No change. Both enumeration() and enumeration(:) are useful as bottom and top of type-hierarchy.
