### ISSUE TITLE
clarify: classes in package

### ISSUE THREAD

**Issue by thorade** [modelica/ModelicaSpecification#2350]
Specialized class `package` may only contain classes, but as everything is a class, it would be helpful to clarify what must not be in a package. All **specialized** classes allowed, but variables/parameters/ forbidden?
In the context of replaceable packages for media, it might be interesting to have a parameter in a package on top-level.

https://github.com/modelica/ModelicaSpecification/blob/1da1aede83b633656ab613e37556e837a8c53e72/chapters/classes.tex#L817-L819

**Comment by HansOlsson** [comment]
> Specialized class package may only contain classes, but as everything is a class, it would be helpful to clarify what must not be in a package. All specialized classes allowed, but variables/parameters/ forbidden?

The linked text says "classes and constants" - to me that already answers the question since it rules out components that are more variable than constants (that is parameters and normal variables); and it allows all specialized classes.

Am I missing something?

> In the context of replaceable packages for media, it might be interesting to have a parameter in a package on top-level.

Currently that is handled somewhat awkardly using constants in the package, but to me that it is a specialized topic.

**Comment by thorade** [comment]
Thanks for the quick reply, I think I read it correctly then.
