### ISSUE TITLE
Consistent quote-symbols

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2364]
As noticed in review of #2353 the quotes are currently a bit of a mess.

The correct solution seems to be:
* In Modelica code use "
* For inlined literal strings in Modelica have " inside the code-string, like `\lstinline!"External"!`
* For Modelica-code that isn't a string: neither use quotes on their own nor combined with lstinline - just use `\lstinline!state!`
* For references use a bibliography (preferably with bibtex), instead of using "" for titles (such as SI-standard).
* In normal English text use ` ``double-quotes'' ` for actual quotes, and otherwise just write it as is.

There might be additional cases that I missed.

**Comment by henrikt-ma** [comment]
For normal English text, I think that we should also consider the use of \emph instead of double quotes.  To me, the double quotes are the solution for environments where writing slanted text isn't an option (for example, when writing by hand).

**Comment by HansOlsson** [comment]
> For normal English text, I think that we should also consider the use of \emph instead of double quotes.  To me, the double quotes are the solution for environments where writing slanted text isn't an option (for example, when writing by hand).

Ok, that is also an option. 

However, I am unsure if it is should be \emph (something that is emphasized) or \textit (something in a different voice), or something else.

I tried to look at https://specification.modelica.org/master/Ch16.html#definitions
And found the following examples:
* In section 3.8.3 the term “discrete-time” Modelica expression and in section 3.8.4 the term “continuous-time” Modelica expression is defined.
* “**base-clock partition**” etc
*  This notation is used to emphasis when a standard function call is used (“is an expression”), instead of restricting the input (“is a Component Expression”)

In these cases they are used for technical terms (but more to show that it is a term than for emphasis), and one possibiltiy would be to embrace hypertext and instead have discrete-time as the link to section 3.8.3. Clearly we shouldn't have both bold and italic/quotes.

**Comment by henrikt-ma** [comment]
The kind of style I have in mind seems fairly in line with this description: https://theeditorsblog.net/2014/05/12/marking-text-choosing-between-italics-and-quotation-marks/
In particular, I'd like to point out the use of quotation marks to indicate sarcasm — it's not what we do most of the time.

Direct use of \textit is a bad idea, since it won't be visible when part of non-normative text, etc — that's the whole point of \emph.  Also using some slightly different font, like \textsl is only going to look like some kind of typesetting error.

I find boldface too distractive when used in running text, except for the extremely rare occasion of really having to put crazy amounts of emphasis on something (I wonder if there's anything in the Modelica spec that would need that strong emphasis).  Besides that, I find it very useful for marking some kind of heading at the lowest level (description lists, labels of figures and tables, theorem titles, etc).

I don't think we should rely on hyperlinking as a way of indicating emphasis, since hyperlinking only makes sense as long as hyperlinks aren't everywhere one might expect them.  Once one reaches a point where most things that could be linked actually are hyperlinked, the visual hints that things are linked get too distracting and have to be removed.

**Comment by HansOlsson** [comment]
> The kind of style I have in mind seems fairly in line with this description: https://theeditorsblog.net/2014/05/12/marking-text-choosing-between-italics-and-quotation-marks/

I agree that we should follow some guide, but that does not seem like an ideal guide for us, since it isn't for technical/scientific text. 

More suited guides might be APA, which says the following:
https://writing.stackexchange.com/questions/10750/when-should-i-use-italics-in-scientific-writing

I can see that "first time" might be problematic, but we could say that first time is where it is introduced - which really should be first time at least in that section/chapter.

Following that for the cases above seems to give: 
Remove quotes in:
>> In section 3.8.3 the term “discrete-time” Modelica expression and in section 3.8.4 the term “continuous-time” Modelica expression is defined.

Italics/Emph instead of quoted bold for (first time it is used):
>> “**base-clock partition**” etc

Remove quotes for:
>> This notation is used to emphasis when a standard function call is used (“is an expression”), instead of restricting the input (“is a Component Expression”) 

For some reason searching also found:
https://jamalahmed.wordpress.com/2013/05/12/emphasizing-text-when-to-use-bold-and-italics/
https://www.prismnet.com/~hcexres/textbook/high.html

>Direct use of \textit is a bad idea, since it won't be visible when part of non-normative text

I get that point, but there are others that claim that \emph is misleading if you don't really use it for emphasis. (And obviously if used for introducing terms the issue with non-normative text seems irrelevant.)


Finally, I also asked our documentation department, and it seems they directly use none of the above.
Instead each fragment is tagged - whether it is user-input, output etc.

That may be the solution, i.e. in the remaining cases use \newterm (or similarly) instead of \emph - even if newterm is internally defined as \emph.

**Comment by henrikt-ma** [comment]
The APA guide had sensible rules for use of italics, but didn't even mention quotation marks.  I fully agree with the _mere emphasis_ item, which I think may be the one that causes most of the confusion (claims made by "others" [here, think sarcasm]) just because the LaTeX command is called \emph.

I would be fine with introducing dedicated markup commands that just forward to \emph, as long as the list of such commands is kept very short so that it is always easy to figure out which one to use.  Given that we're in the LaTeX world, where some of the things in the APA list are naturally handled by the math switch and BibTeX styling, what markup commands would we need besides \firstuse? \linguisticexample?

One of my favorites that's not in the APA list is \filename, which I find logical to treat in the same way as a book title.  This doesn't apply when a filename appears as part of a code snippet (Modelica code, command line example, etc), but just when a filename is embedded in normal text.

**Comment by HansOlsson** [comment]
I agree that we shouldn't over-use additional commands, and using a proper bibliography will also help.

Regarding \filename there are two cases: a fixed file-name such as package.mo and a variable file-name such as MyPackage.mo for the package MyPackage. We don't need to make distinction - but some do.

Technically I believe that should also be \filepath to handle cases such as "Modelica 3.2.1/Mechanics/C.jpg".


> The APA guide had sensible rules for use of italics, but didn't even mention quotation marks.

I guess we have to buy the proper APA manual (6th edition) to find those rules. Obviously due to the first A it recommends using double quotation marks for short actual quotes (longer quotes should be indented), but there might be additional more subtle rules.

**Comment by henrikt-ma** [comment]
I don't see a reason to distinguish between \filepath and \filename.  It would be very strange to handle them differently anyway.

**Comment by HansOlsson** [comment]
> I don't see a reason to distinguish between \filepath and \filename.  It would be very strange to handle them differently anyway.

Agreed; I merely meant that it might be better to call it \filepath instead of \filename.

**Comment by dietmarw** [comment]
So why not simply define the macro as `\file`?

**Comment by dietmarw** [comment]
I do something similar in my writing with `\code`?

**Comment by henrikt-ma** [comment]
I would prefer either \filename or \filepath over \file because \file is too short with too much risk of naming conflicts etc.  (The spell checker in Chrome doesn't like \filepath, by the way.)

**Comment by HansOlsson** [comment]
Would be good if we could get an agreement on these issues at the next meeting; and that someone could volunteer to do the work.

**Comment by HansOlsson** [comment]
There seems to be agreement to introduce some commands like \firsttime, and \filename (Wikipedia includes everything under filename - https://en.wikipedia.org/wiki/Filename ).
Henrik volunteers - to use/introduce emph/firstime instead of quotes, but not find all \firsttime there aren't currently in quotes.

**Comment by henrikt-ma** [comment]
When working on this, I notice that the _Synchronous Language Elements_ chapter isn't using the normal markup for inline code.  Instead of `\lstinline`, it is full of `\textbf`.  I suggest that the entire chapter is rewritten using the same markup as the rest of the specification.

**Comment by henrikt-ma** [comment]
Another big obstacle for doing this right is the primitive formatting of non-normative parts.  These really need to be re-written using the `nonnormative` environment in order to allow clean use of things such as `\lstinline`, quotation marks, and `\emph`.

**Comment by HansOlsson** [comment]
This should ideally be cleaned up before the next release - and it was only partially resolved at Design101. Note, it is not a blocker.

**Comment by henrikt-ma** [comment]
Aren't we in a pretty good shape with regards to this now, considering that the there is #2503 to decide on how to use `\textbf`, and that chapter _Synchronous Language Elements_ is a formatting mess in general covered by #2562?

**Comment by henrikt-ma** [comment]
@HansOlsson don't you think this can be closed now?

**Comment by HansOlsson** [comment]
> @HansOlsson don't you think this can be closed now?

Yes.
