### ISSUE TITLE
Removing "allows to" - tweet by Terrence Parr

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2380]
https://twitter.com/the_antlr_guy/status/1119333987275534336

> Non-native English speakers: please immediately, and with extreme prejudice, delete "allows to ..." from your internal grammar model. Drives us crazy! Thank you.

There are at least 12 uses of that construct in the current document, and it seems we can in those cases replace "allows to" by "allows us to ".

**Comment by xogeny** [comment]
I don't think there is anything wrong with "allows us to" (sounds natural enough to me).  Another alternative would be "makes it possible to".  The use of the infinitive here can also be tweaked so instead of "allows us <infinitive>" substitute "permits/allows <present tense>".  For example, 

```
This feature also allows to define multi-rate systems
```

becomes

```
This feature also permits defining multi-rate systems
```

But honestly, if I were speaking I'd almost certainly say "allows us to".

**Comment by HansOlsson** [comment]
> I don't think there is anything wrong with "allows us to" (sounds natural enough to me).

Just to be clear: currently it just says "allows to", and I assume you agree that isn't natural?

**Comment by svorkoetter** [comment]
Or more formally, "allows one to".

**Comment by mtiller** [comment]
Just to clarify...

Yes, I understood the current specification says "allows to" and you (Hans) were suggesting "allows us to" which I just wanted to indicate was fine (i.e., your solution is fine).  But I wanted to just add a few more alternatives so that we didn't necessarily replace it with the same phrase everywhere.  Stefan's additional alternative "allows one to" also sounds fine to me.

**Comment by beutlich** [comment]
I am not a big fan of "allows one to" since my teachers at University of Bristol strictly insisted on avoiding it.

My examples:
1. allows to compute - wrong
1. allows us to compute - well, ok
1. allows the user to compute - well, ok
1. allows the computation - ok
1. allows one to compute - should be avoided

Have a look at https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/commit/9fce550aa32e30e67db9d7cdf21eb3484517c349 where we fixed it for the conference article of the Modelica_DeviceDrivers library.

**Comment by svorkoetter** [comment]
Another possibility, which I tend to favour when writing technical documentation, is "lets one"

On Sun, 20 Oct 2019 06:54:11 -0700
Thomas Beutlich <notifications@github.com> wrote:

> I am not a big fan of "allows one to" since my teachers at University
> of Bristol strictly insisted on avoiding it.
> 
> My examples:
> 1. allows to compute - wrong
> 1. allows us to compute - well, ok
> 1. allows the user to compute - well, ok
> 1. allows the computation - ok
> 1. allows one to compute - should be avoided
> 
> Have a look at
> https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/commit/9fce550aa32e30e67db9d7cdf21eb3484517c349
> where we fixed it for the conference article of the
> Modelica_DeviceDrivers library.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/modelica/ModelicaSpecification/issues/2380#issuecomment-544254516


-- 
Stefan Vorkoetter
Senior Architect
Maplesoft
