### ISSUE TITLE
Specifying declaration equations

### ISSUE THREAD

**Issue by Daiwen** [modelica/ModelicaSpecification#2385]
In Section 4.4.2.1 _Declaration Equations_ , we cover the cases of builtin types, vectors and matrices, but we say nothing about other components types. In particular, `ModelicaCompliance.Modification.Flattening.Merging2` uses a modifier to give a declaration equation to `c4.x3` which is an instance of a class.

Shouldn't we forbid declaration equation for instance of models, blocks, and classes, and rewrite `ModelicaCompliance.Modification.Flattening.Merging2` to use records rather than classes?

**Comment by HansOlsson** [comment]
We could have a similar restriction as in #2308 and also make sure that it applies to normal equations and algorithms.

**Comment by HansOlsson** [comment]
To clarify the proposal:

Only components of the restricted classes type, record, operator record, and connector may have declaration equations, or appear as left-hand-side in algorithms.

(Not sure where and what to write for equations. The point about equations isn't merely restricting lhs and/or rhs in this way but _almost_ any expression in them; as we don't want `foo(robot)`).

**Comment by HansOlsson** [comment]
Gerd: Should also consider External Objects.
Henrik: Agree in general for expressions, but may be special cases.
In particular record-constructors taking model components, but possibly more.
Instead of limiting expressions, it could be better to only limit equality and function arguments to this (for the latter check record-constructor taking model component as argument).

Turn this into separate issue, and resolve this ticket by (and adding external objects):
Only components of the restricted classes type, record, operator record, and connector may have declaration equations, or appear as left-hand-side in algorithms.

Agreement by acclamation.
