### ISSUE TITLE
System of equations of discrete Real

### ISSUE THREAD

**Issue by agnesramle** [modelica/ModelicaSpecification#2393]
Should the following model really be allowed according to the Modelica specification?

```
 model DiscreteNonLinearSystem
   discrete Real x(start=0),y(start=0);
 equation 
 
  when time > 1 then
     x = y^2 +1;
     y = x^2-1;
  end when;
 end DiscreteNonLinearSystem;
```

Since it results in a non-linear system of equations consisting of discrete Reals as iteration variables?

If so, consider this model:
```
model DiscreteNonLinearSystemReinit
  discrete Real x(start=0),y(start=0), z(start=0);
  Real s(start=0);
equation 
  der(s)=1;  
  when time > 1 then
    z = pre(z)+x+pre(y);
    x = y^2 +1;
    y = x^2-1;
    reinit(s,z);
  end when;
end DiscreteNonLinearSystemReinit;
```

where x needs to be solved but at the same time we cannot update pre(y).

**Comment by HansOlsson** [comment]
Since this is the issue tracker for the specification itself we would prefer references to the specification if there are any specific cases and not just general questions whether it is allowed or not.

More general issues about Modelica can be asked on stackoverflow: https://stackoverflow.com/questions/tagged/modelica
Issues with specific implementations should be reported to the specific tools.

However, I can answer this one:

When-clauses were designed to allow for well-defined systems of equations in Modelica 1.4 so having discrete variables as iteration variables was part of the design, but reinit cannot be part of a system of equations as the reinit takes effect after all other equations, as specified in #578  

Thus the answer is just that it should work.
