### ISSUE TITLE
Convenient record constructor

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaSpecification#2396]
Consider the following situation: The parameters of a model are propagated as a record cellData. This parameter record cellData contains besides single parameters (e.g. Ri) an array of parameter records rcData[:]. 
```
parameter ParameterRecords.CellData cellData(
  Ri=1e-3,
  rcData={Batteries.ParameterRecords.RCData(R=0.2*cellData2.Ri, T=60),
    Batteries.ParameterRecords.RCData(R=0.1*cellData2.Ri, T=10)});
```
How to specify _conveniently_ the array of parameter records rcData without using those clumsy record constructors?
How to specify 0.2*cellData2.Ri more conveniently? I remember a discussion about self ...

**Comment by HansOlsson** [comment]
Above the component is called cellData - and refers to cellData2. Is that intentional?

When discussing convenience I don't think we should just look at source code, because part of the convenience is that tools allows you to enter that information in other forms- and e.g. automatically providing the name of the record constructor and the name of arguments. And similarly not having to type names of variables.

I'm not saying that is the only possibility, but merely that if we focus on the textual representation we miss some possibilities for convenience.

**Comment by HansOlsson** [comment]
Closing for book-keeping reasons, as there haven't been any discussion for over a year.
If there is new information it might be re-opened.
