### ISSUE TITLE
Hierarchical State Machines Limitations

### ISSUE THREAD

**Issue by mestinso** [modelica/ModelicaSpecification#2407]
Why are the "activeInState" and "timeInState" functions limited to non-hierarchical state machines?

I'm building a state machine which utilizes new Modelica 3.4 features, and the "activeInState" and "timeInState" have proved to be quite useful in non-hierarchical state machines. However, it's not clear to me why they are disallowed by design in hierarchical state machines. To me, this substantially limits the usefulness of the Modelica 3.4 state machine feature.

I propose either:
a) Making a change to allow these functions within hierarchical state machines in future versions of Modelica, or
b) Include some explanation why this is disallowed with maybe some example/hint of what should be done instead

**Comment by HansOlsson** [comment]
Note: I assume you mean "timeInState" and "ticksInState"; since "activeInState" shouldn't be limited to non-hierarchical state machines.

> I propose either:
> a) Making a change to allow these functions within hierarchical state machines in future versions of Modelica,

This might be the right solution, but it would help if you could explain how you expect them to behave in a hierarchical state machine, e.g., if the sub-state isn't changing, but the enclosing state is toggled (every second), which of the following answers is the right time:
* Time since sub-state was first entered
* Time since sub-state or enclosing was last entered: 
* Accumulated time in sub-state, since it was entered (and the sub-state wasn't left directly)

**Comment by MrMatt2532** [comment]
> Note: I assume you mean "timeInState" and "ticksInState"; since "activeInState" shouldn't be limited to non-hierarchical state machines.

Correct

> So, if enclosing state and sub-state is entered at 1 and enclosing state left at 2, and then re-entered at 3, and we ask for timeInState at 4 the different options correspond to 3s, 1s, 2s.

Between the three options: my vote would be for the 2nd option (1 second). Effectively in my mind, it's the time since the state was last entered. Also, as far as I can tell, this behavior would be most similar to what the function returns for non-hierarchical state machines (which neither returns the time since first entered or the total accumulated time in the state).

Another comment is that an example of equivalent functionality would be the "elapsed" or "temporalCount" functions in Stateflow (https://www.mathworks.com/help/stateflow/ug/using-temporal-logic-in-state-actions-and-transitions.html), which don't differentiate whether they are being used in a hierarchical state machine or not. The most common way that I would use it would usually be using this is with something like "timeInState() >= 5 and (other condition)".

As a disclaimer: while I often build simple controller and state machine models, I'm not a controls expert. Seems like getting some expert opinions, including from Stateflow users may be prudent. Generally, my cursory opinion is that Stateflow has many niceties that could/should be added, and this is merely a good example.

**Comment by beutlich** [comment]
Please see (again) [ESI_ITI_Feedback_ModelicaStateMachines.docx](https://trac.modelica.org/Modelica/browser/ModelicaDesign/trunk/MeetingMinutesMaterial/min98_2019_Regensburg/ESI_ITI_Feedback_ModelicaStateMachines.docx) (MA login required) for some feedback and comparison with StateFlow.

**Comment by HansOlsson** [comment]
Agreement by acclamation in design group (option 2 above, but needs better description).

Time since sub-state or enclosing state was last entered
So, if enclosing state and sub-state is entered at 1 and enclosing state left at 2, and then re-entered at 3, and we ask for timeInState at 4 it gives 1s, and at 1.5s it gives 0.5s.
