### ISSUE TITLE
Are the restrictions on connect statement arguments too strict?

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2410]
[Section 9.1 of the specification](https://specification.modelica.org/master/Ch9.html#connect-equations-and-connectors) states that the arguments of connect statements can either be in the form `c1.c2...cn` (for outside connectors) or in the form `m.c` (for inside connectors).

Consider this example

```
model TestConnect
  connector C
    Real x;
    flow Real y;
  end C;
  
  model M1
    parameter Real p = 1;
    C c;
  equation
    c.y = p;
  end M1;
  
  model M2
    parameter Integer N;
    M1 m1[N];
  end M2;
  
  model M3
    parameter Integer N = 3;
    M2 m2(N = N);
  equation
    for i in 1:N-1 loop
      connect(m2.m1[i].c, m2.m1[i+1].c);
    end for;
  end M3;
end TestConnect;
```
When checking M3, both Dymola and OpenModelica complain that the connect statement is not in one of the two above-mentioned forms, and declares the model invalid.

I can't see the rationale of this limitation, should we extend the definition to also allow `m1.m2...mp.c`?

See also the discussion in the OpenModelica ticket [#5627](https://trac.openmodelica.org/OpenModelica/ticket/5627), where a concrete case of this issue is presented.

**Comment by HansOlsson** [comment]
There is an obvious way of handling this, consider https://trac.openmodelica.org/OpenModelica/ticket/5627

```
  model Massholder
     Modelica.Mechanics.MultiBody.Parts.Body[3] body(each m=1);
   end Massholder;
   Massholder holder;
equation 
  connect(..., holder.body[j].frame_a);
```

The obvious solution is to expose the frames of the body:
```
  model Massholder
     Modelica.Mechanics.MultiBody.Parts.Body[3] body(each m=1);
     .. frame_a[3];
   equation
       connect(frame_a, body.frame_a);
   end Massholder;
   Massholder holder;
equation 
  connect(..., holder.frame_a[j]);
```
To me there are a few issues with allowing more general connections of this kind:

- There is no obvious graphical representation.
- It breaks "encapsulation".
- The implications for inside/outside connectors becomes messier, and getting that right is important since it determines the signs in flow-equations.

Combined with the fact that there is an obvious solution I don't see the need to add this.

**Comment by casella** [comment]
The idea of exposing the body frame at the higher level sounds good to me. I'd therefore close this issue.
