### ISSUE TITLE
Active when-clauses in algorithms during initialization

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2436]
When resolving #1852, it seems that `when`-statements were forgotten, since section 8.6 _Initialization, initial equation, and initial algorithm_ only speaks of _equations_ (excluding statements) in a `when`-clause.

Should the rules regarding `initial()` be rephrased so that it also applies to `when`-statements in `algorithm` sections?  If not, when should then be said regarding `when`-statements during initialization?

**Comment by HansOlsson** [comment]
Good question.

The reason for focusing on when-equations is that we basically need to extract the "when initial()" equations to construct the initialization problem (since we cannot just evaluate the when-conditions) and such manipulations would be messy for algorithms.

However, it seems that it would be possible to handle for the same cases - without manipulating the algorithms (too much). The alternative would be to make it illegal.

**Comment by henrikt-ma** [comment]
Right, it seems really straight-forward to apply the same _if and only if explicitly enabled with `initial()`_ rule to `when`-statements.  I would prefer this option.

I suppose making it illegal to have `when`-statements active during initialization could make it hard to initialize variables assigned in `when`-statements.  I see no real reason to choose this option.

**Comment by HansOlsson** [comment]
An additional poll. Also running to 2019-12-19

Proposal: 

Extend 8.6 Initialization, initial equation, and initial algorithm to say that both when-statements and when-equations are only active during initialization if and only if explicitly enabled with initial().
(Previously this only applied to when-equations.)

Just use either thumbs up (ok with change) or thumbs down (not ok with change)-reaction:
![Reactions2](https://user-images.githubusercontent.com/13217430/70222518-79ff1380-174a-11ea-81b1-6a2d6241cccb.png)

**Comment by HansOlsson** [comment]
5 votes in favor (Henrik, Hans, Stefan, Gerd, Jesper), 0 against,
