### ISSUE TITLE
Comments on MCP0033 predefined plots

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2440]
When prototyping MCP0033 we discovered a number of subtle issues due to different underlying ideas about plots. 

This is just an attempt at listing them so that we understand the implications:

- The different "plots" as part of a figure are "sub-plots" to that figure, right?
- Is the grouping only used when selecting figures - or does it have some other significance?
- Is it possible to plot variables with different units in the same diagram? The unit seems to be attached to the axis - not to variables.
- It is possible to use different x-axis in the same plot, right?
- It is possible to have auto-scaling of x-axis and given scaling for y-axis (or vice-versa), right?
- The axis-label has a default if not specified (and specifying empty label gives empty label). What about curve legend, and figure title?
- The variants for captions, legends, and axis labels are not clear.

**Comment by HansOlsson** [comment]
And additional point is that it would be good if the example was complete - currently it only has the figures, but not the actual model (it doesn't seem to be a model from MSL).

**Comment by henrikt-ma** [comment]
Sorry for not responding more promptly.  I have been out of office, but will be back on Monday.  

It is great to receive this kind of early detailed feedback, so that we get a chance to sort these things out before sending out proposed specification changes for reviews.

> The different "plots" as part of a figure are "sub-plots" to that figure, right?

Yes.  We chose to call them _plots_ rather than _sub-plots_, since the parent container is called a _figure_, not a _plot_.  It wasn't this way from the beginning, but it really helped getting a clear and concise nomenclature and readable annotations when we changed it to the current state.

> Is the grouping only used when selecting figures - or does it have some other significance?

The grouping is mainly used for presenting the list of figures in a way that makes it easier to navigate when there are many figures.  One can imagine other uses as well, but adding structure to the list of figures is the only things it is used for in SystemModeler at the moment.

> It is possible to use different x-axis in the same plot, right?

I think this question needs clarification.  We allow for parametric plots where each curve has its own variable for the x-coordinate.  However, as we have even avoided plots with multiple y-axes, supporting plots with multiple x-axes seems overly complicated for the current MCP.  Please clarify what it is you would like to be supported.

> It is possible to have auto-scaling of x-axis and given scaling for y-axis (or vice-versa), right?

Yes.  One should even be able to specify just the `min` and let the tool make an automatic choice of `max`.

When I'm back in office, I try to answer the remaining questions with the help from @otronarp.

**Comment by henrikt-ma** [comment]
> And additional point is that it would be good if the example was complete - currently it only has the figures, but not the actual model (it doesn't seem to be a model from MSL).

I see your point, but shouldn't we avoid dependencies on MSL in the specification?  Perhaps we could make an example based on MSL for the evaluation of test implementations, but leave out the examples when making the specification changes?

**Comment by henrikt-ma** [comment]
> The variants for captions, legends, and axis labels are not clear.

I now merged the PR for the text markup.  Did it leave any questions unanswered?

**Comment by otronarp** [comment]
> * Is it possible to plot variables with different units in the same diagram? The unit seems to be attached to the axis - not to variables.

The curves has the units/displayUnits given by the corresponding variable in the model. If the displayUnits are different but compatible it's up to the tool to decide which one to use (perhaps you have a global setting for the prefered display unit).

With that behaviour you need to record the used display unit as soon as you want to have a manually specified axis range (otherwise the range will be wrong if the displayUnit changes in the model).

Also, if you want to force a specific display unit, you do that by setting it on the axis instead of specifying it for each curve.

Nothing prevents you from mixing variables with different (incompatible units), however what you cannot do is specifying a custom display unit for each of them (you have to do that in the model).

**Comment by henrikt-ma** [comment]
> The axis-label has a default if not specified (and specifying empty label gives empty label). What about curve legend, and figure title?

After talking to @otronarp, I have pushed a couple of changes to answer these questions.  Do you find the changes reasonable?

**Comment by HansOlsson** [comment]
> The axis-label has a default if not specified (and specifying empty label gives empty label). What about curve legend, and figure title?
> 
> After talking to @otronarp, I have pushed a couple of changes to answer these questions.  Do you find the changes reasonable?

Yes, seems clearer now.
