### ISSUE TITLE
Should sub-connectors be included in icon for hierarchical connector?

### ISSUE THREAD

**Issue by jespermattsson** [modelica/ModelicaSpecification#2472]
Section 18.6.2 “Component Instance” of the specification states:

> For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model. The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model. Protected connectors are only shown in the diagram layer. Public connectors are shown in both the diagram layer and the icon layer. Non-connector components are only shown in the diagram layer.

This means that for hierarchical connectors (i.e. a connector class that has a component of another connector class), the icon for the parent connector will include the connector for the sub-connector, even when the parent connector’s icon is rendered as a part of another component’s icon. 

Is this the intended behavior? 

While it is possible to hide the sub-component’s icon with “Placement(visible = false)”, it seems likely that the behavior that the user expects is to by default only show the icon defined for the parent icon. Perhaps a reasonable behavior would be to let visible default to false for sub-connectors?

Current tools differ on this, Dymola do not render the sub-connector icons, while OpenModelica and Optimica Compiler Toolkit currently do render them. Modelon’s libraries contain at least one such hierarchical connector, and the author of that connector did indeed intend the connector icon to only include the graphics defined on the parent connector.

Example structure:
```modelica
connector SubConnector
    Real p;
    flow Real f;
    annotation(Icon(graphics = {...}));
end SubConnector;

connector ParentConnector
    SubConnector sc1 annotation(Placement(...));
    SubConnector sc2 annotation(Placement(...));
    annotation(Icon(graphics = {...}));
end ParentConnector;

model A
    ParentConnector pc annotation(Placement(...));
    annotation(Icon(graphics = {...}));
end A;

model Test
    A a annotation(Placement(...));
end Test;
```

**Comment by HansOlsson** [comment]
I agree that this should be clearer.
However, it is not just whether sub-connector is included or not.

Dymola does render sub-connector icons of pc in A but not in Test, and since it is possible to connect to pc.sc1 in A that makes sense.

However, the rendering of ParentConnector in A uses the diagram-layer of ParentConnector, but with the icon-layer for the two SubConnector(s). I believe there is some kind of logic behind this. @DagBruck  ?

**Comment by HansOlsson** [comment]
Seems we need to wait for more input, a complete example with screenshots would help. 
The idea that if you can connect to something it should be visible makes sense.

**Comment by HansOlsson** [comment]
Proposal: 
Public connectors are shown in both the diagram layer and the icon layer, a sub-connector in a hierarchical connector should only be shown when they can be connected to.

**Comment by henrikt-ma** [comment]
It should be made clear how visibility interacts with `Placement.visible`.

**Comment by HansOlsson** [comment]
Proposal 2:
_If a component has `Placement.visible=true` (the default) it can be shown, otherwise it shall not be shown._
For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model.
The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model.
Protected connectors are only shown in the diagram layer.
Public connectors are shown in both the diagram layer and the icon layer_, the sub-connectors in a hierarchical connector should only be shown when they can be connected to_.
Non-connector components are only shown in the diagram layer.
