### ISSUE TITLE
Conditional inner outer

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2499]
Is it allowed to have inner/outer components to be conditionally declared? There is nothing I can find in the Specification that forbids it explicitly. If it is allowed, may the conditions on the inner be different from the one on the outer? What to do if the the inner is missing and there are several outer declarations with the same name, and the same type but different conditions?

**Comment by HansOlsson** [comment]
Interesting question.

I would imagine that a conditional `outer world` could be used if you e.g., sometimes want visualization parameters from world. That should be independent of the condition of `inner world`. But on the other hand I don't see a major need as `outer world` shouldn't be that _expensive_.

To me the messy case is if `inner world` is conditionally disabled (at the top) and there are some enabled (or unconditional) `outer world` (further down). The reason is that it looks as if someone didn't want the world-object, but it is then added automatically (assuming it is unambiguous).

**Comment by HansOlsson** [comment]
I see the following possibilities:

- Forbid both of them.
- State that disabled outer-component are ignored for automatic creation of inner-component (neither causing it; nor influencing the type of it).

After some thinking I believe that the case above with disabled inner component and automatic inner component actually makes sense - and we should not do anything special to forbid it. The scenario is that you have a conditional inner component as a sub-inner, e.g. a local reference frame in an MBS-system. It still seems that the normal automatic inner component should appear in that case.

**Comment by HansOlsson** [comment]
Poll:
1. Forbid:
2. State ...: Elena, Quentin, Hans
Abstain: Filippo, Gerd, Henrik, Martin, Daeoh, Stephan

2.
