### ISSUE TITLE
Implicit iterator range and expandable arrays.

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#2560]
I was wondering if the following model is valid:
```
model AugmentArrayLoop
  expandable connector EC
  end EC;

  connector RealOutput = output Real;

  model M
    RealOutput ro = 1.0;
  end M;

  EC ec;
  M m;

  Real x[Boolean];
equation
  for i loop
    x[i] = 0;
    connect(m.ro, ec.ro[i]);
  end for;
end AugmentArrayLoop;
```

I couldn't find anything forbidding it, so I suppose it is.

**Comment by HansOlsson** [comment]
I agree that there is currently nothing forbidding it, but I believe it should be:

Specifically having an implicit iterator range based on an array in an expandable connector.
The reason is that the members of the expandable connector are also implicitly defined and combining two implicit definitions is not a good idea.

Note that implicit iterator ranges require that all indexed arrays have the same size, i.e. we cannot say that x determines the size and ec.ro just tags along.

The Boolean indexing of ec.ro seems odd, but I don't see any particular reason to forbid it.

**Comment by qlambert-pro** [comment]
> Note that implicit iterator ranges require that all indexed arrays have the same size, i.e. we cannot say that x determines the size and ec.ro just tags along.

This is exactly what I did, and it works.
