### ISSUE TITLE
Replaceable encapsulated classes

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2623]
I cannot find anything in the Specification (3.4) that explicitly prohibits defining replaceable encapsulated classes. Are they allowed? If they are allowed would the redeclared class be encapsulated?

Note that the grammar does not allow to write `...(redeclare encapsulated model B = ...)`

What if the class you redeclare with is encapsulated? Would the result be encapsulated?

**Comment by HansOlsson** [comment]
> I cannot find anything in the Specification (3.4) that explicitly prohibits defining replaceable encapsulated classes. Are they allowed? 

I would say yes - not only is their nothing prohibiting it, but since encapsulated is about lookup going out from the class I don't see a reason again.

> If they are allowed would the redeclared class be encapsulated?

The "encapsulation" property is not inherited, so I don't see why the redeclared class should also be encapsulated (apart from nothing stating it).

> Note that the grammar does not allow to write `...(redeclare encapsulated model B = ...)`

That makes sense since the rhs is looked up in the enclosing class, which would make encapsulated short class definitions difficult to explain (and not particularly useful - the fewer things to look up the less need to limit their lookup).
 
> What if the class you redeclare with is encapsulated? Would the result be encapsulated?

You mean `redeclare model B=B2`, and `B2` is encapsulated? 
No, B isn't encapsulated, but since the actual contents is in B2 (which is encapsulated) that's more of a technicality.

**Comment by eshmoylova** [comment]
> > What if the class you redeclare with is encapsulated? Would the result be encapsulated?
> 
> You mean `redeclare model B=B2`, and `B2` is encapsulated?
> No, B isn't encapsulated, but since the actual contents is in B2 (which is encapsulated) that's more of a technicality.

Yes. I am trying to come up with examples for some corner cases for lookup involving encapsulated classes. So the example is unlikely realistic.
```
package P
  constant Real n = 1;

  partial model A
    Real p;
  end A;

  model M
    replaceable /*encapsulated*/ model B // ???
    end B;
    replaceable A a[n];
    Real x;
    parameter Real p = 1;
  equation 
    a[1].p = x + p;
  end M;
end P;

package P2
  extends P(M(redeclare M.B a, redeclare replaceable model B = B));

  replaceable /*encapsulated*/ model B // ???
    Real p,v;
  equation 
    p = v;
    v = time;
  end B;
end P2;
```

I want the line `redeclare M.B a` to be legal. Since M does not satisfy the requirements of the package, B must be encapsulated to allow `M.B`. The question is which be should I declare as encapsulated? Should it be `P.M.B` or `P2.B`? Or is there no way to make the use of `M.B` legal in such a situation and the tool should just give an error.

**Comment by HansOlsson** [comment]
Ah, I now understand the issue.

Language-lawyer issue:
Technically a redeclare of a model introduces a short-class-definition and that one cannot be encapsulated (according to the grammar); and thus the redeclared `B` cannot be encapsulated.

Language design issue:
The restriction about "encapsulated" is intended to ensure that `B` doesn't depend on its (original) lexical context - and since the redeclare completely replaces the original `B` that is satisfied in this example.

However, what one could do would be to replace the original B with:
`replaceable encapsulated model B=.U.P.BZero(pp=p);`
(with suitable classes), but encapsulation here prevents us from finding `p` in the local scope.
IF that would be legal this `B` when redeclared would depend on `p` from the original lexical context.

Conclusions it seems that we could extend the rule to "replaceable encapsulated" classes have been redeclared (regardless of whether the redeclared classes are encapsulated or not). But I may have missed something, and I don't really see a use-case for this.

**Comment by eshmoylova** [comment]
@HansOlsson I found another case that uses encapsulated and redeclare. This one is from a user model, so not as far fetched as my previous example.
```
package P
    partial function f_base
	input Real x;
	output Real y;
    end f_base;
end P;

package P2
    type MyType = Real(min = -10);

    partial model M
	replaceable function f = P.f_base;
	Real x,y;
    equation
	x = time;
	y = f(x);
    end M;
end P2;

model M2
    extends P2.M(redeclare function f = f2(u=p));
    encapsulated function f2
	import P.f_base;
	extends f_base;

	input P2.MyType u;
    algorithm
	y := x+u;
    end f2;
    parameter P2.MyType p = 10;
    //P2.MyType z;
equation
    //z = f2(x,p);
end M2;
```
There is an error in the type specification of u in `M2.f2`. `P2` needs to be imported for the definition to be valid. If you uncomment the commented out definition and equation for `z` and call `f2` directly, it should be an error for sure, right?
But with those lines commented out should the model give an error? Specifically, would `M2.f` be considered encapsulated? I cannot find anything in the specification about this case.

My first reaction is to say that, of course, `M2.f` is encapsulated because `M2.f2` is. But I see your point about the modifications.

**Comment by eshmoylova** [comment]
The answer to the original question seems to be: if a class is redeclared whether it was encapsulated or the class it is redeclared with was encapsulated the result will not be encapsulated. I created a separate issue for the additional questions that came up in the discussion - #2743.
