### ISSUE TITLE
Initialization of clocked partitions

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2624]
### Problem:

Currently we have the unsatisfactory situation that clocked partitions don't support normal initialization in particular not initial equations, and at the same time we have https://specification.modelica.org/master/synchronous-language-elements.html#continuous-time-equations-in-clocked-partitions
stating: "The goal is that every continuous-time Modelica model can be utilized in a sampled data control system."

I believe we should later turn this into an MCP. (This has preliminarily been discussed in a project.)

### Solutions:
I see two basic possibilities for how to initialize clocked partitions:

- Initially (as all other initial equations)
- At "firstTick", note that I use quotes, as it may be active in a few other cases than firstTick

Which one is best is less clear, but we can then look at a number of questions for those two options:
- Why are we using initial equations and not start-values? One common reason is that we want to start in quasi-steady state in complicated way – and if the system has inputs I see the possibilities:
   - Initialize in quasi-steady-state for “zero input”. This could be done either initially or at “firstTick”; and should ideally give the same result – but I’m unsure how to formulate this restriction.
   - Initialize in quasi-steady-state for actual known inputs. This can only be done at “firstTick”.
   - Initialize in quasi-steady-state together with the inputs. This can only be done initially – and mixes the clocks in initial equations.
- Reset in state-machines. Currently a reset should reset states to start-values – and for “firstTick” this naturally leads to solving initial equations again.
- Using hold(x) or similarly before “firstTick(x)”. If we solve everything initially that gives x the value from the initial equations. If we solve at “firstTick” this is unclear and it seems the best solution is to use start-value of x with a diagnostic.
- How to combine initialization with the other equations? For "firstTick" it seems to follow naturally, but initially it seems messier. Note that the clock does not necessarily tick at the initially (i.e. at starting point) and we have no explicit way of saying "do tick at starting point" (as discrete when-clauses have with when {initial(), ...).

To me this suggest that we should investigate this “firstTick” option, as it naturally decomposes the initialization along the clocks as we want, and for clocked discretized continuous equations it would give for Euler:

_Note: The part in capital letter is a set of equations, and thus overall this is not straightforward code.
In an implementation solving that and clearly separating out “previous(first)” is a good idea._ 

```
when Clock() then
if “firstTick(x)” then
    // first clock tick (initialize system)
   if x.fixed=true then 
       x=x.start
     else
       INITIAL EQUATIONS FOR x;
    end if;
else
    // second and further clock tick
    x = previous(x) + interval()*previous(der_x);
end if;
der_x = -x + u;
end when;
```

and for a normal clocked variable we replace:

```
when clk1 then
  x = previous(x) + hold(u);
end when;
```
with:

```
when clk1 then
  if “firstTick(x)” then
     if x.fixed=true then 
       previous_x=x.start
     else
       INITIAL EQUATIONS for x;
     end if;
   else
     previous_x = previous(x);
   end if;
   x = previous_x + hold(u);
end when;
```

As I see it:
- It allows separable initial equation for clocked equations.
- Clocked discretized continuous-time systems should behave similarly to the non-clocked counterparts.
- It is explainable and covers all cases.
- It is backwards compatible.

**Comment by HansOlsson** [comment]
Henrik: prefer two test-implementations for this.
Hans: a start would be _one_, and detailed explanation with more background.
Please indicate interest in the ticket.

**Comment by christoff-buerger** [comment]
I like to add some background for this ticket from a clocked user-perspective -- to be precise why something has to be done from the EMPHYSIS project/`Modelica.Clocked` for controller development perspective.

There are two main objectives __from that perspective__:
1. Continuous models should be reusable for clocked applications. Wrapping a component into a sampling can of course change the simulation (for example if the sampling period is too large). But currently initialization is completely different for clocked systems compared to continuous; in fact many initialization-means are simply not supported in clocked partitions, meaning that MSL components break because their initialization changes significantly if packed into a clocked partition.
2. Initialization of a controller is something different from sampling (a `DoStep` function call). It has to be possible to properly specify the controller's start-state (initialization modelling), separated from its sampling behavior. Separated here means, also implementation-wise clearly separate (because initialization is often specifically handled in separate routines in embedded system integration).

Point (2) is important. It implies that we can split the control logic from the initialization logic. One can think of this as a kind of `initialize` function, that given some control inputs -- or a flag that default input values should be used -- sets all control states including outputs. In terms of Modelica clocked this means, that `initialize` also sets the initial values of holds -- and that is what we cannot do right now.

From an embedded system integration perspective, `initialize` is used to initialize the controller -- if desired even depending on some runtime inputs -- before any sampling step in terms of `DoStep` is done; the surrounding system is the embedded environment and runtime system which makes sure to call `initialize` before any `DoStep` call.

From the Modelica perspective, the surrounding system is the continuous time partition. Sticking to the clearly separated `initialize` and `DoStep` functions idea, this means the following:
1. The continuous time partition initialization may have to iterate as usual until some fixpoint is found for the __whole__ initialization problem.
2. Throughout Point (1), every time the continuous time partition iterates and needs new hold values to that end, it calls the respective clocked partitions `initialize` function.
3. As soon as Point (1) reached a fixpoint, normal simulation starts throughout which `DoStep` of clocked partitions are called whenever they are sampled.

Consider Hans original proposal above again. It is written from the Modelica semantic perspective. `firstTick` protects all the `initialize` function logic; the else branches (`not(firstTick)`)  the `DoStep`. For the embedded controller modelling domain we need such clear separation.
