### ISSUE TITLE
Restrictions on statements within when-statements

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2635]
For when-equations, there is the section 8.3.5.2 _Restrictions on Equations within When-Equations_ on the restrictions on equations inside the when-clauses.  I find it surprising that there is no corresponding section for when-statements.  If nothing else, I think there should be a clarification that there are not special restrictions corresponding to the ones for when-equations, or references to the other places where such restrictions are given (for instance, I can see that another when-statement isn't allowed).

**Comment by HansOlsson** [comment]
There is a similar restriction, for when-statements: 11.2.7.1 Restrictions on When-Statements
https://specification.modelica.org/master/statements-and-algorithm-sections.html#restrictions-on-when-statements

The heading is different from 8.3.5.2 Restrictions on Equations within When-Equations https://specification.modelica.org/master/equations.html#restrictions-on-equations-within-when-equations _but the contents is similar_. The restriction on the forms of statements is not needed, since statements are already restricted to that form.

There might be some remaining differences (in both directions) that  could be clarified. Making the headings more similar might also be good.

**Comment by HansOlsson** [comment]
To compare the restrictions for when-statements (S) and when-equations (E):

- A when-statement shall not be used within a function. (S): Not relevant for equations as they cannot occur in equations.
- When-statements/When-equations may not occur inside initial algorithms/initial equations. (SE)
- When-statements/When-equations cannot be nested. (SE)
- When-statements may not occur inside while, if, and for-clauses in algorithms. (S) Something similar is not needed for equations, the reason is that if and for-clauses in equations can be expanded - introducing multiple when-equations.
- The equations within the when-equations must be... (E) Similar to restrictions for statements in general.

**Comment by henrikt-ma** [comment]
> The heading is different from 8.3.5.2 Restrictions on Equations within When-Equations https://specification.modelica.org/master/equations.html#restrictions-on-equations-within-when-equations _but the contents is similar_. The restriction on the forms of statements is not needed, since statements are already restricted to that form.

Aren't we at least missing this:
> Any left hand side reference, (v, out1, …), in a when-clause must be a component reference, and any indices must be parameter expressions.

> There might be some remaining differences (in both directions) that could be clarified. Making the headings more similar might also be good.

Yes, I'd propose using the headings _Restrictions on when-equations_ and _Restrictions on when-statements_, and under each present two the item lists _Restrictions on where a when-equation(statement) may occur_ and _Restrictions on the equations(statements) within a when-equation(statement)_.  If any of these lists would en up being completely empty, I'd suggest to just have a sentence saying that there are no such restrictions.

**Comment by HansOlsson** [comment]
> > The heading is different from 8.3.5.2 Restrictions on Equations within When-Equations https://specification.modelica.org/master/equations.html#restrictions-on-equations-within-when-equations _but the contents is similar_. The restriction on the forms of statements is not needed, since statements are already restricted to that form.
> 
> Aren't we at least missing this:
> 
> > Any left hand side reference, (v, out1, …), in a when-clause must be a component reference, and any indices must be parameter expressions.

The first part is true in algorithms in general and thus not needed; you cannot write `algorithm 2*x=2;` nor `algorithm when ... then 2*x:=2;...`.
The second part with restriction of indices to parameter expressions isn't needed as the entire array is assigned by the algorithm - and thus the entire array can be set to pre at the start of algorithm, allowing a model like this:

```
model Unnamed
  Real x[5](each start=0,each fixed=true);
algorithm 
  when sample(1,1) then
    x[integer(rem(time,5)+1)]:=time;
  end when;
end Unnamed;
```
(I believe that some use that - hopefully in saner ways.)
> 
> > There might be some remaining differences (in both directions) that could be clarified. Making the headings more similar might also be good.

> Yes, I'd propose using the headings _Restrictions on when-equations_ and _Restrictions on when-statements_, and under each present two the item lists _Restrictions on where a when-equation(statement) may occur_ and _Restrictions on the equations(statements) within a when-equation(statement)_. If any of these lists would en up being completely empty, I'd suggest to just have a sentence saying that there are no such restrictions.

That makes sense.
