### ISSUE TITLE
Unknown variable 'Z' in figure D.3

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2643]
In figure D.3 _Example series connection of multiple models with stream connectors._, the sensor has a label `Z_{3}(min = 0)`, but there is no use of _Z_ in the surrounding text.  Should it be `\dot{m}_{3}`?

**Comment by HansOlsson** [comment]
It should be `\text{m_flow}_3` or `m3.c.m_flow` or some variation of this see slide 12 and 27 (bottom) on 
https://www.modelica.org/education/educational-material/lecture-material/english/ModelicaStream-Overview-Rationale.ppt/view

I understand that they are kind of long, so another solution would be to introduce `Z` in the text and keep the figure.

If it is intuitively related to `dot{m}_{3}`, but we should separate the two since the ideal sensor doesn't contain any `m` (=mass), and if there are multiple ports for a component `dot{m}` is given by their sum and here we only want the mass-flow through this port.

**Comment by henrikt-ma** [comment]
OK, how about putting `m3.c.m_flow(min = 0)` just above the blue box representing the sensor?

**Comment by henrikt-ma** [comment]
> > OK, how about putting `m3.c.m_flow(min = 0)` just above the blue box representing the sensor?
> 
> Makes sense (after I realized that you meant the "light blue" box)

Will be fixed as part of #2609.

> I realized that there is a major issue in the appendix D: it is using `\dot{m}` instead of `m_flow` throughout - without the considerations I gave, whereas chapter 15 uses `m_flow`. Apart from the problem I stated it's also confusing to have different notations with no explanation.
> 
> On the other hand `\dot{m}` is more common mathematical notation, it's just misleading. I believe we can resolve it by introducing `\tilde{m}` (or something like that) for `m_flow` - and have a short explanation for the relation between `\tilde{m}`and `\dot{m}`.

Right, that's a bigger issue.  Reported separately as #2644.

**Comment by HansOlsson** [comment]
I finally found the explanation. 

Rüdiger Franke did a presentation "Excerpt of Motivation for Modelica stream connectors" as part of "Eurosyslib WP 5.3 Meeting Mannheim, June 9, 2008" (stored in Modelica33 on old svn-server), and used Z instead of m_flow, and included that figure as well.
