### ISSUE TITLE
Strange bar on priority "5" in figure in section 17.2 "State Machine Graphics"

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2649]
Regarding how to display the `priority` of a `transition`, I only find this:
> The value of the \lstinline!priority! attribute is prefixing the condition text followed by a colon if `priority` > 1.

Where does the bar on the `priority` "5" in the figure come from?

**Comment by HansOlsson** [comment]
I neither see any obvious explanation for the bar, nor for the fact that "5: e" is shown to right with a line going towards the transition line - and think that the condition should be shown as the other ones.

As far as I can see Paper "State Machines in Modelica" by Elmqvist, Gaucher, Mattsson and Dupont had a similar picture without the bar, but with the extra line; http://2012.international.conference.modelica.org/proceedings/html/pdf/ecp1207637_ElmqvistGaucherMattsson.pdf My guess is that is the origin, and the bar is due to some artefact.

**Comment by henrikt-ma** [comment]
> I neither see any obvious explanation for the bar, nor for the fact that "5: e" is shown to right with a line going towards the transition line - and think that the condition should be shown as the other ones.

The line to the transition condition mark is documented:
> If the condition text is somewhat distant from the perpendicular line, a dimmed straight line joins the transition text and the perpendicular line.  (See the rightmost transition above.)

> As far as I can see Paper "State Machines in Modelica" by Elmqvist, Gaucher, Mattsson and Dupont had a similar picture without the bar, but with the extra line; http://2012.international.conference.modelica.org/proceedings/html/pdf/ecp1207637_ElmqvistGaucherMattsson.pdf My guess is that is the origin, and the bar is due to some artefact.

OK, I'll get rid of the bar then.

**Comment by HansOlsson** [comment]
> The line to the transition condition mark is documented:
> 
> > If the condition text is somewhat distant from the perpendicular line, a dimmed straight line joins the transition text and the perpendicular line.  (See the rightmost transition above.)

Ah, I see and the text has a position relative to the connection line so the user can control this.
Dymola really draws a dimmed line in that case, but I couldn't see how to position the text graphically.
