### ISSUE TITLE
Section 16.4 "Discrete States" doesn't mention "discrete state"

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2651]
Instead of introducing the term _discrete state_ in section 16.4 _Discrete States_, the term _clocked state variable_ is introduced.

As far as I can tell, _discrete state_ is only used once in the specification, in section _Execution of an algorithm in a model_.  I suppose this should be changed to refer to _clocked state variable_ instead, and that section 16.4 should be renamed.

When we're at it, perhaps section 16.4 should also be rewritten to make it crystal clear whether the clocked state variables are exactly those to which `previous` _has_ been applied, or the ones to which it _could_ be applied?

**Comment by HansOlsson** [comment]
> Instead of introducing the term _discrete state_ in section 16.4 _Discrete States_, the term _clocked state variable_ is introduced.
> 
> As far as I can tell, _discrete state_ is only used once in the specification, in section _Execution of an algorithm in a model_. I suppose this should be changed to refer to _clocked state variable_ instead, and that section 16.4 should be renamed.

Unfortunately it's worse: "discrete state" is only used once, and **it's used incorrectly at that place**.

The "discrete state" in _Execution of an algorithm in a model_ refers to any discrete variable, like any Boolean, Integer (and Real assigned in a when-clause). It's not obvious, but follows since that section had the same text already in Modelica 3.2, before we got clocked state variables.

But that makes the solution simpler, just rename the section!

> When we're at it, perhaps section 16.4 should also be rewritten to make it crystal clear whether the clocked state variables are exactly those to which `previous` _has_ been applied, or the ones to which it _could_ be applied?

Only the ones where previous has been applied, as one of the advantages of the clocked semantics is that there are fewer states.

**Comment by henrikt-ma** [comment]
OK.  I'll prepare a fix.
