### ISSUE TITLE
Poor adoption of byte order mark

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2675]
When beginning to work on a test implementation of [MCP-0015](https://github.com/modelica/ModelicaSpecification/tree/MCP/0015/RationaleMCP/0015) _Language version header_, I got aware that the support for the BOM in SystemModeler is fragile, and would deserve a more serious implementation in same spirit as the handling of the language version header.

However, when not even the MSL has adopted the possibility to use a BOM, I'd like to take the opportunity to challenge the support for BOM in the specification.  Wouldn't it be better to deprecate its use, considering:
- Rudimentary support is easy, whereas proper support takes more work (new files should follow same convention as other files in the same library, removing all contents of a package, and then putting something else back should not alter the use of BOM, etc).
- Given that all Modelica source files use UTF-8, there is no need to indicate this using the BOM.  Compare [IETF recommendation regarding protocols that always use UTF-8](https://tools.ietf.org/html/rfc3629#section-6) (found on [Wikipedia](https://en.wikipedia.org/wiki/Byte_order_mark#:~:text=The%20IETF%20recommends%20that%20if,that%20is%20not%20Unicode%2Daware.)):
  > A protocol SHOULD forbid use of U+FEFF as a signature for those textual protocol elements that the protocol mandates to be always UTF-8, the signature function being totally useless in those cases.
- The BOM is a known source of problems due to its invisible appearance at the start of the first line of text.  For example, I had problems even editing a file with BOM in Emacs.
- It's not even used by the MSL.

Which tools have actually made the effort to add proper BOM support?

**Comment by HansOlsson** [comment]
Unicode support (with BOM) was added in Modelica 3.2; released in 2010 - and one of the guiding principles is stability meaning that files should be stable for 10 year (or more). And if we look back we do find files in iso-8859-1 instead of Unicode from the last decade.

Thus if we want to phase out BOM it should be done slowly.

If we read through the IETF recommendation (SHOULD or RECOMMENDED means that it is recommended in general, but that the recommendation may be ignored if there are good reasons etc) we see that the reason for the recommendation is that there could be an ambiguity whether the leading BOM is a BOM or a white-space part of the file. For some files that would be an important difference. However, since white-space at the start of a Modelica file is semantically ok and doesn't matter semantically that's not a problem for Modelica.

One of the specific issues with BOM is concatenating files (or strings in general); and there are several other reasons why blindly concatenating Modelica files is a bad idea (e.g., the leading within-statement).

I'm a bit uncertain if Unicode whitespace characters (such as BOM) are currently allowed as white-space in Modelica files (it would make sense when we support Unicode). Assuming they are allowed this means that if we deprecate BOM a Modelica file starting with BOM will still be valid and semantically equivalent afterwards, it's just that the BOM will be an invisible white-space character before within instead of a special invisible character before the file contents.

So, even if were to remove it there would be no change in practice.

**Comment by sjoelund** [comment]
> I'm a bit uncertain if Unicode whitespace characters (such as BOM) are currently allowed as white-space in Modelica files

Only at the start of a file as far as I can tell. And I'm not sure it's good to start allowing it: http://unicode.org/faq/utf_bom.html#bom6:

>  When designing a markup language or data protocol, the use of U+FEFF can be restricted to that of Byte Order Mark. In that case, any U+FEFF occurring in the middle of a file can be treated as an unsupported character.

**Comment by HansOlsson** [comment]
> > I'm a bit uncertain if Unicode whitespace characters (such as BOM) are currently allowed as white-space in Modelica files
> 
> Only at the start of a file as far as I can tell. And I'm not sure it's good to start allowing it: http://unicode.org/faq/utf_bom.html#bom6:
> 
> > When designing a markup language or data protocol, the use of U+FEFF can be restricted to that of Byte Order Mark. In that case, any U+FEFF occurring in the middle of a file can be treated as an unsupported character.

That is for BOM, but my question was more generally about other non-ASCII whitespace characters. So, spaces in the range 0x2000-0x200D, 0x205F, 0x2060 (Word joiner as replacement for byte-order-mark), etc.

One could argue that no-one needs them in Modelica as whitespace (they can still occur in strings), and thus there is no ambiguity.

**Comment by sjoelund** [comment]
> That is for BOM, but my question was more generally about other non-ASCII whitespace characters. So, spaces in the range 0x2000-0x200D, 0x205F, 0x2060 (Word joiner as replacement for byte-order-mark), etc.

Section 2.2:
> The whitespace characters are space, tabulator, and line separators (carriage return and line feed)

**Comment by henrikt-ma** [comment]
> > That is for BOM, but my question was more generally about other non-ASCII whitespace characters. So, spaces in the range 0x2000-0x200D, 0x205F, 0x2060 (Word joiner as replacement for byte-order-mark), etc.
> 
> Section 2.2:
> 
> > The whitespace characters are space, tabulator, and line separators (carriage return and line feed)

Working with the things you can't easily see in a text editor is generally difficult, so I think adding more characters to the list of grammar/lexer whitespace characters is only going to hurt users.  (Inside strings, this is different, as the various invisible characters may actually serve different purposes there.)

**Comment by henrikt-ma** [comment]
> So, even if were to remove it there would be no change in practice.

The important change in practice would still be that the character would be just considered whitespace instead of BOM, meaning that tools wouldn't be supposed to have complete support for BOM.  Repeating myself, these are some of the things I would expect of a tool that actually supports BOM:
- A toggle for controlling the use of BOM on per-file basis.
- Intelligent use of BOM for new files based on existing files in the same package.
- Command for converting all files of a package to/from use of BOM.
- The BOM should not be included in any Modelica text views.
- No change to use of BOM even if all classes stored in a file are removed and replaced by new definitions.

If we were to deprecate the use of BOM, on the other hand, I think we should explain non-normatively that it's not a big deal; something like this:
> A byte order mark (BOM, U+FEFF) was allowed in some earlier versions of Modelica.  If such files are encountered, the BOM at the beginning of a file can be handled like any whitespace character in the grammar.  A tool can also easily help users get rid of the deprecated BOM by giving the option of dropping the BOM altogether instead of treating it as whitespace.

**Comment by HansOlsson** [comment]
Couldn't we keep BOM in the current form and add: 
Tools can ignore the optional BOM when reading, and do not have to write it.

**Comment by henrikt-ma** [comment]
> Couldn't we keep BOM in the current form and add:
> Tools can ignore the optional BOM when reading, and do not have to write it.

To me, that's just another way of saying that it doesn't really need to be supported.  To standardize that the BOM can get lost when using a Modelica tool sounds like bad specification to me.  As I see it, the deprecation variant would give the same result, but without a bad specification.

**Comment by HansOlsson** [comment]
> > Couldn't we keep BOM in the current form and add:
> > Tools can ignore the optional BOM when reading, and do not have to write it.
> 
> To me, that's just another way of saying that it doesn't really need to be supported. To standardize that the BOM can get lost when using a Modelica tool sounds like bad specification to me. As I see it, the deprecation variant would give the same result, but without a bad specification.

I don't understand this.

If we _remove_ the support for BOM all files with BOM will cease to be valid Modelica, and saying that they "can" be handled doesn't change that.

Deprecated means that it is still part of the standard (in preparation for removing it later), but we discourage its use. (That's both the normal usage and how we currently use it in the specification.)

Thus to _deprecate_ this feature I propose to change from:
"and may start with the UTF-8 encoded byte order mark (0xef 0xbb 0xbf); this is treated as white-space in the grammar. "
to:
"and a deprecated feature is that the file may start with the UTF-8 encoded byte order mark (0xef 0xbb 0xbf); this is treated as white-space in the grammar. Since this feature is deprecated tools can ignore the optional BOM when reading, and it is  recommended to never write it."

**Comment by henrikt-ma** [comment]
> > > Couldn't we keep BOM in the current form and add:
> > > Tools can ignore the optional BOM when reading, and do not have to write it.
> > 
> > 
> > To me, that's just another way of saying that it doesn't really need to be supported. To standardize that the BOM can get lost when using a Modelica tool sounds like bad specification to me. As I see it, the deprecation variant would give the same result, but without a bad specification.
> 
> I don't understand this.
> 
> If we _remove_ the support for BOM all files with BOM will cease to be valid Modelica, and saying that they "can" be handled doesn't change that.
> 
> Deprecated means that it is still part of the standard (in preparation for removing it later), but we discourage its use. (That's both the normal usage and how we currently use it in the specification.)

Yes, I agree, the non-normative text I suggested was not something to go with a deprecated feature, it was something we could add in the future when the feature has actually been removed.  I'm sorry about the confusion.

> Thus to _deprecate_ this feature I propose to change from:
> "and may start with the UTF-8 encoded byte order mark (0xef 0xbb 0xbf); this is treated as white-space in the grammar. "
> to:
> "and a deprecated feature is that the file may start with the UTF-8 encoded byte order mark (0xef 0xbb 0xbf); this is treated as white-space in the grammar. Since this feature is deprecated tools can ignore the optional BOM when reading, and it is recommended to never write it."

Sounds like a good way to put it.

**Comment by HansOlsson** [comment]
Poll:
* No change. BOM is still supported. Stephan Ziegler, Filippo Donida
* Change to "and a deprecated feature is that the file may start with the UTF-8 encoded byte order mark (0xef 0xbb 0xbf); this is treated as white-space in the grammar. Since this feature is deprecated tools can ignore the optional BOM when reading, and it is recommended to never write it." Henrik Tidefelt, Axel Mårtensson, Gerd Kurzbach, Christoff, Markus, Martin Sjölund, Quentin Lambert
2nd option.
Leo Gall, Hans Olsson abstain
