### ISSUE TITLE
Is it an error for functions to return records containing uninitialised fields?

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#2745]
Section 12.4.4 states that
> It is an error to use (or return) an uninitialized variable in a function.

In `Modelica.Media.Water.IF97_Utilities.dewcurve_p` either `bpro.cv` or `bpro.cp` is returned and uninitialised.
Here is the declaration of the function:
```
function dewcurve_p "Properties on the dew curve"
  extends Modelica.Icons.Function;
  input SI.Pressure p "Pressure";
  output Common.IF97PhaseBoundaryProperties bpro "Property record";
protected
  Common.GibbsDerivs g "Dimensionless Gibbs function and derivatives";
  Common.HelmholtzDerivs f "Dimensionless Helmholtz function and derivatives";
  SI.Pressure plim = min(p, data.PCRIT - 1e-7) "Pressure limited to critical pressure - epsilon";
algorithm
  bpro.R := data.RH2O;
  bpro.T := Basic.tsat(plim);
  bpro.dpT := Basic.dptofT(bpro.T);
  bpro.region3boundary := bpro.T > data.TLIMIT1;
  if not bpro.region3boundary then
    g := Basic.g2(p, bpro.T);
    bpro.d := p / (bpro.R * bpro.T * g.pi * g.gpi);
    bpro.h := if p > plim then data.HCRIT else bpro.R * bpro.T * g.tau * g.gtau;
    bpro.s := g.R * (g.tau * g.gtau - g.g);
    bpro.cp := -bpro.R * g.tau * g.tau * g.gtautau;
    bpro.vt := bpro.R / p * (g.pi * g.gpi - g.tau * g.pi * g.gtaupi);
    bpro.vp := bpro.R * bpro.T / (p * p) * g.pi * g.pi * g.gpipi;
    bpro.pt := -p / bpro.T * (g.gpi - g.tau * g.gtaupi) / (g.gpipi * g.pi);
    bpro.pd := -bpro.R * bpro.T * g.gpi * g.gpi / g.gpipi;
  else
    bpro.d := rhov_p_R4b(plim);
    f := Basic.f3(bpro.d, bpro.T);
    bpro.h := hv_p_R4b(plim);
    // bpro.R*bpro.T*(f.tau*f.ftau + f.delta*f.fdelta);
    bpro.s := f.R * (f.tau * f.ftau - f.f);
    bpro.cv := bpro.R * (-f.tau * f.tau * f.ftautau);
    bpro.pt := bpro.R * bpro.d * f.delta * (f.fdelta - f.tau * f.fdeltatau);
    bpro.pd := bpro.R * bpro.T * f.delta * (2.0 * f.fdelta + f.delta * f.fdeltadelta);
  end if;
end dewcurve_p;
```

**Comment by qlambert-pro** [comment]
A similar question exists for uninitialised array `C`  in the case of `Modelica.Mechanics.MultiBody.Visualizers.Advanced.SurfaceCharacteristics.torus`

**Comment by HansOlsson** [comment]
> A similar question exists for uninitialised array `C` in the case of `Modelica.Mechanics.MultiBody.Visualizers.Advanced.SurfaceCharacteristics.torus`

That's a bit special since 'c' is in that case an empty matrix, so there are no unitialized array elements.
But it would be trivial to initialize it.

> Section 12.4.4 states that
> 
> > It is an error to use (or return) an uninitialized variable in a function.
> 
> In `Modelica.Media.Water.IF97_Utilities.dewcurve_p` either `bpro.cv` or `bpro.cp` is returned and uninitialised.

You mean `Modelica.Media.Water.IF97_Utilities.BaseIF97.Regions.dewcurve_p`, and looking more closely it's used in e.g. `Modelica.Media.Water.IF97_Utilities.BaseIF97.Regions.dhv_dp` calling `Modelica.Media.Water.IF97_Utilities.BaseIF97.Regions.hvl_dp`, and in the latter we see that the initalized one of cp or cv is used depending on region3boundary.

Thus it is one sense an attempt at a https://en.wikipedia.org/wiki/Tagged_union (variant record in Pascal, Ada).
I don't see a good simple way of fixing this in the library. Obviously one could replace the two variables with one "cv_or_cp" which is either cv or cp depending on region, but it seems messy (and it might trigger unit-warnings).

Note that the problematic statement was added in Modelica 3.4.

One proposal would be to remove "or return", as the point is using the unitialized variable; and it was just assumed that the returned record was fully used.

**Comment by HansOlsson** [comment]
Agreement not to change specification and instead change MSL.

**Comment by beutlich** [comment]
Should we transfer the issue to the MSL repo?

**Comment by HansOlsson** [comment]
> Should we transfer the issue to the MSL repo?

Or create a duplicate issue/pr.

**Comment by HansOlsson** [comment]
> > Should we transfer the issue to the MSL repo?
> 
> Or create a duplicate issue/pr.

I did that now.
