### ISSUE TITLE
What is the semantic of an equation in declaration section

### ISSUE THREAD

**Issue by AtiyahElsheikh** [modelica/ModelicaSpecification#2780]
The specification document (V3.4 & V3.5-dev), to my knowledge and maybe I am wrong, does not seem to explicitly specify what is the precise behavior of an equation in a declaration section. 

For example

```
model  M
   Real X(start = 1)`; 
   Real Y = X; 
   ... 
equation 
  ... 
  der(X) = 1;
  ... 
end M;
```

What is the precise behavior of equation `Y = X`?  Does it behave as

- an equation in an "initial equation" section? and in this case an additional equation involving Y should be placed in equation section? 
- a constant equation` Y = X.start`?
- a time-varying equation `Y = X`? 

My relative understanding is that it should be the second case as I am influenced by earlier Modelica libraries in Power Systems where power-flow calculations (using nonlinear equations) were placed in the declaration section and their solutions were used as initial values for transient simulations. I guess at that early time (< 2002), "initial equation" was not yet established in the specification and therefore such equations were placed in the declaration section.  

Another clearer example: What should be the behavior of the variable X in the following model: 

```
model V
    Real X = time;
    ...
end V;

```
A constant equation` X=0 `or a linear equation `X=time`?

**Comment by henrikt-ma** [comment]
What you are describing is syntactically a _binding equation_, which is a case of a _declaration equation_: https://specification.modelica.org/master/class-predefined-types-and-declarations.html#declaration-equations

The sort of equality expressed by a declaration equation is similar to a normal equation, but a declaration equation comes with additional constraints and possibilities.  They play a special role for constants and "fixed parameters", as these cannot be determined by normal equations.

The kind of `X = Y` you get is a relation that holds over time (a "time-varying equation"), so your second `X` will always be equal to `time`.

**Comment by AtiyahElsheikh** [comment]
To my understanding, the specification describes declaration equations as binding equations in the context of constants and parameters (Sec 4.4.3). Declaration equations for setting discrete time-varying and continuous time-varying variables is not explicitly mentioned (a bit implicit in Sec. 4.4.2.1). 

I still have the impression that the specification can be made clearer and preciser regarding time-varying equations as declaration equations.   

I can imagine few cases for usefulness of time-varying equations as declaration equations, but it also opens the door for misusing the concept to produce badly-designed funny-looking models.

**Comment by henrikt-ma** [comment]
Declaration equations are listed as one of the equation categories in Modelica, and it is clear that these equations are not restricted to only parameters and constants:
https://specification.modelica.org/master/equations.html#equation-categories

I won't try to list all the benefits of having them in the language, but let me just give one example: The clarity it brings to the equation structure of a model when an equation is syntactically attached to a particular variable, with the variable appearing in "solved position".

Keep in mind that a declaration equation should be made final (by means of applying `final` to the component declaration or modification) if it is not supposed to be modified.

**Comment by HansOlsson** [comment]
Yes, a declaration equation is an equation that is just as any other equation (unless it is replaced by another declaration equation using a modifier).

Note that a non-connector input to a block/model relies on this; as the input-prefix indicates that a declaration equation will be provided (regardless of whether it is provided in the declaration).

Without having seen the problematic models in Power Systems I would assume they are doing parameter-computations before the initial equations; but for some reason (possibly limitations of parameter-bindings) those variables are not declared as parameters.

It may be that the text could be a bit clearer; but to me the question boils down to "it doesn't say these equations behave like other equations so we don't know how they behave". And to me the answer is that the standard is (fairly) complete and that exceptions to rules are indicated (or ideally listed); and thus it all equations should behave the same -- unless there is an exception (as for initial equations). In other cases when there are contradictions between different parts of the standard we have to resolve that, but I don't see any here.

Going through all the rules to make them airtight will be a major undertaking, and we shouldn't do it one rule at a time since that would make the untightened rules appear less clear ("other rules state that there are no exceptions, but this one doesn't - does it mean there are exceptions?").

**Comment by HansOlsson** [comment]
I would thus like to close this question.

**Comment by AtiyahElsheikh** [comment]
Ok I see it.
