### ISSUE TITLE
MLS 3.5 RC1: Coloured hyperlinks

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2798]
Whereas [ModelicaSpec34.pdf](https://modelica.org/documents/ModelicaSpec34.pdf) / [ModelicaSpec34.html](https://specification.modelica.org/maint/3.4/MLS.html) display hyperlinks in blue, they are black or grey in [ModelicaSpec35.pdf](https://specification.modelica.org/maint/3.5/MLS.pdf) / [ModelicaSpec35.html](https://specification.modelica.org/maint/3.5/MLS.html). Is this intentional or just a side-effect?

**Comment by henrikt-ma** [comment]
The intention is that they should blend with the text.  Do the grey ones stick out?

**Comment by beutlich** [comment]
The grey ones do, but the black ones do not:

![grafik](https://user-images.githubusercontent.com/14896695/103707742-812ccc80-4faf-11eb-8ee7-d0e12d7b5eab.png)

It is recognizable that section number and ticket number are links here.

**Comment by henrikt-ma** [comment]
It is good that they are not recognizable, so that visual distraction can be used for other purposes, but where are the gray ones that stick out?  Everything I see here is 20% gray.

**Comment by beutlich** [comment]
By grey links I mean external hyperlinks in text. Not yure if they are grey or if it is just due to the monospaced font.

![grafik](https://user-images.githubusercontent.com/14896695/103746498-7bf86d80-5001-11eb-87ed-e79eb93362e4.png)

**Comment by henrikt-ma** [comment]
OK, I think I can see what you mean.  The link has the same color as the surrounding text (20% gray in HTML, pitch black in PDF).  In the PDF, the link actually appears darker due to the monospaced font being heavier than normal text.  In HTML, the link appears lighter due to a reverse relation between fonts.

Is this investigation enough to close, or do you suggest that we try to find alternative fonts?

**Comment by beutlich** [comment]
Well, I prefer the explicit colour difference of MLS 3.4. The 20% grey are not recognizable at all to me, it just makes no difference.

However, feel free to close this issue, if it just is a matter of personal taste.

**Comment by henrikt-ma** [comment]
> Well, I prefer the explicit colour difference of MLS 3.4. The 20% grey are not recognizable at all to me, it just makes no difference.

Note that the 20% gray is the color used for all text, it has nothing to do with links or monospaced fonts.  The change from pure black to 20% gray was one of the very first style changes made by @MartinOtter after the introduction of LaTeXML.

> However, feel free to close this issue, if it just is a matter of personal taste.

Yes, but let's keep eyes and ears open in case lack of link color turns out to be a common complaint once the new version gets more readers!

**Comment by beutlich** [comment]
> Note that the 20% gray is the color used for all text, it has nothing to do with links or monospaced fonts.

OK, that seems to be the reason why links do not differ from the rest of the text.

**Comment by eshmoylova** [comment]
I also prefer the explicit color difference.

**Comment by henrikt-ma** [comment]
> I also prefer the explicit color difference.

OK.  Good to know.  Still, I believe it's best to not rock the boat too much right now, as it will be hard to quickly collect opinions from both sides; those who like not getting disturbed by colored links are unlikely to make themselves heard unless we go out and ask them.  (Note that phone meeting time was actually spent on advertising for participation in #2690, but with very little effect.)

**Comment by MartinOtter** [comment]
> Note that the 20% gray is the color used for all text, it has nothing to do with links or monospaced fonts. The change from pure black to 20% gray was one of the very first style changes made by @MartinOtter after the introduction of LaTeXML.

I do not recall this. Probably, this was not by purpose. I also prefer color-visible links.
