### ISSUE TITLE
Initializing discrete variables in algorithms when clocked

### ISSUE THREAD

**Issue by gkurzbach** [modelica/ModelicaSpecification#2816]
Chapter 11.1.2 states:
A discrete-time variable v is initialized with pre(v).

But is this still true when v is part of a clocked partition? This makes the partition to a clocked continous partition which is not expected. Wouldn't it be better to have an initialization to previous(v).

**Comment by HansOlsson** [comment]
Agreed, it would make sense to use previous(v) instead; as pre(v) isn't really defined for a clocked variable.

However, the reasonable interpretation is that pre(v) will have the same value as previous(v) on the first event iteration of an event, and clocked partitions should only be active on the first event iteration so it should sort of work.

However, related to MCP0038 I see one important difference indicating that it should be more complicated than just previous(v): if the algorithm is inside a state-machine and that state-machine is reset. (There's also another problem with that case, will open separate issue.)

**Comment by gkurzbach** [comment]
> Agreed, it would make sense to use previous(v) instead; as pre(v) isn't really defined for a clocked variable.
pre() on clocked variables makes their partition to a clocked continous partition, anabling a solver and event iterations.
> 
> However, the reasonable interpretation is that pre(v) will have the same value as previous(v) on the first event iteration of an event, and clocked partitions should only be active on the first event iteration so it should sort of work.
> 
But the use of an algorithm should not change the kind of the partition in an unnexprected unneeded way. If pre(v) already exists in the model, ok we can use this to initialize but the compiler should not introduce it.

**Comment by HansOlsson** [comment]
> > Agreed, it would make sense to use previous(v) instead; as pre(v) isn't really defined for a clocked variable.
> 
> pre() on clocked variables makes their partition to a clocked continous partition, anabling a solver and event iterations.

We certainly don't want that. I was more thinking that pre in itself as returning the value before event sort of worked.

**Comment by gkurzbach** [comment]
> 
> 
> > > Agreed, it would make sense to use previous(v) instead; as pre(v) isn't really defined for a clocked variable.
> > 
> > 
> > pre() on clocked variables makes their partition to a clocked continous partition, anabling a solver and event iterations.
> 
> We certainly don't want that. I was more thinking that pre in itself as returning the value before event sort of worked.

It is not specified whether a clock tick in a clocked continous partition is really the first step in an event iteration if needed at the same time. It could als be possible that the event iteration is part of the process of solving the continous system between the clock ticks. So both things would be well separated.

**Comment by gkurzbach** [comment]
Under this assumption, pre() and previous() would not return the same value at the first event step in an event iteration. There might be more then one eventiteration needed to solve the continous system and pre() would return the value from the previous iteration, but previous() still would return the value from the last clock tick.
An algorithm might be either evaluated in the context of the continous system or during a clock tick. So it is not clear, which kind of initialization should be applied.

**Comment by HansOlsson** [comment]
> Under this assumption, pre() and previous() would not return the same value at the first event step in an event iteration. There might be more then one eventiteration needed to solve the continous system and pre() would return the value from the previous iteration, but previous() still would return the value from the last clock tick.

I believe this hints at additional issues in the specification, since it is both stated that clocked equations are only active once per time-point and that there might be event iterations in discretized continuous-time partitions.

My statement above was only trying to justify that pre(v) in this context would sort of work like previous(v); but clearly this should be cleaned up.

**Comment by christoff-buerger** [comment]
> There might be more then one eventiteration needed to solve the continous system and pre() would return the value from the previous iteration, but previous() still would return the value from the last clock tick.

That is also exactly my understanding.

`previous(v)` is the value of `v` as hold at the end of the last sampling.
`pre(v)` is the value if `v` just before the last event (i.e., just before the current event iteration).

Assume for example, that a clocked partition with its solver yields a mixed equation system, where `pre(v)` and previous(v)` for a variable `v` that is subject to the mutual dependencies between continuous and discrete equations are used. Now `previous(v)` and `pre(v)` are two very different things. `previous(v)` is the solution for `v` computed in the previous sampling; throughout the current sampling it is constant. `pre(v)` however, is the last event iteration's value of `v` (with the current sampling requiring arbitrary many event iterations); `pre(v)` might change throughout the current sampling (until a fixpoint for `v` is found, i.e., a solution for the mixed equation system has been computed).

Above case of mixed equation systems with `pre(v)` and `previous(v)` we already have in one of the EMPHYSIS demonstrators. And we need this semantics. Dymola generates code behaving like this.

To specify a proper initialization for such a clocked partition is still challenging in Modelica (read bogus/non-sense) however.

**Comment by henrikt-ma** [comment]
> > > Agreed, it would make sense to use previous(v) instead; as pre(v) isn't really defined for a clocked variable.
> > 
> > pre() on clocked variables makes their partition to a clocked continous partition, anabling a solver and event iterations.
> 
> We certainly don't want that. I was more thinking that pre in itself as returning the value before event sort of worked.

I'm afraid that defining `pre` for clocked variables could cause problems with the intuitive understanding of `pre`, since it would need to be something rather different for a clocked variable compared to its current meaning.  Alternatively, it would require changing the basic definition of a clocked variable only existing at clock ticks, which also sounds dangerous.

**Comment by HansOlsson** [comment]
> > > > Agreed, it would make sense to use previous(v) instead; as pre(v) isn't really defined for a clocked variable.
> > > 
> > > 
> > > pre() on clocked variables makes their partition to a clocked continous partition, anabling a solver and event iterations.
> > 
> > 
> > We certainly don't want that. I was more thinking that pre in itself as returning the value before event sort of worked.
> 
> It is not specified whether a clock tick in a clocked continous partition is really the first step in an event iteration if needed at the same time. 

I agree that there are problems with the current formulation.
However, as I see it the only possible values for pre(v) in this context matches previous(v) so it will not be a change. (But ideally we want to forbid pre(v) in normal clocked code).

The reason is that if there is only one event iteration with clock-variable updates it doesn't matter if it is the first or not for for this, as previous(v) will give the value from the previous clock tick, and pre(v) in the same code (if legal, which it ideally shouldn't be) would be the same as v couldn't have changed.

For clocked-discretized continuous equations involving pre and possibly having pre inside them it is messier, and we need to investigate more; see also #2815

**Comment by christoff-buerger** [comment]
@henrikt-ma:
 > I'm afraid that defining pre for clocked variables could cause problems with the intuitive understanding of pre, since it would need to be something rather different for a clocked variable compared to its current meaning.

I don't think it means something completely different. `pre` in a clocked-continuous time partition has the same meaning like in a continuous time partition, looking at it from an event point of view; its meaning is not the one of `previous` however. It is `previous` that has a special meaning in clocked partitions, without any corresponding pure continuous language means (maybe `delay` is closest to `previous`, if, and only if, the delay happens to be the sampling time; but here we also have examples in EMPHYSIS where a physical delay is used in a clocked time partition that is a multitude, i.e., fixed but independent, of the sampling time, hence a **physical** delay).

That is what I liked to explain above using the mixed equation system example, which nicely illustrates the difference of `pre` and `previous` for clocked-continuous time partitions:
 
 > previous(v) is the value of v as hold at the end of the last sampling.
 > pre(v) is the value if v just before the last event (i.e., just before the current event iteration).

`pre(v)` in clocked time partitions means the same as in continuous: The value of `v` just before the last event. And in case of clocked-continuous time partitions we have event iterations due to the selected solver. But there is no difference regarding `pre` compared to solvers of pure continuous time partitions.

It is interesting to note however, that we can also have event-iterations in clocked(_-continuous?????_) time partitions even if no solver is selected however; an example is a reinit within such. For reinitialization we have to event-iterate. So I guess we could construct an example with no solver method, but where `pre` and `previous` are different in a clocked(_-continuous?????_) time partition (for example if it has `when` clauses). I wrote _-continuous?????_ because I am not sure what the definition for such time partitions without solver method, but event iteration, is. I assume we currently just speak of clocked whenever there is no solver -- even if there is need for event iteration; but maybe it would be better to call them also clocked-continuous (even if no solver, but there is need for event-iteration).

**Comment by henrikt-ma** [comment]
> That is what I liked to explain above using the mixed equation system example, which nicely illustrates the difference of `pre` and `previous` for clocked-continuous time partitions:
> 
> > previous(v) is the value of v as hold at the end of the last sampling.
> > pre(v) is the value if v just before the last event (i.e., just before the current event iteration).
> 
> `pre(v)` in clocked time partitions means the same as in continuous: The value of `v` just before the last event. And in case of clocked-continuous time partitions we have event iterations due to the selected solver. But there is no difference regarding `pre` compared to solvers of pure continuous time partitions.

I'm sure the distinction you want to make can be done somehow, but we should be careful about the basic definition of a clocked variable as something that only exists at clock ticks.  Thus, defining `pre(v)` as the value just before the current clock tick is somewhat problematic.  Somehow, the definition would need to be adopted to also work as you want for clocked variables, and the question I'm asking is just whether this would break too much of the intuitive understanding of `pre`.

On the other hand, there might not be any realistic alternative to overloading `pre` with slightly different intuition for clocked variables, since having different constructs could bring too much burden on the user who could have a hard time keeping track of which variables are clocked.  Right?

**Comment by christoff-buerger** [comment]
>  Thus, defining pre(v) as the value just before the current clock tick is somewhat problematic.

But that is the point. `pre(v)` for clocked variables has nothing to do with the clock ticks (I do not define it to be the value just before the current clock tick; that is `previous(v)` but not `pre(v)` -- please check above definition again); `prev(v)` is about event iteration, like in the continuous case. And how many event-iterations are required to compute a sampled partition for a *single* tick is not restricted by any means (it depends on the equation system, discrete events and used integrator, similar to normal continuous event-iteration).

Thus, I do not see any need to...

 > [..] to overloading pre with slightly different intuition for clocked variables,

...; `pre(v)` has one intuitive meaning for me, regardless if in clocked partitions or not (and that meaning is: `prev(v)` = value of `v` right before the last event influencing `v`. That this *can* mean value at last sampling Ok (assuming there have been no further events except the clock ticked); but it can also mean value of last event iteration to compute *this very* sampling (thus, there is some event iteration to compute a single sampling).

 > but we should be careful about the basic definition of a clocked variable as something that only exists at clock ticks.

`previous(v)` already requires some kind of bookkeeping to remember old values (which implies that this memory must somehow be persisted, i..e, exist, when the sampled partition is not active).

The definition is rather as something that is only computed/updated at clock ticks (less restrictive than only exists).

**Comment by henrikt-ma** [comment]
> The definition is rather as something that is only computed/updated at clock ticks (less restrictive than only exists).

In that case it gets hard to explain why a clocked variable can't participate in a continuous-time equation, doesn't it?

We've also struggled a bit lately with the fact that the first clock tick isn't necessarily at the beginning of the simulation, meaning that there's at least an interval at the beginning when there's really no value at all.

**Comment by HansOlsson** [comment]
> > The definition is rather as something that is only computed/updated at clock ticks (less restrictive than only exists).
> 
> In that case it gets hard to explain why a clocked variable can't participate in a continuous-time equation, doesn't it?

I believe you are talking past each other.

From the point of the equations the clocked variable only exists at clock ticks of the corresponding clock.

However, by using previous(v) and hold(v) you get some earlier value of the variable - indicating that it exists in some form; although that does not allow its use. The intent with the specification was that you shouldn't be allowed to use the clocked variables in continuous time or in other clock partitions - _not even at the times when the clocked variable exists_.

This indicates that the specification should be clarified so that variables only exist as part of clock partitions (as is indicated in the clock partition section)  - not at specific time-points (when the clock partition is active); so that the previous statement becomes:

From the point of the equations the clocked variable only exists at clock ticks of the corresponding clock; _and when evaluating the corresponding clock partition_.


> We've also struggled a bit lately with the fact that the first clock tick isn't necessarily at the beginning of the simulation, meaning that there's at least an interval at the beginning when there's really no value at all.

Yes, that still require more work.

**Comment by christoff-buerger** [comment]
> 
> 
> > The definition is rather as something that is only computed/updated at clock ticks (less restrictive than only exists).
> 
> In that case it gets hard to explain why a clocked variable can't participate in a continuous-time equation, doesn't it?
> 
> We've also struggled a bit lately with the fact that the first clock tick isn't necessarily at the beginning of the simulation, meaning that there's at least an interval at the beginning when there's really no value at all.

If it is only computed/updated at clock ticks, then obviously it has no value before the first tick (if we exclude that a [fixed] start value would imply to have that value even before the first tick -- I think that is not the case currently but we might argue about that).

> In that case it gets hard to explain why a clocked variable can't participate in a continuous-time equation, doesn't it?

The reason you cannot just use it in *another* clocked or continuous partition is only because the whole concept of clocked partitions requires partitioning! Without partitioning, we would not know when to compute/update variables in the first place. But that is only about knowing when to compute/update; it is not about existenc as such.

**Comment by henrikt-ma** [comment]
> I believe you are talking past each other.

Probably.  I seems as we're stuck discussing the wrong question.  The idea of what `pre(v)` should return – at least after a variable has been initialized at the first clock tick – seems simple enough, and the need for an additional state to keep track of it doesn't seem like a big deal (especially since tools could do optimizations and only introduce this state when needed). 
 Instead of discussing the philosophical questions and exact wording for "clocked `pre`", shouldn't we first settle how it would be used to solve the actual problems with algorithm initialization and consequences for event iteration?

**Comment by HansOlsson** [comment]
The conclusion regarding the original question seems to be that depending on other factors either `pre(v)` and `previous(v)` are the same, and then it doesn't matter if a discrete variable is initialized with `pre(v)` or `previous(v)`, **or** they are subtly different (clocked continuous partition) and in those cases `pre(v)` should be used for initializing `v` in an algorithm.

Thus no change is needed, and this issue can be closed.
