### ISSUE TITLE
Line break needed in the initialization section

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2891]
This line is too long in the [pdf version](https://specification.modelica.org/master/MLS.pdf):
https://github.com/modelica/ModelicaSpecification/blob/e4f879cb8659d7dcbda67a0e199b068d7e897218/chapters/equations.tex#L771

![image](https://user-images.githubusercontent.com/20460714/111163943-f26e9a00-8573-11eb-906f-f0cbf115729d.png)

**Comment by henrikt-ma** [comment]
To me, this is a tradeoff between aesthetics and maintainability, and not obviously something we must address.

To me, the ugly space at the beginning of the next line is an even bigger frustration; I can see why some lines "need" to be long to fit content that's hard to break nicely, but there's absolutely no need for the following line to start with white-space.  In light of such errors being passively accepted as part of the LaTeXML deal, reformulating a paragraph/item because of lines that still fit on the page seems like over-fitting content to line breaks in the PDF document.

On the other hand, if someone finds an even better formulation that also has nice line breaks, it wouldn't be the first time we actually fiddle with `\lstinline` and line breaks…
