### ISSUE TITLE
Clarification on "redeclare replaceable" mechanism when combined to the extends clause.

### ISSUE THREAD

**Issue by filippomariadonida** [modelica/ModelicaSpecification#2935]
Hi everyone,

I need your help to clarify a doubt I have regarding the "redeclare replaceable" mechanism when combined with a "extends". Things are probably easier with an example:

class P1
  replaceable class C Real r1; end C;
  C c1;
end P1;
class P2
  extends P1;
  redeclare replaceable class extends C Real r2; end C;
  C c2;
end P2;

what would you expect to have in the flat code of P1.C?

I'm asking this because some compiler implementations add r2 into P1.C, thus obtaining:

class P2
  Real c1.r1;
  Real c1.r2;
  Real c2.r1;
  Real c2.r2;
end P2;

and here is where I am totally lost: why the extend + the redeclare clauses of P2 are changing P1.C that resides in P1?

Best,

Filippo.

**Comment by perost** [comment]
That doesn't really have anything to do with extends, you get the same thing if you do e.g.:
```Modelica
class P1
  replaceable class C
    Real r1;
  end C;

  C c1;
end P1;

class P2
  extends P1;

  redeclare class C
    Real r1;
    Real r2;
  end C;
end P2;
```
Redeclares are applied before instantiating the components, so resolving the extends and redeclare you first get:
```Modelica
class P2
  class C
    Real r1;
    Real r2;
  end C;

  C c1;
end P2;
```
Then flattening it completely gives:
```Modelica
class P2
  Real c1.r1;
  Real c1.r2;
end P2;
```
So it's not that r2 is added to P1.C, it's that P1.C is overwritten with P2.C when you redeclare it.

**Comment by filippomariadonida** [comment]
Regarding your comment of "That doesn't really have anything to do with extends", isn't the P2 class declaration in your example reporting: "extends P1;"?

I still do not understand why we want to overwrite P1.C from P2 without clearly declaring that?

Is the fact that redeclaration come before instantiation somewhere present in the specification document?

I'm sorry but I'm confused here.

Best,

Filippo.

**Comment by perost** [comment]
> Regarding your comment of "That doesn't really have anything to do with extends", isn't the P2 class declaration in your example reporting: "extends P1;"?

Sorry, I meant that it doesn't have anything specifically to do with the `redeclare class extends` mechanism, but of course there's some extends involved since `redeclare` as an element requires the redeclared element to be inherited (https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#redeclaration).

> I still do not understand why we want to overwrite P1.C from P2 without clearly declaring that?

You are declaring that though, that's what `redeclare` means in this case. Although it's perhaps not correct to say that P1.C is overwritten, it would be more correct to say that C inherited by P2 from P1 is overwritten.

> Is the fact that redeclaration come before instantiation somewhere present in the specification document?

See https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#the-instantiation-procedure

**Comment by HansOlsson** [comment]
> Regarding your comment of "That doesn't really have anything to do with extends", isn't the P2 class declaration in your example reporting: "extends P1;"?
> 
> I still do not understand why we want to overwrite P1.C from P2 without clearly declaring that?

I believe part of that is that it is an abstract example and it is difficult to see what benefit overwriting the used P1.C in P2.

If we look at Modelica.Media.Interfaces.PartialMedium.setState_pTX and Modelica.Media.Interfaces.PartialLinearFluid.setState_pTX we see a similar situation: but C1 is now called ThermodynamicState; and to me it makes sense that setState_pTX is using the re-declared ThermoDynamicState.

**Comment by filippomariadonida** [comment]
@HansOlsson: thanks for the example, a real implementation helps, especially because both packages from the Media extend a partial declaration. 

I'll try to check if I understood correctly: P1.C in the below adapts and gets r2 rather than r3 depending on the context, meaning the P1.C is either containing r1, r2 rather than r2, r3.

If that is matching the intended behavior, the expected from the following?

class P1
  replaceable class C Real r1; end C;
  C c1;
end P1;

class P2
  extends P1;
  redeclare replaceable class extends C Real r2; end C;
  C c2;
  P1.C p1c2;
end P2;

class P3
  extends P1;
  redeclare replaceable class extends C Real r3; end C;
  C c2;
  P1.C p1c2;
end P3;


Best,
Filippo.

**Comment by perost** [comment]
> I'll try to check if I understood correctly: P1.C in the below adapts and gets r2 rather than r3 depending on the context, meaning the P1.C is either containing r1, r2 rather than r2, r3.

It might be better to think of it like P1.C doesn't change, what the redeclare changes is what's inherited from P1 by P2 och P3. So if you apply the extends and redeclares you end up with:
```Modelica
class P1
  replaceable class C
    Real r1;
  end C;
end P1;

class P2
  replaceable class C
    Real r1;
    Real r2;
  end C;

  C c1;
  C c2;
  P1.C p1c2;
end P2;

class P3
  replaceable class C
    Real r1;
    Real r3;
  end C;

  C c1;
  C c2;
  P1.C p1c2;
end P3;
```
Flattening P3 then gives you:
```Modelica
class P3
  Real c1.r1;
  Real c1.r3;
  Real c2.r1;
  Real c2.r3;
  Real p1c2.r1;  // But not p1c2.r3, because P1.C does not refer to the inherited C
end P3;
```

**Comment by filippomariadonida** [comment]
Ok, thanks for further explaining, I think I understand now: there could be multiple P1.C, depending on the scope:
- outside of P2 you got the original P1.C declaration, i.e. only containing r1,
- inside P2 you got the redeclared P1.C version, i.e. also containing r2.
Is this correct?

**Comment by HansOlsson** [comment]
> Ok, thanks for further explaining, I think I understand now: there could be multiple P1.C, depending on the scope:
> 
> * outside of P2 you got the original P1.C declaration, i.e. only containing r1,
> * inside P2 you got the redeclared P1.C version, i.e. also containing r2.
>   Is this correct?

Yes.

**Comment by filippomariadonida** [comment]
Thanks @HansOlsson and @perost for your explanations.

**Comment by eshmoylova** [comment]
> Ok, thanks for further explaining, I think I understand now: there could be multiple P1.C, depending on the scope:
> 
> * outside of P2 you got the original P1.C declaration, i.e. only containing r1,
> * inside P2 you got the redeclared P1.C version, i.e. also containing r2.
>   Is this correct?

I would say that `P1.C` stays the same but `C` is different depending on where you define it. Because you defined c1 as of type `C`: 
```
class P1
  replaceable class C Real r1; end C;
  C c1;
end P1;
```
for `P2.c1` it would be resolved to `P2.C` and for `P3.c1` it would be `P3.C`. If you declared `c1` as:
```
class P1
  replaceable class C Real r1; end C;
  P1.C c1;
end P1;
```
it would always resolve to `P1.C` regardless of redeclaration of `C`. However, it is not allowed to refer to `P1.C` because `P1` does not satisfy the requirements of the package (because it has the component `c1`). So I would say that if you want `c1` to always be of the same type regardless of definition of C you need to define a different type that is the same as C but not replaceable.
```
class P1
  class C Real r1; end C;
  replaceable class CR = C;
  C c1;
end P1;
```

**Comment by filippomariadonida** [comment]
@eshmoylova thanks this makes more sense: RE: _P1.C stays the same but C is different depending on where you define it_.

The doubt I have left is due to the extends mechanism since we're extending from P1 thus I would expect the c1 instance being of type P1.C?

class P1
  replaceable class C Real r1; end C;
  C c1;
end P1;

class P2
  extends P1; // When doing this I would think of a P1.c1 of type P1.C being in P2
  redeclare replaceable class extends C Real r2; end C;
  C c2;
  P1.C p1c2;
end P2;

**Comment by eshmoylova** [comment]
@filippomariadonida we are supposed to first bring in all classes from the extends clauses and only then resolve the classes of components. So after expanding the extends-clause of `P1` in `P2` we get:
```
class P2
  replaceable class <base C> Real r1; end <base C>;
  C c1;
  redeclare replaceable class extends <base C> Real r2; end C;
  C c2;
  P1.C p1.c2;
end P2; 
```
OK, this is a bit of tool-specific representation. I don't think it is specified if we are supposed to resolve "class extends" classes before instances are resolved. So in MapleSim we choose to do it only if somebody actually uses that class. What is specified is that there is only one `C` after the classes from P1 are brought in. After resolving the extends clauses we need to resolve the types of the instances. At that point we look at `C c1;` and search for the definition of `C` in the scope of `P2`. There is only one `C`  in the scope of `P2` which extends <base C>.

Actually, the whole point of using "replaceable" classes and then call "redeclare" on them is that you can replace the definition of `C` used by `c1` in `P2`. "class extends" only says that you want to add to the previous definition of `C` instead of defining it from scratch.
