### ISSUE TITLE
Help the convergence by setting the min and max boundary of state variables?

### ISSUE THREAD

**Issue by Satinelamp** [modelica/ModelicaSpecification#2965]
I was struggling to improve the convergence performance of my model. Now I am thinking about that If I define the min and max attributes of the state variables, like the max mass flow rate is 10000kg/s, the min mass flow rate is 0.01kg/s, I am considering if when the iteration result reaches the boundary, the iteration would bounce back in the opposite direction, which might ensure the convergence of my model. I suggest maybe we could use the min/max attributes to help the initialization/simulation converged. Because the min/max boundary values are all the information the users could provide. Apparently, now min/max attributes are used to verify if the iteration values are out of the boundary, and if they are, the initialization/simulation just stops, but it might be better if we could use this information to improve the iteration. According to the answer on [Stackoverflow,](https://stackoverflow.com/questions/59210066/could-i-ensure-the-convergence-by-setting-the-min-and-max-boundary-of-state-vari) this idea might be not worth trying, but I think it is still worth a discussion.
My  suggestion is:
It should be recommended that [min/max attribute](https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#real-type) could be used to help convergence, not only for assertion.

**Comment by HansOlsson** [comment]
How to use min/max attributes to help convergence is non-trivial (and even NP-hard (at least I can see that you formulate 3SAT problems with them)).

The underlying problem is that with multiple variables and equations it is not clear that there is any set of values that satisfy all of the min/max-attributes.

Note that using them for assertions doesn't mean that if the assertions the simulation/initialization just stops - instead it means that error recovery starts, which may involve trying a smaller "change". And in that sense the assertions can already help with convergence. However, in many cases there is no obvious way to recover.

**Comment by Satinelamp** [comment]
Maybe the idea in the following paper could be useful.
On the choice of initial guesses for the Newton-Raphson algorithm: https://arxiv.org/pdf/1911.12433.pdf

**Comment by casella** [comment]
> > Maybe the idea in the following paper could be useful.
> > On the choice of initial guesses for the Newton-Raphson algorithm: https://arxiv.org/pdf/1911.12433.pdf
> 
> I don't see how that helps with this issue. The problem of solving non-linear systems in the presence of min/max-bounds still seem NP-hard in general.

Those criteria are by no means meant to improve the robustness of convergence, given a set of initial guesses, which may be very hard problem. They  are just meant to help picking out the badly wrong start attributes in case one has some ideas on them in general. This could be combined with min-max attribute checking after one iteration, to further improve the heuristics.

One possible way to use the criteria in that paper combined with min-max attributes is the following:
- check that all initial guesses (based on start values) respect the given min-max bounds - I guess this should be done anyway
- after one iteration, check again - if some variables are now out of those bounds _and their \alpha, \Gamma and \sigma values are high_, then report to the end user that their start values are probably in need to be improved.

However, this is purely heuristic: there is always the possibility that a bad start value for one nonlinear unknown triggers another one to go astray. Anyway, it is definitely a tool issue, not a specification issue. 

> And that paper tries to argue that the linear part is unimportant - but there can be min/max-bounds in the linear part so several of the theorems (e.g. Theorem 4 & 6) seem to only be valid if we ignore the min/max-bounds during the iterations.

Of course one has to assume first that the solution will respect min- and max-bounds, otherwise obviously there is no hope that including them in the game will improve convergence. The goal of the criteria in that paper is to make sure your initial guesses are already in a region that will ensure quick convergence to the solution, and to show you which ones aren't.


My 2 cts.
