### ISSUE TITLE
pure(...) operator semantic clarification

### ISSUE THREAD

**Issue by jonathankampemodelon** [modelica/ModelicaSpecification#2971]
Besides the grammar, the pure operator is only mentioned in chapter 12.3

> pure(impureFunctionCall(. . .)) – which allows calling impure functions in any pure context.

The operator could use some clarification. Should it not be expanded on in chapter 3.7 along with the other operators?

Some concrete questions:
1. Are there any semantic limitations? Is any expression legal as argument?
2. Does it apply to all functions in the argument? For example, is `pure(f(g()))` equivalent to `pure(f(pure(g())))`?
3. Does it mean we can rearrange the evaluation order in sub-expressions? For example, in `pure(f()+g())` can `g()` be evaluated before `f()`?

**Comment by henrikt-ma** [comment]
These are good questions and I get the impression that you folks at Modelon are currently in the best position to give qualified answers.

I agree that it ought to be mentioned somewhere in 3.7, and it seems like a good candidate for a _special purpose operator with function syntax_.

Question 1 and 2 seem closely related.  I've also asked myself whether any expression is legal as argument, but can't remember if there was ever a separate issue created for it.  In its current form, restricting it to a function call seems unintuitive since there could be general expressions among the function arguments, and it would be odd if the `pure` didn't apply also to the function arguments wrapped inside it.  (If the syntax would have been `pure(impureFunction)(arg1, …)` it would have been more clear that it only applies to the callee and not the arguments.)

For question 3, it annoys me that a statement like this isn't normative:
> A tool is not allowed to perform any optimizations on function calls to an impure function, e.g., reordering calls from different statements in an algorithm or common subexpression elimination is not allowed.

Anyway, for `pure(f() + g())`, would there have been an evaluation order guarantee even without wrapping in `pure(…)`?  Maybe a better example would be to ask about common subexpression elimination in `pure(f() + f())`?

**Comment by jonathankampemodelon** [comment]
> Anyway, for pure(f() + g()), would there have been an evaluation order guarantee even without wrapping in pure(…)?

After reading 3.3 Evaluation Order; No, there's no guarantee.

> Maybe a better example would be to ask about common subexpression elimination in pure(f() + f())?

Yes, and with the limited information available I would say that it is not allowed. I think it would be good to explicitly state that.
> pure(impureFunctionCall(. . .)) – which allows calling impure functions in any pure context.

> A tool is not allowed to perform any optimizations on function calls to an impure function, e.g., reordering calls from different statements in an algorithm or common subexpression elimination is not allowed.

**Comment by HansOlsson** [comment]
As I understand it was added in #1937 and those parts weren't clear, and that's why it wasn't added.
The main part of the discussion was that pure as added in Modelica 3.3 broke way too much, and that needed fixing.

However, the main discussion was about pure for a specific function - although having it for general expressions was also considered.

If we specify that restriction it is basically as if `pure(f(...))` were seen as `pure(f)(...)` and thus to me the logical conclusions are:
1. Only `pure(f(...))` is allowed, no general expression.
2. It does not imply anything for the arguments of `f`; as they are not "pure".
3. And the arguments can be re-arranged and optimized in various ways.

**Comment by henrikt-ma** [comment]
> If we specify that restriction it is basically as if `pure(f(...))` were seen as `pure(f)(...)` and thus to me the logical conclusions are:
> 
> 1. Only `pure(f(...))` is allowed, no general expression.
> 2. It does not imply anything for the arguments of `f`; as they are not "pure".
> 3. And the arguments can be re-arranged and optimized in various ways.

With such a specification (and I agree that this seems like the best kind of back door for bypassing purity analysis), wouldn't it be good to also introduce the alternative syntax `pure(f)(…)` that makes the semantics more intuitive?  The current syntax could be kept just as a deprecated way of saying the same thing.
