### ISSUE TITLE
Meaning and restrictions for 'import names'

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2974]
The term _import name_ seems to be used inconsistently, meaning that the uniqueness rule for qualified imports is unclear.  This issue looks like it could be a follow-up to #1573.

Searching for _import name_ in the sources gives me these three matches (ordered for purposes of this presentation):

1:
> Among the import names of qualified import-clauses in the \emph{instance} scope.  The import name of \lstinline!import A.B.C!; is \lstinline!C! and the import name of \lstinline!import D=A.B.C;! is \lstinline!D!.

2:
> Assume that we want to access the package \lstinline!MyLib.Pack2! in \cref{fig:roots} above, e.g.\ through an \lstinline!import!-clause \lstinline!import MyLib.Pack2;!. During lookup we first try to find a package \lstinline!MyLib! corresponding to the first part of the import name.  It is not found in the top-level scope since it has not previously been loaded into the environment.

3:
> Multiple qualified \lstinline!import!-clauses shall not have the same import name.

From 1 we seem to get a clear definition of what the _import name_ is, but then 2 speaks of the first part of the import name, which doesn't make sense in view of 1 where there's always just one part.

What is really meant by 3?  Is the purpose to forbid things like the following?
```
import Pack.{f, f};
```
That doesn't seem to correspond to one of the confusing situations discussed in #1573, making me think that the purpose of the rule is to rule out something else…

**Comment by HansOlsson** [comment]
I would say that 2 is incorrect use of the term import name and it should be re-written.

For 3 I would more say that the intent is to forbid:
```
import Pack1.f;
import Pack2.f;
```
(Regardless of whether `f` is actually used. So the same meaning of import name as in 1.)
Obviously if they are identical (as in your example) there is no real ambiguity, but it is still bad style and there's no real reason to allow it. Historically that occurred a few times for:
```
import SI=Modelica.SIunits;
...
import SI=Modelica.SIunits;
```
That wasn't discussed in #1573 as I recall; probably because it was clear that it was incorrect.

**Comment by henrikt-ma** [comment]
> I would say that 2 is incorrect use of the term import name and it should be re-written.

Sounds like a good resolution.
