### ISSUE TITLE
Why can't derivatives be assigned in algorithm sections?

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2984]
According to [Section 11.2.1](https://specification.modelica.org/maint/3.5/statements-and-algorithm-sections.html#simple-assignment-statements) of the Specification

> The syntax of simple assignment statement is as follows:
>
> `component-reference ":=" expression`

This means that the following model is invalid
```
model M
  Real x(fixed = true);
algorithm
  der(x) := 1;
end M;
```
since obviously `der(x)` is not a component reference. On the other hand, I don't see anything wrong with assigning values to derivatives in algorithms; in fact, the whole purpose of continuous-time Modelica models is indeed to compute state derivatives, so that the ODEs can be solved over time.

I would propose to amend Section 11.2.1 to make models such as `M` legal, e.g.

> The syntax of simple assignment statement is as follows:
>
> `component-reference | der(component-reference) ":=" expression`

**Comment by HansOlsson** [comment]
First and foremost we want to encourage the use of equations, so the obvious change of the model would be to use:
```
model M
  Real x(fixed = true);
equation
  der(x) = 1;
end M;
```
Obviously there are cases where algorithms are useful, but in case the algorithm originates in a normal procedural language it would be kind of odd that it uses der - since that it isn't part of such languages. Thus I don't see this as such a major issue in practice.

There are also a number of technical issues:

- Continuous-time variables are set to their start values at the start of algorithms (unless unconditionally assigned), but der-variables don't have start values.
- We also have to consider non-simple assignments such as `(a,der(b)):=foo(...);`
- We cannot just change the grammar in that section - obviously it should be integrated in the real grammar.

**Comment by casella** [comment]
I actually agree, in particular on the fact that we should promote using equations instead of algorithms outside function bodies. In fact, I never fully understood the point of algorithm sections in models.

The reason I asked is that I wanted to compare the simulation results of a declarative model with an equivalent, manually sorted and symbolically solved model, that I also wanted to write in Modelica, hence the use of the algorithm. OpenModelica complained about `der(x) := something` not being legal, while Dymola accepted it, so I wanted to understand if there was a rationale behind this rule. I now see it. I just wonder why Dymola accepts `M` then. But that is of course a tool issue.

**Comment by casella** [comment]
I guess I can close this, unless there are other opinions in the group.
