### ISSUE TITLE
Syntax of preferredView annotation

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2988]
The specification of the `preferredView` annotation looks inconsistent.

According to the grammar of the annotation, it should be used like this (supported by System Modeler):
```
annotation(preferredView = info);
```

However, in the examples it is used with a string instead, in agreement with how the annotation is used in the MSL:
```
annotation(preferredView = "info");
```

I see some alternatives:
- Pretend the non-string variant has ever existed; just silently change it to use strings instead.
- Add the string form and treat both forms equal.
- Add the string form and deprecate the non-string form.

**Comment by perost** [comment]
This seems like something that should rather be an enumeration, but I guess it's probably too late for that.

Otherwise it seems like it's probably just an oversight by the person who wrote that bit of grammar. It's the only place in the specification where the valid option strings are enumerated using grammar that I could find.

**Comment by HansOlsson** [comment]
I also believe that it was an oversight when writing the grammar; basically forgetting that `"info"` in the grammar-context mean the name `info` not the string "info".

For resolving it:
I would prefer to have it as a string, and either silently change this or deprecate the non-string variant. 
The reason is that strings are more extensible, see #2987
