### ISSUE TITLE
Clarification on where reinit is allowed

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3001]
I'm afraid that the rule for where `reinit` is allowed may not be clear enough:
> `reinit` can only be used in the body of a `when`-equation.

Are we sure that no further clarification is needed regarding the following?
```
/* Case A */
der(x) = 1.0;
when time > 1.0 then
  if b then
    reinit(x, 0.0);
  end if;
end when;
```

```
/* Case B */
der(x) = 1.0;
when initial() then
  if b then
    reinit(x, 0.0);
  end if;
end when;
```

```
/* Case C */
  Clock c = …;
  when c then
    der(x) = 1.0;
  end when;
  when subSample(c, 3) then
    reinit(x, 0.0);
  end when;
```

```
/* Case D */
der(x) = 1.0;
when Clock(1.0) then
  reinit(x, 0.0);
end when;
```

**Comment by HansOlsson** [comment]
I don't see any problems with A and B (I would say that B more commonly occurs using `when {initial(),..}`).
For C and D the problem is that when-equations should exclude "Clocked when-clause" here and in other cases.

A simpler example illustrating this:
```
  Real x;
equation 
  when Clock(1.0) then
    x*3=sample(time);
  end when;
```
According to https://specification.modelica.org/maint/3.5/synchronous-language-elements.html#clocked-when-clause we just have equations in clocked when-clause (and they become clocked) so this should be legal; which makes sense.

However, this is in contrast to https://specification.modelica.org/maint/3.5/equations.html#when-equations when-equations where we must have a variable in the left-hand-side in a when-equation; since the variable is discrete and held as pre(x) (the semantics of clocked when-clauses is different), and thus the following is illegal.
```
  Real x;
equation 
  when sample(1,1) then
    x*3=time;
  end when;
```
So the conclusion is that clocked when-clause shouldn't be seen as when-equation, and that also makes C&D illegal.

**Comment by HansOlsson** [comment]
B is explicitly mentioned in https://specification.modelica.org/maint/3.5/equations.html#initialization-initial-equation-and-initial-algorithm

**Comment by henrikt-ma** [comment]
> B is explicitly mentioned in https://specification.modelica.org/maint/3.5/equations.html#initialization-initial-equation-and-initial-algorithm
> (Well, except the if - but conditional equations in initial equations are common.)

The combination of `initial()` and `if` is the point of the example, as it isn't totally obvious how this would correspond to an equation in the initialization problem.  For me, it would be enough to clarify that within a `when`-clause active during initialization, each `reinit` is turned into an equation, whether directly under the `when`-clause or nested inside `if`-equations.

The following example could illustrate an important difference.
```
when time > 0.5 then
  /* Balanced if-equation, as a reinit isn't counted for purposes of balancing the branches. */
  if x > 0 then
    reinit(x, 0);
  end if;
end when;

when initial() then
  /* Unbalanced if-equation in the initialization problem. */
  if x > 0 then
    reinit(x, 0); /* Turns into the equation x = 0 in the initialization problem. */
  end if;
end when;
```

**Comment by henrikt-ma** [comment]
This problem noted by @HansOlsson in https://github.com/modelica/ModelicaSpecification/pull/3000#pullrequestreview-755636969 should also be addressed together with the other problems in this issue.  Sentence doesn't make sense:
> having `reinit` of the same variable in `when` and `elsewhen` of the same variable is allowed

Quoting @HansOlsson:
> That seems repetitive and the second "same variable" should be something else: that reinit of the same variable should be possible in both when and elsewhen of one when-equation.

**Comment by henrikt-ma** [comment]
I see now that the clocked part was missed in #3063.  Quoting https://github.com/modelica/ModelicaSpecification/issues/3001#issuecomment-920383402 above:
> So the conclusion is that clocked when-clause shouldn't be seen as when-equation, and that also makes C&D illegal.

This should be clarified both in 8.3.5 _When-Equations_ and in 16.6 _Clocked When-Clause_, (along with proper cross references).

Reopening.
