### ISSUE TITLE
Two identical entries for inverse in Index

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3047]
While reviewing #3043 and looking for examples of indices with multiple entries (in HTML) I found that `inverse` has two what looks like identical entries:
> inverse - Annotation 12.3, §12.7.3, Annotation 12.3

They point to the same paragraph definition but different parts of it. It's especially confusing because the link that appears first takes you the middle of that paragraph and the actual definition link is the last entry in the index.

I think the reason for double entries is because the `annotationdefinition` automatically creates an index entry and so does `\fmtannotationindex` used on this line:
https://github.com/modelica/ModelicaSpecification/blob/7ad198650e8ac01f6e50c700ba3e30e79eb335b4/chapters/functions.tex#L1280
Maybe the reference to the definition of the annotation is enough?

**Comment by HansOlsson** [comment]
I agree that one of them should be enough, and considering it more I think one possibility would be to replace all `\fmtannotationindex` by `\lstinline` and `\annotationindex`  placed at a consistent spot. The reason is that even when it works, it is hard to do it consistently - and I prefer consistency even over automation.

As examples consider https://github.com/modelica/ModelicaSpecification/blob/7ad198650e8ac01f6e50c700ba3e30e79eb335b4/chapters/annotations.tex#L1033-L1077

When seeing whether they are correctly indexed you have to look through more to find it.

**Comment by henrikt-ma** [comment]
There is no requirement to use `\fmtannotationindex`, but the convenience of it makes it more likely that we will have a well maintained index where all the annotations can be found.  As your example shows, there are currently situations where one doesn't want the index entry to point to a place where the annotation appears in the text, but those are exceptional situations and maybe the real solution here is that the `OnMouseUpSetBoolean` would benefit from a more systematic way of presenting annotations.
