### ISSUE TITLE
Has the Access.hide annotation a meaning for instances of the class?

### ISSUE THREAD

**Issue by gkurzbach** [modelica/ModelicaSpecification#3049]
If I have a class with annotation(Protection(access = Access.hide)); and an instance of this class in a model.
What I should be able to do and to see with this instance when I look at the model in diagram view?

According to the specification all kind of access to the class not possible, but applies this also to the instance?
- Is the instance visible at all?
- If yes, can I have access to public parameters? (this is what D*a does)
- ...

**Comment by HansOlsson** [comment]
Yes, I would say the intent is that it should be invisible in some way.
Exactly how isn't clear - it could either be seen as a misspelled class name and indicated as an error, or just hidden.

**Comment by HansOlsson** [comment]
I would say the description "Do not show the class anywhere (it is not possible to inspect any part of the class)." is clear, but we can confirm that it is the intent.

**Comment by henrikt-ma** [comment]
It wouldn't be unreasonable to show the existence of the instance, but not allow the type of the instance to be accessed.  At least, this would avoid a completely broken look of the diagram where the instance is used.  For this scenario one should probably clarify whether the component's icon should still be accessible, or whether the instance has to be shown with some generic component-of-hidden-type-icon.

**Comment by henrikt-ma** [comment]
> I thought that was what `Access.icon` was for.

It would be meaningful enough to let the distinction between `Access.icon` and `Access.hide` come down to whether an icon representing the class is shown in places pointing to the class itself, not instances of it, for example in a package browsing tree.

To make `Access.hide` go further and make instances of the class not show just seems too messy when you think about looking at the text view of a model with an instance of the class.  Since such use might expose internals in the form of what can be modified (or even redeclared), allowing the icon of the instance to show in the diagram view doesn't seem like a big deal, and it will definitely help understanding the model containing the instance if one can still see how the instance is connected.

If one doesn't want to this kind of leak to be possible, I'd suggest that a class with `Access.hide` gets restricted to that it can only be used in other classes with protection at least `Access.icon`.

**Comment by HansOlsson** [comment]
> If one doesn't want to this kind of leak to be possible, I'd suggest that a class with `Access.hide` gets restricted so that it can only be used in other classes with protection at least `Access.icon`.

Yes, I think that's the best solution.
