### ISSUE TITLE
Arrow link to show raw listing in HTML output doesn't work in modern Chrome

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3102]
In a modern Chrome, clicking the "arrow" button to the top right of listings, for example in this page:
https://specification.modelica.org/master/introduction1.html#some-definitions
will not do anything, and if you look at the Console you see:

```
Not allowed to navigate top frame to data URL: data:text/plain;base64,...
```

This is a security measure, see https://groups.google.com/a/chromium.org/g/blink-dev/c/GbVcuwg_QjM

I used Chrome Version 96.0.4664.110.

In a Firefox 95.0.1 it doesn't seem to work either, but I don't get any indication of why. One could guess they have taken similar security measures.

**Comment by HansOlsson** [comment]
Hmm...
My Google chrome seems to be 100.0.4896.127 which seems later and I get a background download.
 
However, for reasons I cannot understand it adds the file-extension "mos" - not "mo"; it might be that it was due to a previous download - or it might be some configuration. 
And then there might also be some special setting for chrome.

**Comment by maltelenz** [comment]
Looks like there has indeed been some change!

In Chrome `100.0.4896.127` I now get a `download.txt`.
In Firefox `9.0`  I now get a download named `seemingly-random-hash.txt`.

I think we can close this then.
