### ISSUE TITLE
Modelica and tunable parameters

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3140]
I'm opening this ticket inspired by the discussion [here](https://github.com/OpenModelica/OpenModelica/discussions/8568), and after an email exchange with @TorstenBlochwitz.

The FMI standard introduced the concept of _tunable parameters_. This concept has no counterpart in Modelica, and I understand from @TorstenBlochwitz that it is currently a tool issue to determine which parameters in a Modelica model can actually be turned into a tunable model when generating the corresponding FMU.

In view of better standard coordination, I wonder if it could be useful to introduce some annotation in Modelica to make this more explicit.

Any opinions?

**Comment by TorstenBlochwitz** [comment]
From my point of view this feature is not only related to tunable parameters of FMUs when the Modelica model is exported as FMU. Even a Modelica tool might allow changes to parameters via the GUI during simulation.

**Comment by henrikt-ma** [comment]
I haven't actually implemented a criterion for automatic detection of tunability, and one reason is that it seems rather complicated to get it right, isn't it?  Would it be easier to verify that a component declared as tunable parameter is only used in ways that allow tuning?

For example, if `tunable` was made a first class Modelica variability, I suppose a model like the following should be rejected:
```
model TunabilityError
  tunable Real L = 0.5; /* Error: L is not in tunable position in model equations. */
  Real lambda;
  Real x(start = 0.5), y(start = 0.2);
equation
  x^2 + y^2 = L^2;
  der(der(x)) = -x * lambda;
  der(der(y)) = -y * lambda - 10;
end TunabilityError;
```
That is, changing the value of `L` after initialization would invalidate the length constraint equation, and since there isn't an obvious way for how to adjust the variables to be on the new solution manifold, it should be concluded that changing `L` after initialization isn't allowed.

Do we think we are ready to write down a tool independent criterion for valid tunability?  If not, it is probably better to leave it to tool specific analysis for the sake of model portability between tools.  (Otherwise, one tool may allow the user to declare a component as tunable, while another tool's analysis don't agree that the component is tunable and therefore considers the model invalid.)

**Comment by HansOlsson** [comment]
> I haven't actually implemented a criterion for automatic detection of tunability, and one reason is that it seems rather complicated to get it right, isn't it? Would it be easier to verify that a component declared as tunable parameter is only used in ways that allow tuning?

Yes, and the mathematical idea would be to forbid differentiation of tunable parameters (or possibly differentiating them twice).

But:
- Sometimes the differentiation is done before writing the equations in Modelica. A classic case is `der(C*Q)` vs `C*der(Q)` for (variable) capacitance; and that's why we would need models re-written using updated semantics.
- Many of the intended uses of tunable parameters in models are cases that are not strictly correct; the idea in those cases is that the change slightly breaks thing - but then it stabilizes at a new re-tuned value.

Another case of non-tunable parameters are:
```
  parameter Real x0;
  Real x(start=x0, fixed=true);
equation
  der(x)=u-x;
```
Changing x0 after the initialization will not change anything (assuming it is not used elsewhere), so it doesn't make sense to view it as tunable - even though re-tuning it is harmless.

**Comment by christoff-buerger** [comment]
I like to add to the discussion, that in eFMI we support tuneable parameters.

This is our eFMI specific support for runtime tuning; runtime means throughout execution (not just initialization) on the embedded device. The support is eFMI specific, because we have to work in a safety critical, real time suited environment. To that end, eFMI has a layered approach to what can change when, i.e., has to be/can be initialized, recalibrated, reinitialized or recomputed when. The layers of variability are constants, tuneable parameters, dependent parameters, inputs outputs and states.

It is important to note, that:
 - We do not support structural changes (parameters are describing physical/runtime-values properties, **never** structural like dimensional sizes).
 - The whole abstraction is on the algorithmic/computational level (GALEC code). Thus:
   - States are **not** physical states (i.e., Modelica state selection), but everything that must be stored/persisted inbetween two samplings because it is used before being assigned in the `DoStep()` method.
   - Recalibration means to change a tuneable parameter at runtime, with respective reevaluation of dependent parameters; such reevaluation are only permitted to depend on constants and tuneable parameters (and dependent parameters that are assigned before beeing used in the same recalibration).
   - Reinitialization means to initialize at runtime anew, considering the current parametrization **and inputs**; it assigns values to all states and outputs.

Note, that all of this is on the GALEC level defined, i.e., an a-causal algorithmic language. Hence, a Modelica tool first has to find an algorithmic solution for the model physics. And this solution must be expressed as GALEC program.

The example of @henrikt-ma is a physical modelling issue. In eFMI we do not forbid such tuning nor do we care; if a GALEC solution can be generated it is fine to tune all tuneable parameters. The point is, that whenever you do so, this has a well-defined GALEC execution semantic.

The whole eFMI GALEC design is about computational correctness (i.e., well-defined execution on hardware), not whether the GALEC program's semantic does a certain thing. And I think this is the correct abstraction. You can not expect, that a tool can proof that something does the right thing when that tool/language is about modelling general/arbitrary systems. Therefore, I think what @henrikt-ma implies is the wrong track: we will never be capable to automatically catch for arbitrary equation systems if their tunables are proper according to the domain the equation system models something in. If a user says "this is a tuneable parameter" we can only check "is it independent", and if so then it is tuneable. This is similar to the situation with `final`; if users know a model breaks if you change this or that, it is their responsibility to forbid such changes via `final`. Tuneable is just the other way around: it is the modellers responsibility to ensure tuning a parameter has sensible semantics in the modeled physics domain (and he might for that reason restrict tuning to certain values).

**Comment by casella** [comment]
@christoff-buerger based on your discussion, it seems that we would need some kind of primitive in Modelica for modellers to declare _explicitly_ what are tunable parameters, because that is a-priori information that cannot be derived _exclusively_ from mathematical structure, but is something the modeller should take the responsibility of declaring based on their knowledge.

In absence of this information, it seems to me that no parameters of Modelica models could be _safely_ be considered as tunable parameters in the derived eFMI, so in the hierarchy constants, tuneable parameters, dependent parameters, inputs outputs and states they should probably be considered as constants, a priori.

Do I get this right, or do I miss something?

**Comment by casella** [comment]
In any case, given the MA motto "open, coordinated standards for system simulation" we should reach a broad and solid consensus among tool vendors about the meaning of this concept for all involved MA standards. If tool vendors, modellers, and end users have different interpretations that are inconsistent, the end result could be quite messy.

**Comment by henrikt-ma** [comment]
> The example of @henrikt-ma is a physical modelling issue. In eFMI we do not forbid such tuning nor do we care; if a GALEC solution can be generated it is fine to tune all tuneable parameters. The point is, that whenever you do so, this has a well-defined GALEC execution semantic.

In Modelica we have equations to be fulfilled, and that's probably the key difference here – sure, tunability isn't a concern for an algorithmic execution model.

What I am suggesting is not that the ideal solution would be that tools would automatically infer which parameters are tunable, even though that appears to be the best option currently available for FMI export from Modelica when trying to take maximum advantage of tunability in FMI.

What I'm suggesting is that there ought to be some _sufficient_ conditions for allowing a parameter to be tunable without breaking equations when a tunable parameter gets tuned.  Assuming that, I see two main paths:
- Treating it as quality of implementation to find the most relaxed conditions to be applied when translating a model (for example, during FMI export).  This means that different tools could be marking different parameters as tunable for the same Modelica model.
- Agreeing on a standardized set of conditions that any tool should be able to check. As noted by @HansOlsson above, formulating and checking such conditions could be more or less difficult depending on whether tunability is a declared variability.

My personal preference for this kind of concept is clearly to have a declared variability corresponding to what to expect in the translated model (exported FMU), and that tools shall reject models where the declared variability isn't feasible.  Having a declared variability also allows us to take advantage of the explicit variability rules that help enforcing correct variability and allow for more helpful error reporting.

**Comment by henrikt-ma** [comment]
Maybe, before trying to reach agreement on what is a tunable parameter in a Modelica model, we should first think about how to express that a plain `parameter` in Modelica is expected to be a parameter of an exported FMU…

**Comment by christoff-buerger** [comment]
> @christoff-buerger based on your discussion, it seems that we would need some kind of primitive in Modelica for modellers to declare _explicitly_ what are tunable parameters, because that is a-priori information that cannot be derived _exclusively_ from mathematical structure, but is something the modeller should take the responsibility of declaring based on their knowledge.
> 
> Do I get this right, or do I miss something?

Exactly!

Only the modeler knows for example in which range and to which extend a parameter can be tuned from one value to the next to ensure model stability.

Take controllers as an example. Even if tuning of some parameter always works (whatever that means mathematically), it may take quiet some period -- i.e., many samplings -- until the controller tuned in because the internal states only step-wise adjust towards the new tuning. Maybe to long for the application at hand for which reason you want to combine a recalibration with an reinitialization to also reset the states (to "erase" their memory/history).

Or consider chattering caused by tuning: to which extend it is acceptable depends on the modeled scenario. Likewise to which extend the jumps of piece-wise continuous outputs -- caused due to recalibration of tuneable parameters -- are acceptable.

And the model may always compensate for tuning effects by combining a recalibration with a `reinit` or tangled `when` clause; but how would you _**automatically**_ conclude if a modeller used these constructs to enable proper tuning?

> In absence of this information, it seems to me that no parameters of Modelica models could be _safely_ be considered as tunable parameters in the derived eFMI, so in the hierarchy constants, tuneable parameters, dependent parameters, inputs outputs and states, they should probably be considered as constants, a priori.
> Of course the "tunability" information is not something that must be necessarily be declared in the Modelica model, it could be declared afterwards in the context of eFMI generation, e.g. as a list of tunable parameters that is supplied alongside the Modelica source code to generate the GALEC code. However, taking the responsibility to supply such declaration requires deep knowledge of the structure and meaning of the model, so that's probably something that is best embedded in a Modelica library when the model is written. Otherwise, whomever compiles the Modelica code into an eFMI later on may not have good enough knowledge to take a correct decision.

This leads to the question of _"what did you do in eFMI to model tuning scenarios in Modelica"_.

First of all, we do not assume any Modelica language extensions. Our test cases library must pass the pedantic checks and be vendor neutral.

SimulationX provides an interactive dialog (stemming from their FMI export) to select the parameters exposed; you can also pick the variability, including if they can be tuned (this is already working to define tuneables for FMI export). And I think you can store your selection by means of SimulationX annotations added to the exported model. Adding vendor specific annotation violates our vendor neutral requirement however. Hence, such annotations are not in the MAP eFMI testcases library -- they could be stored in a separate library. At the end however, SimulationX did anyway not test tuning (they always constant fold all parameters away in their eFMI export).

For Dymola, I wanted to support online recalibration in software-in-the-loop (SiL) tests of eFMUs. Hence, we need a way to select the tuneable parameters for GALEC code generation. I thought forth and back how to best do that with the means we already have in Modelica, and settled with a heuristic that can be easily made explicit in the model. Dymola simply considers all independent (i.e., by means of literal value and constant based expressions) **top-level** parameters of the exported model to be tuneables. If a modeler concludes that tuning such is not safe, he simply makes the respective parameter `final`, which boils down to be constant (btw., I have hard trouble to see any difference between `constant` and `final parameter`). If some nested component's parameters should be tuneable, simply introduce a respective top-level parameter and pass it through (this is how it is done for many, many models anyway -- a very common pattern). If your controller model as is does conflict with this heuristic, then simply extend it and do above explicit modelling of tuneables as they should be in the block-interface of the generated eFMI code; you then just use this extended model for code export and can leave your original model as is. This scheme turned out very well; it fitted for all the models that popped up in the project, including industrial demonstrators, and has been appreciated by users.

The main message is, that we managed to avoid any need to extend the Modelica language _and_ still support a pretty clear way of how to model tuneable parameters for FMI/eFMI export.

This leads to the next question...

# What are the pitfalls of extending Modelica with tuneable parameters

We already have issues with the variability concepts we have. It is not clear why we need constants and `final` parameters, how `Evaluate=true` plays in (can we consider this constant for code export?) _and_ -- my favorite -- that variability can be changed by modification, even for deeply nested components. The latter means for example, that if we have in a model
```
model M
  parameter Real p1 = 3.3;
  parameter Real p2 = 2 * p1;
```
we could conclude that `p1` is independent and `p2` dependent. But now some _"expert"_ comes and does
```
M m(p1 = 2 * p2, p2 = 3.3);
```
which flips variability. That is absolutely deadly for any kind of code export for `M`, since SiL testing of the exported component will break if the export assumed any variability for `p1` and `p2`. But a variability must be assumed, since the whole idea of a code export like in FMI and eFMI is to define a block interface; and tuneable parameters are part of such interface.

Even better are the consequences of optimization thanks to scalarization. Consider for example
```
parameter Real p = 3.3;
final parameter Real pv[] = { 2.2, 2*p };
```
When we scalarize we get
```
parameter Real p = 3.3;
final parameter Real 'pv[1]' = 2.2;
final parameter Real 'pv[2]' = 2*p1;
```
If we now optimize at code generation, we can conclude that `p` is a tuneable parameter, `'pv[1]'` a constant and `'pv[2]'` a dependent parameter. This will utterly break the exported block interface. The block interface must be preserved, hence scalarization undone after optimizing with the knowledge that `'pv[1]'` is constant. We do that in the Dymola GALEC code export, but believe me, it was a lot of hassle.

Adding now some `tuneable` lamguage extension to Modelica will make the shit hit the fan. We first have to clean up what we have -- or do we want that at all?

**Comment by christoff-buerger** [comment]
I edited my above post in the "What are the pitfalls of extending Modelica with tuneable parameters" Section.

I think it provides now some meat to think about :)

**Comment by zwerfl** [comment]
maybe (well - most likely, cause I'm not an expert..) a stupid idea, but why can't you treat tunable parameters just like inputs with an initial value? 
to me it seems Dymola is doing exactly that:
parameter input Real param; 
(referring to: https://openmodelica.org/forum/default-topic/3444-how-to-obtain-a-variability-tunable-parameter-when-exporting-fmu#p11417)

**Comment by christoff-buerger** [comment]
> maybe (well - most likely, cause I'm not an expert..) a stupid idea, but why can't you treat tunable parameters just like inputs with an initial value? to me it seems Dymola is doing exactly that: parameter input Real param; (referring to: https://openmodelica.org/forum/default-topic/3444-how-to-obtain-a-variability-tunable-parameter-when-exporting-fmu#p11417)

Because tuneable parameters are changed occasionally, not all the time. They are semi-constants (something between a constant and an ordinary variable). And as such, they are changed by means of an external event at unknown time points.

The concept can be best understood in the domain of controllers / sampled systems. You _must_ provide inputs at each sampling; but tuneables are changed outside the scope of ordinary sampling. And god forbid you start pulling their value from the external system; it might be undefined at the point when you (the FMU etc) _thinks_ its a good idea to pull some value -- only the external environment knows when to set new tuneables to which value. It is told to you (the FMU etc) when to use which new tuenable values and _then_, and only then, you must adapt respectively before the _next_ computation of outputs for given inputs.

**Comment by casella** [comment]
@christoff-buerger, @eshmoylova thanks for your mini-essays, that I agree with 100%. Maybe what we need to do to clean up the concepts is to first _get clear user requirements and use cases and for parameter variability_, both in Modelica and for eFMI, and make them _explicit_ so we can eventually get consensus on them. Then, based on that, we can try to clean up the MLS and eFMI specifications, if needed. 

The problem that I see currently is that these concepts are subtle and articulate, many people have a partial vision of them (not their fault, that includes myself) and tend to draw conclusions which do not lead to good designs, because they are based on a limited view, rather than on a comprehensive vision. Additionally, users (including myself) have sometimes a tendency to take a shortcut, i.e. to try stuff with one tool and draw conclusions based on what a specific tool does, assuming this has universal validity.

I believe making those requirements explicit would help a lot if we want to do a good job here. Anyone volunteers? We could set up an .md page linked here with PR's to it, much the same way as the Flat Modelica spec was handled.

**Comment by zwerfl** [comment]
@ christoff-buerger
thanks for clarification! haven't thought about that.
nevertheless: from the cited post it seems that Dymola supports tunable parameters (haven't checked, as I don't use Dymola)
Maybe it's possible to evaluate how Dymola is handling tunable parameters?

**Comment by christoff-buerger** [comment]
> @ christoff-buerger thanks for clarification! haven't thought about that. nevertheless: from the cited post it sounds like Dymola supports tunable parameters (haven't checked, as I don't use Dymola) Maybe it's possible to evaluate how Dymola is handling tunable parameters?

I think I already described that roughly in above post, the paragraph starting with _"For Dymola, I wanted to support online recalibration in software-in-the-loop (SiL) tests of eFMUs. "_.

**Comment by christoff-buerger** [comment]
> 

I extended the paragraph a bit to also describe how recalibration tests can be modeled in Modelica using Dymola's modelling approach for eFMI.

**Comment by casella** [comment]
> A `final parameter` can do this, which a `constant` can't:
> 
> ```
> parameter Real p = 1.0;
> final parameter Real q = sin(p);
> ```

What is final is the binding equation, not the value. This is often misunderstood :)
