### ISSUE TITLE
Modelica.Electrical.Batteries.Utilities.BusTranscription does not respect the specification around expandable connectors

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#3147]
In `Modelica.Electrical.Batteries.Utilities.BusTranscription` the connect equation
```
connect(gainLosses.u, stackBus.cellBus.lossPower);
```
fails to respect

> "One connector in the connect equation must reference a declared component, and if the other connector is an undeclared element in a *declared* expandable connector it is handled as follows (*elements that are only potentially present are not seen as declared*)"

as `lossPower` is an undeclared element in *undeclared* expandable connector `cellBus`

This relates to #428 and #2172

**Comment by HansOlsson** [comment]
For #2172 the main issue was lack of realistic examples, and it now seems we have them.
In particular the array declaration of cellBus is good since it illustrates why following are good ideas:

- Requiring that it is potentially present; as we otherwise wouldn't know if it should be an array of lossPower (as in stackBusArrays) or array of cellBus (as in stackBus).
- Should be able to connect to it when only potentially present.
- Have the feature at all since otherwise we would need a free-floating stack-bus-array-declaration in the model, which seems odd.

**Comment by HansOlsson** [comment]
Proposed new text:

> At least one connector in the connect equation must reference a declared or potentially present component.
> If potentially present component it will be marked as being present (recursively if needed).
> If the other connector is not even potentially present it must be an undeclared element in a at least potentially present expandable connector and it is handled as follows (after marking the potentially present expandable connector as present):

Non-normative:
The undeclared component in 'potentially present expandable connector' makes it possible to have a 'potentially present _array of_ expandable connectors'.
(Add example.)

Poll:
- Thumb up if in favor
- Thumb down if against
- Eyes if we need to discuss it more.

**Comment by qlambert-pro** [comment]
I don't understand the wording. Can you explain what your text is trying to do that specifying that potentially present component are considered declared does not?

**Comment by HansOlsson** [comment]
However, an alternative might be the following:

1. If a connect-statement references a potentially present component (either as the complete argument or as part of the argument) it will be marked as being present and will be treated as declared below.
2. After that at least one connector in the connect equation must reference a declared component.
3. If the other connector is not potentially present it must be in a declared component and is handled as follows:

So for:
`connect(gainLosses.u, stackBus.cellBus.lossPower);`
`stackBus.cellBus` is potentially present and is by 1 transformed into declared
Then `gainLosses.u` is declared (assuming lossPower isn't), so 2 is ok.
And then since lossPower isn't declared we continue with 3.

But we still have the benefit that if we just drag in an expandable connector and don't connect it we avoid all of the issues, both the problem above for physical connectors, and also the lack of source for a causal one.

**Comment by qlambert-pro** [comment]
I prefer this alternative but I don't understand the purpose of `3.`. There are no potentially present connector then, since `1.` made them into declared component. To me `3.` sounds like it forbids adding an undeclared signal to an expandable connector. Unless what you mean is:
> If the other connector is undeclared if must be a connector inside a declared expandable connector.

**Comment by HansOlsson** [comment]
> I prefer this alternative but I don't understand the purpose of `3.`. There are no potentially present connector then, since `1.` made them into declared component. To me `3.` sounds like it forbids adding an undeclared signal to an expandable connector. Unless what you mean is:
> 
> > If the other connector is undeclared it must be a connector inside a declared expandable connector.

Yes, that was the idea - I wrote 'not potentially present' intending to mean 'not _even_ potentially present'; but you are right that undeclared is clearer.
