### ISSUE TITLE
What is the intended behavior of defaultComponentName?

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3151]
What is the intended behavior for the annotation `defaultComponentName`? In particular, what is the expected first and second name when creating 2 components of this class?
```
model MyLongModelName
  annotation(defaultComponentName = "shortname1");
end MyLongModelName;
```
When answering, one example to keep in mind could be [cases in the standard library](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Blocks/Logical.mo#L10).

My personal expectation is `shortname1` and `shortname2`

**Comment by HansOlsson** [comment]
I have the same expectation.

However, as far as I understand the numbering of components isn't specified - clearly you cannot have two components with the same name (in the same model) and I would expect most tools to use a numbering system to avoid that.

**Comment by HansOlsson** [comment]
I don't think we need to over-specify this, especially as you normally change the name anyway, but simply: 

If the default name cannot be used (e.g., since it is already in use) another name can be used automatically, a recommended way is to add a the lowest strictly positive integer suffix giving a usable name - after removing any possible trailing "1" from the default name.
However, see also below under `defaultComponentPrefixes`.

(Note 'strictly positive' is a bit unnecessary, we could write 'positive'; but since there are conflicting definitions of positive it seems safer.)
I don't think we need to consider ensuring that libraries using `defaultComponentName = "shortname001"` might look odd when developed using multiple tools (the models should run the same, it's just the default naming that might seem off).

**Comment by eshmoylova** [comment]
I checked various examples and how they are treated in MapleSim. In general, if we have `defaultComponentName = "A"` the names that components get would be `A1` for the first one, then `A2`, etc. If we have defined `A1`, `A2`, and `A3` and then delete `A2`. The next inserted one would be `A2`. If the name ends in a number (any number) , e.g. `defaultComponentName = "a1"`, the components would be named `a1_1`, `a1_2`, ....

This is modified if the component has `defaultComponentPrefixes = "inner"`. Then for the first component the name would be used as given. For the second component,  if  the name does not end in a number (as for `A` above), it would be `A2`.  If the name ends in a number ("a1"), the first one would be `a1`, the second would be `a2`.

**Comment by HansOlsson** [comment]
That sounds a bit odd, but I don't see that it is a major issue.

Could reformulate the previous to just indicate that it is one possibility.

If the default name cannot be used (e.g., since it is already in use) another name can be used automatically.
One way is to append the lowest strictly positive integer suffix giving a usable name - after removing any potential trailing "1" from the default name.
However, see also below under defaultComponentPrefixes.

**Comment by henrikt-ma** [comment]
I think this was closed in a rush and needs more consensus before adding text that may not improve anything.

First, I note that the added text describes a different strategy than that taken by MapleSim.  Hence we shouldn't add such text without any input on the proposed changes from Maple (@eshmoylova).

Second, as long as there isn't one clear interpretation of what the "1" at the end of a `defaultComponentName` means, I don't think there's anything normative to be said about it.

Third, there wasn't even enough time to spot typos, so now I'll begin by setting up a new PR just to fix the typo.
