### ISSUE TITLE
support for directorySelector

### ISSUE THREAD

**Issue by GarronFish** [modelica/ModelicaSpecification#3187]
In Dymola there is a custom dialog annotation, Dialog.__Dymola_directorySelector which allows the user to select a directory.  There does not appear to be an equivalent in the Modelica Specification, or at least I could not figure out how to use loadSelector to do the same thing.

This is a useful feature could it be added?

**Comment by HansOlsson** [comment]
Specifically directorySelector could be specified along these lines:

Selector directorySelector;
...
A component shall have at most one of showStartAttribute=true, colorSelector=true, loadSelector, saveSelector, directorySelector or connectorSizing=true.
...
The presence of directorySelector specifying Selector suggests the use of a file dialog to select an existing directory. caption is a caption for display in the file dialog, and filter is ignored.

**Points to consider**
Short version: We can change the presentation. For the design I have considered a number of options but I don't see a need to change it.

Longer:
- State that filter is ignored, or have another record without it? (Filters for directory names don't make much sense and is normally unsupported - although I'm sure someone have implemented it somewhere.)
- Only one for selector and the directory must exist when returning. I believe that is the most available and supported - and have considered a number of options:
  - For comparison files have load and save as two separate ones. The assumption is that load must exist and save will warn if it exists. The reason is that the dialogs for selecting directories normally only allow you to return existing directories (sometimes obvious from the name https://doc.qt.io/qt-5/qfiledialog.html#getExistingDirectory ) but the returned directories can be read, written, and modified.
  - Some directory selectors have a slightly different read/write restriction possibility ( https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog )  can prohibit the creation of new directories. All dialogs don't have that, and users can anyway create a new directory in a file-browser while the dialog is active so I don't see it as needed functionality. The caption can also clarify this - "Select Export Directory" vs "Select Import Directory".
  - A different functionality would be whether the directory is "writeable" or not; having a read-only "Export Directory" doesn't make sense - it's just that captions help here as well, and it's messy to get that information in general (ACLs are complicated) and the simplest possibility is often to try to write and see if it works. And directory selectors don't seem to offer it in general.
- It returns a directory in the file-system, a more general variant would be an URL. If we want to add URLs we should start with the loadSelector.
