### ISSUE TITLE
Relax rules for declaration equations in external functions

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3188]
The rules for making use of results computed by an external function seem overly restrictive.  For the discussion, assume we have a function which increments its argument in-place:
```
void
inc(int* z)
{
  ++(*z);
}
```

Example of currently valid use:
```
function inc
  input Integer x;
  output Integer y = x;
external "C"
  inc(y);
end inc;
```

I find it strange that we don't allow the same to be expressed with the use of a protected variable:
```
function inc
  input Integer x;
  output Integer y = z;
protected
  Integer z = x;
external "C"
  inc(z);
end inc;
```

As protected variables are passed in the same way as output variables, I would find it more natural to also make it possible to make use of results returned in the protected variables, as shown above.  To make it work one would need to remove the part marked in bold here:
> A binding equation for a non-input component initializes the component to this \lstinline!expression! at the start of every function invocation (before executing the algorithm section **or calling the external function**). These bindings must be executed in an order where a variable is not used before its binding equations has been executed; it is an error if no such order exists (i.e.\ the binding must be acyclic).

and instead have the following restrictions on declaration equations in an external function:
- A non-input variable passed in the external function call must be initialized before the external function is called.
- A non-input variable passed or returned in the external function call cannot be used until after the external function has returned.

The result is that an external function is sorted like any other function without an algorithm, but with the additional requirements that some non-input variables' declaration equations need to go before the external function call, and some need to go after.

Edit: Removed pointless example at the end of the comment.

**Comment by HansOlsson** [comment]
> and instead have the following restrictions on declaration equations in an external function:
> 
> * A non-input variable passed in the external function call must be initialized before the external function is called.

That would break a large number of existing uses, e.g. Modelica.Math.Matrices.LAPACK.dgeev where work isn't initialized (whereas Awork is initialized to A).
Basically non-inputs are often used as work-areas and thus sending them in non-initialized is perfectly fine.

> * A non-input variable passed or returned in the external function call cannot be used until after the external function has returned.

There exists a good work-around for this: have a wrapper function calling the external function - similarly as Modelica.Math.Matrices.eigenValues calls the eigen-value function and assert that it works.

> The result is that an external function is sorted like any other function without an algorithm, but with the additional requirements that some non-input variables' declaration equations need to go before the external function call, and some need to go after.

Apart from breaking the natural flow (you have to mentally re-sort declarations together with the external call) it fails to handle a common existing use case as shown in Modelica.Math.Matrices.eigenValues; the need to assert that the result was ok (other wrappers show that asserting before calling the function is also useful, as well as more).

I'm fully aware that existing bindings also can be re-sorted which also breaks the natural flow, but in general I (and many others) tend to avoid it - keeping that natural flow.
We don't have that as a strict rule since:
- It would often just be one of those things where a compiler could handle it in a well-defined manner (as currently defined), but is forced to generate an error message. As a user you then just feel that the compiler is out to annoy you, not help you.
- In case of bindings for record members you might not be able to fix it locally, and if you try to change the record it becomes a mess.

**Comment by henrikt-ma** [comment]
> > * A non-input variable passed in the external function call must be initialized before the external function is called.
> 
> That would break a large number of existing uses, e.g. Modelica.Math.Matrices.LAPACK.dgeev where work isn't initialized (whereas Awork is initialized to A). Basically non-inputs are often used as work-areas and thus sending them in non-initialized is perfectly fine.

No, as this is a restriction that applies for *declaration equations in an external function*.  That is, it doesn't say anything about protected variables without declaration equation, and the proposal in this issue is not intended to remove the possibility of passing uninitialized working memory.  However, the fact that one can pass uninitialized memory to an external function is probably worth documenting regardless of the present proposal.

**Comment by henrikt-ma** [comment]
> Apart from breaking the natural flow (you have to mentally re-sort declarations together with the external call) it fails to handle a common existing use case as shown in Modelica.Math.Matrices.eigenValues; the need to assert that the result was ok (other wrappers show that asserting before calling the function is also useful, as well as more).

To me this sounds as just another possible extension of external functions that I think should be handled completely orthogonal to the current proposal: allow external function wrappers to contain asserts in addition to the external function call:
```
function dgeev_eigenValues "Compute eigenvalues for real nonsymmetric matrix A"
  extends Modelica.Icons.Function;
  input Real A[:, size(A, 1)];
  output Real EigenReal[size(A, 1)];
  output Real EigenImag[size(A, 1)];
protected
  Integer n = size(A, 1);
  Integer lwork = 8 * n;
  Real Awork[size(A, 1), size(A, 1)] = A;
  Real work[8 * size(A, 1)];
  Real EigenvectorsL[size(A, 1), size(A, 1)] = zeros(size(A, 1), size(A, 1));
  Integer info; /* No declaration equation, will be passed uninitialized. */
external "FORTRAN 77"
  dgeev("N", "N", n, Awork, n, EigenReal, EigenImag, EigenvectorsL, n, EigenvectorsL, n, work, lwork, info)
    annotation(Library = "lapack");
  assert(info == 0, "Calculating the eigen values with function \"Matrices.eigenvalues\"…");
end dgeev_eigenValues;
```

To make it work, one would need to add dependency rules so that it is clear when the assert can be evaluated.  I think it would be sufficient to say that – in addition to being dependent on any declaration equations for variables appearing in the assert – the assert is dependent on the external function call whenever a non-input variable in the assert is present in the external function call.  To make the mechanism really useful, it should be required that all asserts that can be evaluated before the external function call must be evaluated before the call.  A limitation of the mechanism would be that one cannot express that an assert involving a non-input present in the external function call should be evaluated before the external function call, but I think this would be easy to work around by the introduction of additional protected variables.

**Comment by HansOlsson** [comment]
> > > * A non-input variable passed in the external function call must be initialized before the external function is called.
> > 
> > 
> > That would break a large number of existing uses, e.g. Modelica.Math.Matrices.LAPACK.dgeev where work isn't initialized (whereas Awork is initialized to A). Basically non-inputs are often used as work-areas and thus sending them in non-initialized is perfectly fine.
> 
> No, as this is a restriction that applies for _declaration equations in an external function_. 

So, declaration equations _if present_ are done before the external function call for non-inputs?
Having a wrapper is just a cleaner existing solution; and I don't see this proposal going anywhere.

The following:
```
function inc
  input Integer x;
  output Integer y = x;
external "C"
  inc(y);
end inc;
```
Does in pseudo-C-code:
```
y=x;
inc(&y);
```
The proposed other variant:
```
function inc
  input Integer x;
  output Integer y = z;
protected
  Integer z = x;
external "C"
  inc(z);
end inc;
```
Would seem to require the following in pseudo-C-code:
```
z=x;
inc(&z);
y=z;
```
That is not good since:
- It is non-intuitive for users as is mixes sorting and code modifying variables.
- It doesn't gain us anything not already handled by wrappers.
- It introduces new failure modes, e.g., if y was an argument to the external function.

I simply don't see this proposal going anywhere.

**Comment by henrikt-ma** [comment]
If nothing else, the discussion above can be seen as a collection of the reasons for _not_ allowing the use of protected variables after the external function call.  Based on this, I think it should be possible to write a better description of what really is the role of protected variables in external functions.  For example stating something like the following would make it clear that one really shouldn't expect something like what is proposed above:
> Protected components can be passed to the external function without being initialized by means of a declaration equation, which is useful for passing workspace memory to functions with FORTRAN style memory management, and the reason for passing them in the same (writable) way as output components.  The value of a protected component passed to the external function should be considered undefined (destroyed) after the external function call.
