### ISSUE TITLE
Clarify purpose of smoothOrder

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3200]
When I read the definition of `smoothOrder`, it looks like a mechanism that allows a function call to be automatically augmented with a `smooth(…)` wrapper.  The non-normative explanation, on the other hand, presents the annotation as something a tool can use to determine when to expect that a function can be "analytically" differentiated.  I'm not sure about the precise meaning of _analytically_ here, but I often hear `smoothOrder` being described as a mechanism for instructing the tool to automatically construct a function derivative.

What I find strange is no specification of `smoothOrder` can be used to tell tools to _not_ try to automatically differentiate the function.  After all, even a C^0 function could have a (discontinuous) derivative that a tool could construct automatically.

For example:
```
function absPlus1
  input Real x;
  output Real y = abs(x) + 1;
  annotation(Inline = false, smoothOrder = 0);
end absPlus1;
```
has the maximum possible `smoothOrder`, and it would be meaningful to automatically construct the discontinuous derivative function.

From the above, to concrete questions emerge:
- Shouldn't the non-normative description of `smoothOrder` be changed to not give the impression that it has to do with automatic construction of derivative functions, and instead describe a relation to `smooth(…)`?
- Wouldn't it be nice to have a mechanism for specifying an upper bound on the number of automatically constructed derivative functions?

**Comment by henrikt-ma** [comment]
See also #686, where there was also a suggestion to have a mechanism for describing some sort of upper bound on differentiation.  That time, the resolution was to keep the definition of `smoothOrder` close to the mathematical concept of smoothness, but maybe the underlying confusion behind the issue could be the same as described here; namely that what we need most is not an annotation for mathematical smoothness, but an annotation that gives the _maximum_ order of automatically generated derivative functions…

**Comment by henrikt-ma** [comment]
Am I naive to think this this is generally considered an acceptable Modelica model?
```
model DiscontinuousDerivative
  Real x(start = 2.0, fixed = true);
  Real y(start = 2.5, fixed = false);
equation
  abs(x - y) = 1;
  der(x) + der(y) = 1.0;
  annotation(experiment(StopTime = 5.0));
end DiscontinuousDerivative;
```

I mean, index reduction of this to implicit ODE form depends upon differentiation of `abs`, which isn't `smoothOrder = 1`…

**Comment by casella** [comment]
@henrikt-ma, my previous comment was incomplete. As I understand, these are the possible scenarios, that are valid both for `smooth()` in expressions and `smoothOrder` in function declarations.

**Regarding event handling (possibly discontinuous expressions on the RHS of the ODEs)**

If expressions/functions are discontinuous, in order to keep the declared accuracy of the integration method with error control, you need to generate an event at the discontinuity, integrate until there, switch the expression, and then restart the integration.
```modelica
model ME
  Real x;
equation
  der(x) = if x > 0.5 then 10*(1-x) else (1-x);
end ME;
```
If expressions/functions have `smoothOrder = 0` you may skip event-handling (i.e. implicitly add `noEvent()`), though error estimators of order greater than 1 won't be correct. Ideally, you should use a first-order method when doing the time step that contains the event time, but I guess most tools don't care about that.
```modelica
model ME0
  Real x;
equation
  der(x) = smooth(0, if x > 0.5 then 10*(1-x) else 10*(1-x) + (0.5 - x));
end ME0;
```
If expressions/functions have `smoothOrder = n > 0`, you may skip event-handling (i.e. implicitly add `noEvent()`), though error estimators of order greater than n won't be correct. Ideally, you should use an n-th order method when doing the time step that contains the event time
```modelica
model MEn
  parameter Integer n(min = 1);
  Real x;
equation
  der(x) = smooth(n, if x > 0.5 then 10*(1-x) else 10*(1-x)+(0.5-x)^(n+1));
end MEn;
```
**Regarding index reduction (potentially discontinuous expressions/functions in state variable constraints to be differentiated**

If expressions/functions that are differentiated for index reduction are discontinuous, then the model is invalid as soon as the discontinuity is crossed
```modelica
model MIR
  Real M(stateSelect = StateSelect.never);
  Real x(stateSelect = StateSelect.always, start = 0, fixed = true);
equation
  // The value of M will be wrong as soon as x crosses 1, but will be ok otherwise
  M = if x < 1 then x else x-1;
  der(M) = 1;
end MIR;
```
If potentially discontinuous expressions/functions that are differentiated for index reduction have `smoothOrder = 0`, then the model is correct, but it is necessary to generate an event at the discontinuity for accuracy
```modelica
model MIR0
  Real M(stateSelect = StateSelect.never);
  Real x(stateSelect = StateSelect.always, start = 0, fixed = true);
equation
  // an event should be generated when x >= 1
  M = smooth(0, if x < 1 then x else x + (x - 1));
  der(M) = 1;
end MIR0;
```
If potentially discontinuous expressions/functions that are differentiated for index reduction have `smoothOrder = n > 0`, then the model is correct, though error estimators of order greater than n-1 will be wrong

```modelica
model MIRn
  Real M(stateSelect = StateSelect.never);
  Real x(stateSelect = StateSelect.always, start = 0, fixed = true);
  parameter Integer n(min = 1);
equation
  M = smooth(n, if x < 1 then x else x + (x - 1)^(n+1));
  der(M) = 1;
end MIRn;
```
Adding @bernhardbachmann, @kabdelhak, @AnHeuermann, @phannebohm to the loop.

**Comment by HansOlsson** [comment]
Just some general comments:
* Restricting the maximum differentiation order does not make sense, as many functions can "collapse" for certain arguments and get higher differentiation order.
* As Francesco notes the real issue is when differentiating something that is discontinuous; so  `x-y = 1+(if time>=1 then 1 else 0);` would clearly be an error.
* As Francesco implicitly notes smooth and smoothOrder are connected; and smooth is also connected to events. So, both smooth and smoothOrder ensure that the expression/functions is continuously differentiable and can be differentiated - assuming the "inputs" are smooth.

The connection to smooth is that smooth only implies that it is smooth if events are ignored. If you generate events you will switch from one branch to the other with some "event epsilon", and that makes it not smooth (unless both branches have the same value - so why have an if at all?).

Thus I don't see what purpose needs to be clarified.

**Comment by HansOlsson** [comment]
> Just some general comments:
> 
> * Restricting the maximum differentiation order does not make sense, as many functions can "collapse" for certain arguments and get higher differentiation order.
> * As Francesco notes the real issue is when differentiating something that is discontinuous; so  `x-y = 1+(if time>=1 then 1 else 0);` would clearly be an error (added: when combined with the other equations with `der(x)` and `der(y)`).
> * As Francesco implicitly notes smooth and smoothOrder are connected; and smooth is also connected to events. So, both smooth and smoothOrder ensure that the expression/functions is continuously differentiable and can be differentiated - assuming the "inputs" are smooth.
> 
> The connection to smooth is that smooth only implies that it is smooth if events are ignored. If you generate events you will switch from one branch to the other with some "event epsilon", and that makes it not smooth (unless both branches have the same value - so why have an `if `at all?).
> 
> Thus I don't see what purpose needs to be clarified.

**Comment by henrikt-ma** [comment]
This is the part I'm concerned about:
> If a tool needs the derivative of a function, e.g. for index reduction or to compute an analytic Jacobian, the function can be differentiated analytically at least `smoothOrder` times.

Isn't the essence of the comments above that what should really be emphasized is the following?
> When a tool computes the derivative of a function, e.g. for index reduction or to compute an analytic Jacobian, each differentiation of a function reduces the `smoothOrder` by 1.  The `smoothOrder` information can then be used to infer continuity of the resulting differentiated function calls.  This is a conservative check, however, meaning that a tool may be able to establish continuity of a function call even though the `smoothOrder` has been reduced to less than 0.

**Comment by henrikt-ma** [comment]
One of the things I'm trying to improve is to avoid the misinterpretation of `smoothOrder` as a way of requesting that the tool provide automatically generated function derivatives, as an alternative to explicitly providing derivatives with the `derivative` annotation.  That is, while the tool can relatively easily work out the shape of derivative functions, it needs the additional smoothness information in order to know when those functions are are meaningful derivatives.

I suppose it wouldn't hurt to point out that a tool could also automatically infer smoothness information by investigating a function body?

As I understand it, `smoothOrder` could also be useful in combination with `derivative`, as in the following example:
```
model ContinuousDerivative
  function f
    input Real x;
    output Real y = abs(x) * x;
    annotation(derivative = f_der);
  end f;

  function f_der
    input Real x;
    input Real x_der;
    output Real y_der = sign(x) * x_der * x + abs(x) * x_der;
    annotation(smoothOrder = 0); /* This is information that a tool may not be able to automatically infer. */
  end f_der;

  Real x(start = 1.0, fixed = true);
  Real y(start = 2.0, fixed = false);
  Real vx;
  Real vy;
equation
  vx = der(x);
  vy = der(y);
  der(vx) + der(vy) = 1;
  f(x - y) = 1;
  annotation(experiment(StopTime = 5));
end ContinuousDerivative;
```

However, I guess it is more common to provide a second order derivative (and providing a second order derivative implies that the first order derivative must be continuous).

**Comment by HansOlsson** [comment]
> I suppose it wouldn't hurt to point out that a tool could also automatically infer smoothness information by investigating a function body?

We could, but the problem is that it is not guaranteed that all tools reach the same conclusion - as we haven't standardized how tools shall do this. Thus if a user want to be to write tool-agnostic code using smoothOrder is better.

Obviously if a tool can figure out that a function is continuously differentiable it could (suggest to) automatically augment the function definition with that information.

> As I understand it, `smoothOrder` could also be useful in combination with `derivative`, as in the following example:
> 
> ```
> model ContinuousDerivative
>   function f
>     input Real x;
>     output Real y = abs(x) * x;
>     annotation(derivative = f_der);
>   end f;
> 
>   function f_der
>     input Real x;
>     input Real x_der;
>     output Real y_der = sign(x) * x_der * x + abs(x) * x_der;
>     annotation(smoothOrder = 0); /* This is information that a tool may not be able to automatically infer. */
>   end f_der;

If tools can infer that functions are smooth based on the body, I would expect them to handle cases like this.

**Comment by henrikt-ma** [comment]
> If tools can infer that functions are smooth based on the body, I would expect them to handle cases like this.

The purpose of the example was just to pick something that wasn't entirely trivial.  I imagine that a minimal implementation of smoothness detection wouldn't perform any sort of simplification, and therefore stop as soon as it encounters `sign(x)` and conservatively treat the function as possibly discontinuous.

**Comment by henrikt-ma** [comment]
> If expressions/functions are discontinuous, in order to keep the declared accuracy of the integration method with error control, you need to generate an event at the discontinuity, integrate until there, switch the expression, and then restart the integration.

Right, and as Modelica has designed `sign(x)` to not generate events, I thought that there was a rather that in the design of Modelica, adequate error control has been sacrificed for speed.

> If expressions/functions have `smoothOrder = n > 0`, you may skip event-handling (i.e. implicitly add `noEvent()`), though error estimators of order greater than n won't be correct. Ideally, you should use an n-th order method when doing the time step that contains the event time

On the same theme as `sign(x)`, wouldn't such an approach defeat Modelica's design decision to not generate events for `max(x, y)` (or `abs(x)`)?  I mean, to know when to reduce the order, you would need to have some sort of zero crossing function for `x - y`.  While it wouldn't be necessary to exactly locate the time of the zero crossing, it would probably be desirable to at least reduce the step around the crossing so that one doesn't take a very long step using a low order method.

**Comment by henrikt-ma** [comment]
In view of `abs(x)` and `sign(x)` not generating events, perhaps the non-normative text for `smoothOrder` should also point out that `smoothOrder = 0` allows a tool to automatically create a – possibly discontinuous – function derivative?

**Comment by HansOlsson** [comment]
> > If expressions/functions are discontinuous, in order to keep the declared accuracy of the integration method with error control, you need to generate an event at the discontinuity, integrate until there, switch the expression, and then restart the integration.
> 
> Right, and as Modelica has designed `sign(x)` to not generate events, I thought that there was rather clear that in the design of Modelica, adequate error control has been sacrificed for speed.

Not really; it was a necessary sacrifice to reduce errors. 

Originally `sign(x)` (and abs) was designed to generate events.
But it turned out that it introduced problems, and didn't really correct any so it was changed (I believe at the 50th design meeting in Vienna 2006-09-08).

A typical example was in fact `abs(x)*x=y;` - which appear in fluid models. Consider solving for x when y passes through zero. The idea with events and crossing functions was ensure smooth-ness during continuous integration - but here the result is instead an equation that cannot be solved.

Such problematic cases for abs are so common that the automatic event generation causes more problem than they solve.

**Comment by henrikt-ma** [comment]
> Such problematic cases for abs are so common that the automatic event generation causes more problem than they solve.

Sounds like a great rationale to include non-normatively in the specification!

**Comment by casella** [comment]
> One of the things I'm trying to improve is to avoid the misinterpretation of `smoothOrder` as a way of requesting that the tool provide automatically generated function derivatives, as an alternative to explicitly providing derivatives with the `derivative` annotation.

@henrikt-ma I'm not sure why you'd consider it as a misinterpretation. If the function has potential discontinuities, it does not provide derivative annotations, and has a smoothOrder annotation, and if it is necessary to differentiate it because of index reduction, the only way to simulate the model is precisely that the tool automatically differentiates the function body, and trusts the validity of the annotation regarding potential discontinuities. If the library developer does not provide the derivative annotation, there is no other choice.

On the other hand, if one provides the derivative annotation, it is pretty obvious to me that this means the function can actually be differentiated. Of course it is the responsibility of the library developer to make sure it actually is (and that the provided derivative functions are actually correct).

Do I miss something?

> I suppose it wouldn't hurt to point out that a tool could also automatically infer smoothness information by investigating a function body?

I think there are no rules explicitly forbidding that, so this looks a bit to me as "excusatio non petita".
 
> As I understand it, `smoothOrder` could also be useful in combination with `derivative`

True, but you are using the `smoothOrder` and the `derivative` annotations on two different functions, `f` and `f_der`. I think it doesn't make much sense to use both on the same function.
