### ISSUE TITLE
Use of "connect-equation", "connection equation", and "connect-clause" should be streamlined

### ISSUE THREAD

**Issue by gwr69** [modelica/ModelicaSpecification#3273]
I find it slightly confusing, that the specs mix the terms _**connect-equation**_, _**connection equation**_, and _**connect-clause**_. ~I would suggest to exclusively use _**connect-equation**_, unless I am missing a syntactic difference.~

~While~ the _**connect-clause**_ is simply a _**connect-equation**_ without the trailing ";" (cf. section 9.1 and appendix A.2.6) ~it could imho be renamed to _**connect-equation**_ following the use of _if-equation_ or _when-equation_ as to make the specs clearer?~

EDIT:
As a minimal clarification, it may help to change the last item in the list at the end of section 9.1 (changes bold):

>The three main tasks are to:
>- Elaborate expandable connectors.
>- Build connection sets from `connect`-equations.
>- Generate equations for the complete model (_**connection equations**_).

EDIT2:
I just noted that the specs indeed make the above clarification on page 8 in section 1.2:

>- Generation of connection equations from connect-equations

So my proposed addition for section 9.1 above would indeed simply be a repetition, albeit a clarifying one. 

My underdeveloped sense for technical specification language requirements is likely to blame for finding `connect-equations` as a means to generate `connection equations` slightly unfortunate. Having `connect-clauses` do the same would sound niceṛ (at least to my ears) possibly without too much loss of precision? :)

**Comment by henrikt-ma** [comment]
> So my proposed addition for section 9.1 above would indeed simply be a repetition, albeit a clarifying one.

It's a good suggestion.  I'll turn it in to a PR, and we can continue the discussion there if needed.

> My underdeveloped sense for technical specification language requirements is likely to blame for finding `connect-equations` as a means to generate `connection equations` slightly unfortunate. Having `connect-clauses` do the same would sound niceṛ (at least to my ears) possibly without too much loss of precision? :)

My intuition about how we use _clause_ is that it is used when other terms are too precise.  For example, a `when`-clause is something which has to do with `when`-equations as well as `when`-statements (whether it's the entire `when`-equation/statement or just a part of it, I'm not sure).  I'd like to keep using the more precise term `connect`-equation here, since it helps reminding readers that some constructs come in both an equation and a statement variant, while others only come in one of the forms.
