### ISSUE TITLE
Flipping asymmetrical instances on diagram layer ends up in corrupted connection lines in different modelica tool

### ISSUE THREAD

**Issue by sbaetzing** [modelica/ModelicaSpecification#3275]
Bosch Rexroth AG as library developer noticed the following.

The flipping of component instances is not clearly defined in the specification (chapter 18.6.2 "Component Instance").
The tools interpret the execution of the flip differently. Some tools exchange e.g. with the vertical flip x1 and x2 coordinate (exclusively in the extends annotation). 
In others, the icon is defined via origin and extends. If you then swap the x1 and x2 coordinates there, the location of the component shifts in the diagram layer itself, since the origin is kept.

The different interpretations have the consequence that models which were developed in a tool "A" have shifted connection lines (annotation of the connections are not correct) when opening in tool "B" as well as misplaced components. 
This especially happens to asymmetrical icons regarding the center 0/0.

It would be good to clarify what flip means in the Modelica context.

I will append screenshots of the different behavior in a moment

Best regards
 
Sven Bätzing

**Comment by sbaetzing** [comment]
![2022-11-07_13h46_53](https://user-images.githubusercontent.com/84787397/200315758-743d64f5-d1d2-40f2-843d-6534cbd50b59.png)
![2022-11-07_13h47_57](https://user-images.githubusercontent.com/84787397/200315764-258be0b6-f2ad-4740-8c80-7ee004aeeac9.png)
![2022-11-07_13h48_15](https://user-images.githubusercontent.com/84787397/200315766-c51bb39e-ebda-4d3b-aacc-afaf3be01adf.png)
![2022-11-07_13h39_53](https://user-images.githubusercontent.com/84787397/200315767-32fd2dab-25a9-46b0-883b-75582a8adc22.png)
![2022-11-07_13h41_31](https://user-images.githubusercontent.com/84787397/200315769-3e65edce-9a46-4589-9f4d-3dfa9bbca02a.png)

**Comment by sbaetzing** [comment]
`within ;
package FlipDefinition1
  model MyClass

    Modelica.Blocks.Interfaces.RealInput u annotation (Placement(transformation(extent={{-222,38},{-182,78}}), iconTransformation(extent={{-140,-20},{-100,20}})));
    Modelica.Blocks.Interfaces.RealOutput y annotation (Placement(transformation(extent={{-214,52},{-194,72}}), iconTransformation(extent={{240,-10},{260,10}})));
    annotation (Diagram(coordinateSystem(extent={{-100,-40},{240,220}})),  Icon(coordinateSystem(extent={{-100,-40},{240,220}}),  graphics={
          Rectangle(lineColor = {28, 108, 200}, fillColor = {0, 140, 72}, fillPattern = FillPattern.Solid, extent={{-100,220},{240,-40}}),
          Text(textColor = {255, 255, 255}, extent = {{-94, 16}, {-50, -18}}, textString = "Left"),
          Text(textColor = {255, 255, 255}, extent={{158,14},{218,-18}},     textString = "Right")}));
  end MyClass;

  model test

    FlipDefinition1.MyClass myClass annotation (Placement(transformation(extent={{-74,20},{-20,62}})));
    MyClass myClass1 annotation (Placement(transformation(extent={{74,20},{20,62}})));
    MyClass myClass2 annotation (Placement(transformation(extent={{-74,-20},{-20,-62}})));
    MyClass myClass3 annotation (Placement(transformation(extent={{74,-20},{20,-62}})));
  equation
    connect(myClass.u, myClass2.u) annotation (Line(points={{-77.1765,26.4615},{-84,26.4615},{-84,-26.4615},{-77.1765,-26.4615}},
                                                                                                              color={0,0,127}));
    connect(myClass.y, myClass1.u) annotation (Line(points={{-18.4118,26.4615},{12,26.4615},{12,16},{84,16},{84,26.4615},{77.1765,26.4615}},
                                                                                                                         color={0,0,127}));
    connect(myClass2.y, myClass3.u) annotation (Line(points={{-18.4118,-26.4615},{12,-26.4615},{12,-16},{84,-16},{84,-26.4615},{77.1765,-26.4615}},
                                                                                                                              color={0,0,127}));
    annotation (Diagram(graphics={Text(
            extent={{-130,-22},{-96,-32}},
            textColor={0,0,0},
            textString="Flipped Hori"), Text(
            extent={{28,68},{62,58}},
            textColor={0,0,0},
            textString="Flipped Verti")}));
  end test;
annotation (uses(Modelica(version="4.0.0")));
end FlipDefinition1;`

**Comment by HansOlsson** [comment]
I would propose that we should remove the _normative_ discussion of flipping that is a left-from from the pre-3 annotations where there was a separate `flipHorizontal` and `flipVertical` attribute.

Instead, `extent` should be defined as a mapping of coordinates (followed by the rotation - so instead of size, flipping, and then rotation we have mapping, then rotation) - and we should only have a non-normative statement that `x2 < x1` _implies_ a flipping.

**Comment by henrikt-ma** [comment]
I think normatively saying that `x2 < x1` means flipping could be an easy way to avoid the need to ensure that the general description of the mapping cannot be understood any other way.

**Comment by HansOlsson** [comment]
> I think normatively saying that `x2 < x1` means flipping could be an easy way to avoid the need to ensure that the general description of the mapping cannot be understood any other way.

If the mapping is defined in a good way that shouldn't be necessary.
(Note that "The graphical operations are applied in the order: scaling, flipping and rotation" should be removed.)

Proposal 1:
The extent together with the origin defines the mapping of the coordinate system of the component, so that a point (x, y) is mapped to `origin+{extent.x1,extent.y1}+{(extent.x2-extent1.x1)*(x-coord.x1)/(coord.x2-coord.x1), (extent.y2-extent1.y1)*(y-coord.y1)/(coord.y2-coord.y1)}`.
The rotation around origin is applied after this mapping.
Non-normatively: If `extent.x2 < extent.x1` this implies that the component is horizontally flipped.

Proposal 2:
The transformation defines the mapping of the coordinate system of the component, so that a point (x, y) is mapped to `origin+[cos(r),-sin(r);sin(r),cos(r)]*{extent.x1+(extent.x2-extent1.x1)*(x-coord.x1)/(coord.x2-coord.x1), extent.y1+(extent.y2-extent1.y1)*(y-coord.y1)/(coord.y2-coord.y1)}`.
Note that this assumes that the rotation is converted from degrees to radians. 
Non-normatively: If `extent.x2 < extent.x1` this implies that the component is horizontally flipped.

**Comment by henrikt-ma** [comment]
Proposal 3 (same non-normative as above):
> The `extent` defines an affine transformation of the coordinate system, acting independently on the _x_ and _y_ coordinates, and such that `coordinateSystem.extent[1]` is mapped to `extent[1]` and `coordinateSystem.extent[2]` is mapped to `extent[2]` (where `coordinateSystem.extent` refers to the `Icon`-annotation of the component instance being positioned).

By the way, the text mentions an `coordsys-specification` which seems to be some old name referring to a `coordinateSystem`.  Maybe we should also clean this up?

**Comment by HansOlsson** [comment]
Just to be clear. The current text has (after record Transformation):

The origin attribute defines the position of the component in the coordinate system of the enclosing class.
The extent defines the position, size and flipping of the component, relative to the origin attribute.
The extent is defined relative to the origin attribute of the component instance. 
Given an extent {{x1, y1}, {x2, y2}}, x2 < x1 defines horizontal flipping and y2 < y1 defines vertical flipping around
the center of the object.
The rotation attribute specifies rotation of the extent around the point defined by the origin attribute.
The graphical operations are applied in the order: scaling, flipping and rotation.

The intent of proposals 1 and 2 was to replace all of this (possibly after further clarifying the notation). For proposal 3 I'm not fully sure what to keep. (Note that rotation being counter-clockwise was recently added at the other place rotations are mentioned.)

**Comment by HansOlsson** [comment]
The formula must be clear which extent and origin is referred to.
Should check what the tools do; so we see if there is close to consensus in tools.

**Comment by henrikt-ma** [comment]
System Modeler:
![FlipDefinition1-SystemModeler](https://user-images.githubusercontent.com/25294143/203357882-279f3fa0-159a-43e7-93de-6aa56426c3b3.png)

**Comment by DagBruck** [comment]
Dymola 2023x:
![image](https://user-images.githubusercontent.com/24527575/203359455-6e2579ba-1ee2-4041-adb9-c517abb39eec.png)

**Comment by HansOlsson** [comment]
It seems we a clear majority for the one interpretation.

**Comment by HansOlsson** [comment]
> Proposal 3 (same non-normative as above):
> 
> > The `extent` defines an affine transformation of the coordinate system, acting independently on the _x_ and _y_ coordinates, and such that `coordinateSystem.extent[1]` is mapped to `extent[1]` and `coordinateSystem.extent[2]` is mapped to `extent[2]` (where `coordinateSystem.extent` refers to the `Icon`-annotation of the component instance being positioned).

Yes, but we then need to define that this is followed by a counter-clock-wise rotation by the rotation angle and then translated by origin. That's why a formula might be more concise.

Alternatively, if we cannot agree we could just modify the current text:

The origin attribute defines the position of the component in the coordinate system of the enclosing class.
The extent defines the position, size and flipping of the component, relative to the origin attribute.
The extent is defined relative to the origin attribute of the component instance.
Given an extent {{x1, y1}, {x2, y2}}, x2 < x1 defines horizontal flipping and y2 < y1 defines vertical flipping around
the center of the object.
The rotation attribute specifies rotation of the extent around the point defined by the origin attribute.
The graphical operations are applied in the order: scaling, flipping and rotation.

->
The origin attribute defines the position of the component in the coordinate system of the enclosing class.
The extent defines the position, size _(and flipping)_ of the component, relative to the origin attribute.
The extent is defined relative to the origin attribute of the component instance.
_Non-normatively_: Given an extent {{x1, y1}, {x2, y2}}, x2 < x1 defines horizontal flipping and y2 < y1 defines vertical flipping around the center of the object.
The rotation attribute specifies rotation of the extent around the point defined by the origin attribute.
The graphical operations are applied in the order: scaling, rotation, and _positioning_.

As seen the main point is that "flipping" is a _consequence_, not a separate operation (note that this was different in Modelica 2 graphics).

**Comment by henrikt-ma** [comment]
I find it problematic to suggest that flipping is less important to state by putting it inside parentheses.  To me, it is the fully normative combination _size and flipping_ that works as the natural language replacement for something more mathematical.

For a more readable presentation, we could avoid breaking up the paragraph with a non-normative paragraph like so:
> (That is, given an extent {{x1, y1}, {x2, y2}}, x2 < x1 defines horizontal flipping and y2 < y1 defines vertical flipping around the center of the object.)

> The graphical operations are applied in the order: scaling, rotation, and positioning.

I think I see what you mean, and I like this way of breaking it down to application of the three attributes `extent`, `rotation`, and `origin` (in that order).  The problem is that this currently doesn't correspond to how the text is written.  It could be done like this:
> The attributes are applied in the order `extent`, `rotation`, `origin`, as follows:
> 1. The `extent` of the component icon is mapped to the `extent` rectangle (possibly shifting, scaling, and flipping contents).
> 2. The `rotation` specifies counter-clockwise rotation around the origin (that is `{0, 0}`, not the `origin` attribute).
> 3. The `origin` specifies a shift (moving `{0, 0}` to `origin`).

> As seen the main point is that "flipping" is a consequence, not a separate operation (note that this was different in Modelica 2 graphics).

Right, but I find this clear in all the alternatives we have discussed.

**Comment by eshmoylova** [comment]
I have been trying to figure out how the current formulation can be interpreted that the result would end up like in the top pictures in [the second comment](https://github.com/modelica/ModelicaSpecification/issues/3275#issuecomment-1305575297). I cannot. Anybody? As reported in other comments, other tools are consistent among themselves and with the user expectation. Would it be possible to get comments from the tool developers responsible for the unexpected images on what logic led to those images? Then we would have a better idea of what needs to be fixed.

**Comment by HansOlsson** [comment]
> I think I see what you mean, and I like this way of breaking it down to application of the three attributes `extent`, `rotation`, and `origin` (in that order). The problem is that this currently doesn't correspond to how the text is written. It could be done like this:
> 
> > The attributes are applied in the order `extent`, `rotation`, `origin`, as follows:
> > 
> > 1. The `extent` of the component icon is mapped to the `extent` rectangle (possibly shifting, scaling, and flipping contents).
> > 2. The `rotation` specifies counter-clockwise rotation around the origin (that is `{0, 0}`, not the `origin` attribute).
> > 3. The `origin` specifies a shift (moving `{0, 0}` to `origin`).

Ok, if we don't want a formula that seems the cleanest.
And could add the previous non-normative part about flipping at end of 1.

**Comment by HansOlsson** [comment]
> I have been trying to figure out how the current formulation can be interpreted that the result would end up like in the top pictures in [the second comment](https://github.com/modelica/ModelicaSpecification/issues/3275#issuecomment-1305575297). I cannot. Anybody? 

I don't know either. However, I do know that it can be somewhat tricky to get things to work correctly in some drawing environments (especially for images), but that would indicate a bug not a misunderstanding.

**Comment by HansOlsson** [comment]
Phone meeting: Agree on "The attributes are applied in the order extent, rotation, origin, as follows:..."
