### ISSUE TITLE
Annotations in redeclare

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3311]
The syntax allows to specify annotations as part of the redeclarations. How those annotations should be combined with the annotations on the element?

Here is a simple case where you want the annotations to be replaced by the redeclaration:
```
package RedeclAnnot
    record M1
      replaceable parameter Integer X(min=-1,max=-1) = -1
          annotation( choices(choice=-1 "-1", choice=1 "1"));
    end Modes;

    record M2
      extends M1(redeclare parameter Integer X(min=0,max=2) = 1 "Mode 2 for X"
	annotation( choices( choice=1 "1", choice=2 "2") ));
    end GlobalModes;
end RedeclAnnot;
```
But what about any graphical annotations? Are they even allowed in redeclarations? Are there any cases where the annotations should be merged?

**Comment by HansOlsson** [comment]
To me that seems like a fairly major issue to resolve due to:

- Merging seems needed in some cases. As I recall we tried to support some modified annotations in Dymola in some project and the merging was one of the pain-points.
- If we allow it for graphical annotations the obvious question is why does have to be a `redeclare` repeating the declaration just to add/modify the annotation (well, currently that is how the specification works - but from a design perspective it is weird).
- On the other hand, if we generalize to all modifiers we can suddenly have annotations on attributes, which is a bit weird
- There's also the interaction with selective model extension that allows you to deselect and add the component with appropriate annotations (but only at the top, not nested). If the cases are sufficiently few that might be good enough.

So, I would say that either we should remove it completely or go all in; but I believe we need more information to take that decision.

As for the example I find it a bit odd that it shifts the range (i.e., min and max), and in some sense it should be an enumeration but the sub-typing doesn't allow that.
I can understand decreasing the range, if some value in the base-class shouldn't be used, and increasing the range (if out of bounds values didn't generate equations and we add equations for that case).

As a separate note if we just had: 
```
package RedeclAnnot
    record M1
      parameter Integer X(min=-1,max=-1) = -1
          annotation( choices(choice=-1 "Reverse", choice=0 "Parking", choice=1 "First gear"));
    end Modes;

    record M2
      extends M1(X(min=0));
    end M2;
end RedeclAnnot;
```
Then M2.X might remove the choice that is out of bounds.

**Comment by HansOlsson** [comment]
Design meeting:

Alternative using different classes ( https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#annotation-choices-for-suggested-redeclarations-and-modifications )
```
package RedeclAnnot
   type X1=Integer annotation( choices(choice=-1 "-1", choice=1 "1");
    record M1
      replaceable parameter X1 X(min=-1,max=-1) = -1;
    end Modes;

    record M2
     type X2=Integer annotation( choices( choice=1 "1", choice=2 "2");
      extends M1(redeclare parameter X2 X(min=0,max=2) = 1 "Mode 2 for X");
    end GlobalModes;
end RedeclAnnot;
```
Question: Should we deprecate/remove annotations for redeclare?

**Comment by HansOlsson** [comment]
Action: Check whether it is used, and if not deprecate/remove it.

**Comment by HansOlsson** [comment]
I checked MSL and example models in each of the libraries I have installed and none triggered this.
I understand that redeclare annotations might be some used somewhere, but I believe we can deprecate it.

**Comment by HansOlsson** [comment]
Phone meeting:
Mention that choices should be consistent with min/max in spec.
Deprecating shouldn't be impactful, since not used in most libraries and mostly not supported in tools.
