### ISSUE TITLE
Event-generation in while-loop condition

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3321]
The specification sometimes mentions implicit treatment of an expression as being wrapped in `noEvent` (for example, see https://specification.modelica.org/master/equations.html#assert), but there is no such statement regarding the condition of a `while`-loop.  Perhaps we should add such a statement, and I can't see that it would hurt to do so normatively?

This model illustrates the need:
```
model WhileLoopRelation
  Real x;
algorithm
  x := exp(-0.2 * time);
  while x >= 0.1 loop
    x := 0.5 * x;
  end while;
  annotation(experiment(StopTime = 5.0));
end WhileLoopRelation;
```

**Comment by HansOlsson** [comment]
I agree that it makes sense.

However, the same applies to most thing inside the while-loop as well, so I would say that the entire while-loop should be wrapped in noEvent.

Example of other issue:
```
model WhileLoopRelation
  Real x;
algorithm 
  x := time;
  while x >= 0.1 loop
    if x >= 0.2 then
      x := 0.1*x;
    else
      x := 0.5*x;
    end if;
  end while;
  annotation (experiment(StopTime=5.0));
end WhileLoopRelation;
```

**Comment by henrikt-ma** [comment]
A better alternative to just hiding problems by saying there's an implicit `noEvent` could be to make event-generating expressions illegal.  This would make the algorithm semantics much more clear to a reader.

By the way, as long as we consider an implicit `noEvent` as one of the options, I think that making illegal without prior deprecation should also be on the table.  (To require deprecation would only make sense if the implicit `noEvent` would be ruled out because of the way it would change semantics of currently valid models.)

Something that tools might actually be able to do right with somewhat limited effort could be event-generating expressions which can be handled with time events.  That is, both saying that there is an implicit `noEvent` or making event-generating expressions illegal, could have non-backwards compatible impact on currently valid models with support in existing tools.

To see how to proceed, we would need to know to which degree there is tool support today for event-generating expressions in the `while`-loop condition or inside the loop body.

**Comment by HansOlsson** [comment]
The suggestion above to turn off event-generation completely in while-loops was based on how it is implemented in Dymola.
To me the good solutions are:

- Implicitly turn off event-generation in while-loops.
- Deprecate event-generating expressions in while-loops (I don't think we can just forbid it).

Note that in theory there are some other cases that can be handled e.g.:
```
model WhileLoopRelation
  Real x;
algorithm 
  x := time;
  while x >= 0.1 loop
    if sin(time) > 0.2 then
      x := 0.1*x;
    else
      x := 0.5*x;
    end if;
  end while;
  annotation (experiment(StopTime=5.0));
end WhileLoopRelation;
```
Here `sin(time) > 0.2` could be hoisted out of while-loop (note: it is not a time-event). However, since you can hoist that manually as well _and I haven't seen good uses of this_, I don't believe we should add special cases for this.

Additionally, time-events shouldn't be an exception (the example below doesn't make sense - please don't write code like this).
Consider:
```
  Integer i,j;
  Boolean b;
equation 
  j= integer(10*time);
  b=time<0.2*(j+2);
algorithm 
  i:=integer(10*time);
  while time<0.2*(i+2) loop
      i:=i-2;
  end while;
```
Here `b` can be given by a time-event (since the rhs is discrete-time expression), but the corresponding expression in the while-loop cannot be seen as a time-event (since there can be multiple values for the rhs since `i` is assigned to).

**Comment by eshmoylova** [comment]
Agreed that while-loops should not raise events. Should there be a similar restriction for for-loops? Consider:
```
model ForLoopRelation
  Integer x;
  parameter Integer n = 3;
  parameter Integer t[n] = {1,2,3};
algorithm 
  x := integer(10*time);
  for i in 1:n loop
    if x >= t[i] then
       x := x+1;
    else
       x := x+5;
    end if;
  end for;
end ForLoopRelation;
```
vs. [Modelica.Electrical.Digital.Sources.Table](https://github.com/modelica/ModelicaStandardLibrary/blob/89d5175dea8b668624c90dbd019cca4bd3f1f5bb/Modelica/Electrical/Digital.mo#L3719-L3723). Should they be treated the same?

**Comment by HansOlsson** [comment]
> Agreed that while-loops should not raise events. Should there be a similar restriction for for-loops? 

I wouldn't say so, as the number iterations are bounded and you can in the example below  generate n crossing functions (well if x were an integer - otherwise there is no need for any crossing functions), whereas there's no known upper limit for a while-loop.

**Comment by eshmoylova** [comment]
What if the expression in the for-loop is not a parameter expression? It is not restricted to parameter-expressions in algorithms, but I can't come up with an example.

**Comment by henrikt-ma** [comment]
At least it's not obvious to me that it is a problem as long as the range expression is discrete-time, so that the number of active zero crossings can be determined at the beginning of continuous-time integration after an event.  Whether it motivates this being a quality-of-implementation thing, or if we want to lock down the language further to facilitate tool implementation (for higher degree of actual portability of models between tools) is a different question.

**Comment by henrikt-ma** [comment]
> Here `b` can be given by a time-event (since the rhs is discrete-time expression), but the corresponding expression in the while-loop cannot be seen as a time-event (since there can be multiple values for the rhs since `i` is assigned to).

Just noting that as this explains why the event in the `while`-loop condition isn't a time event, this example is not related to the question whether to allow exceptions for time-event generating expressions.

**Comment by HansOlsson** [comment]
Added after finding the right spot in the spec while writing a reply:

It seems we were close to thinking about in the specification and added:
https://specification.modelica.org/master/operators-and-expressions.html#discrete-time-expressions

> Inside an if-expression, if-clause, while-statement or for-clause, that is controlled by a non-discrete-time (that is continuous-time, but not discrete-time) switching expression and not in the body of a when-clause, it is not legal to have assignments to discrete-time variables, equations between discrete-time expressions, or real elementary relations/functions that should generate events.

But the paragraph looks weird (calling the loop-expression a "switching expression" isn't clear), and even if it works for if-clauses it doesn't cover all cases for for-clauses (or while-loops) because even a discrete-time "switching expression" would be complicated to implement.

Back to my planned reply:

> What if the expression in the for-loop is not a parameter expression? It is not restricted to parameter-expressions in algorithms, but I can't come up with an example.

I could come up with examples, and think it is important to separate it into two cases:
* Non-parameter array, with parametric size
* Even the size isn't parametric

To me the second case is as problematic as while-loops, and should be forbidden.

The first is mostly a convenience issue. 

Consider:
```
  Real x[:]={cos(time),sin(time*3),sin(time*5)};
  Boolean b;
algorithm 
  b:=true;
  for i in 1:size(x,1) loop
    b:=b and x[i]>0;
  end for;
```
One could rewrite the for-loop as:
```
  for y in x loop
    b:=b and y>0;
  end for;
```
And then the expression wouldn't be a parameter-expression, but an expression whose size is a parameter (or literal in this case). If we look in MSL we see that the former is the usual style. I just view that as a convenience issue and not of high priority (but similar constructs in other languages (Python, C++11) may increase its priority).

However, even the for-array could vary, consider the following generalization:
```
  for y in sin(time*(1:2:integer(time))) loop
    b:=b and y>0;
  end for;
```
Or some other formula that makes more sense.

And final remark:
The examples above seem to be forbidden by the quoted paragraph, but we can rewrite the last one to:
```
  Boolean b;
algorithm 
  b:=true;
  for i in 1:2:integer(time) loop
    b:=b and sin(time*i)>0;
  end for;
```
Here `i` is given by a discrete-time array with discrete-time size so it should be legal, but we would need to generate an unbounded number of crossing functions which is practically impossible.

So, it seems we should restrict it further to parameter-variability for for-loops.

**Comment by henrikt-ma** [comment]
> Here `i` is given by a discrete-time array with discrete-time size so it should be legal, but we would need to generate an unbounded number of crossing functions which is practically impossible.

While this is something System Modeler couldn't handle today, I wouldn't call it practically impossible.  As with many other changes that are backward incompatible if seen strictly from the perspective of the specification, we should inform ourselves about the degree to which tools have been able to implement the challenging cases allowed by the specification.  If there are tools that support a fully dynamic (discrete-time) number of zero crossings, we'd need to proceed with deprecation before disallowing it completely.  If no such tool exists, we can just pretend it was just a mistake to allow it in the first place and correct the mistake without prior deprecation.

We should also consider each of the conditional constructs separately, as what we determine to be "practically feasible" will probably differ from one construct to another.

For `if`-expressions and `if`-equations, I think that the discrete-time restriction is enough, as the potentially active event-generating expressions can be found by just examining all of the branches.

For a `while`-loop, it almost gets silly to require the loop condition to be a parameter expression, as it doesn't even help as long as the condition doesn't turn out to be `false`.  Further, when the loop condition is `false`, the entire `while`-loop could just be removed, so `while test() loop … (x > 0) … end while;` would just reduce to the requirement that `test()` is a parameter expression and an assertion that the value is `false`.  Conclusion: Completely disallow event-generating expressions inside `while`-loops.

For a `for`-loop, a simple place to start (introducing a backward compatibility that may not matter for practical purposes) could be to require that the size of the loop range is a parameter expression.  (I believe that this formulation would work for explicit as well as implicit iteration ranges.)  Who would argue for anything more challenging than this, keeping in mind that we could always open up for less restricted `for`-loops in the future?

**Comment by HansOlsson** [comment]
Phone meeting: Two options for while-loops: automatic noEvent-wrapping or require users to write it explicitly (deprecate it).

**Comment by henrikt-ma** [comment]
> Phone meeting: Two options for while-loops: automatic noEvent-wrapping or require users to write it explicitly (deprecate it).

The two options shouldn't only apply to while-loops: they should apply to all of the conditional and looping constructs where the controlling expression does not fulfill the requirements for allowing event-generating expressions inside.

**Comment by gkurzbach** [comment]
In SimulationX, there is currently an implicit noEvent around while and for loops in algorithms. Therefore dynamic changing the number of zero crossings is no supported,

**Comment by HansOlsson** [comment]
Design meeting:

We agree that:
* While-loop should be noEvent (not clear if explicit or not).
* If the for-loop contains event-generating things the for-loop-range should be evaluable - (no special case when the for-loop size of range can be evaluated without evaluating the range itself)
* Thus we need explicit noEvent for for-loop, and similarly for array reductions

Discussion:
* While-loop: explicit noEvent or implicit?

Conclusion:
* Deprecate existence of event-generating things in while-loops (thus we require explicit noEvent).

**Comment by henrikt-ma** [comment]
I suggest that we fix this after merging https://github.com/modelica/ModelicaSpecification/pull/2754, so that we can directly take advantage of the new terminology.
