### ISSUE TITLE
Overconstrained connectors are not mentioned in the Modelica Revision history

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3440]
Overconstrained connectors (currently [Section 9.4](https://specification.modelica.org/master/connectors-and-connections.html#equation-operators-for-overconstrained-connection-based-equation-systems1)) were introduced in Modelica 3.0, making it possible to achieve true object-orientation of the Modelica.Mechanics.MultiBody library.

I think this was an important addition that is worth mentioning in the Modelica Revision History.

**Comment by HansOlsson** [comment]
Good point, but due to https://github.com/modelica/ModelicaSpecification/pull/3394 removing revisions I think this will have to be closed without any change.

I guess we _could_ update 3.6 maintenance branch with the change, but since it has been missing for more than a decade I don't think that is needed. (Additionally based on the size of the list for 3.0 I think there is a lot more missing - so we might have to add a lot more.)
