### ISSUE TITLE
Lookup of enumeration values.

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#3463]
In light of:
> If the identifier denotes a class, that class is temporarily flattened (as if instantiating a component
> without modifiers of this class, see section 7.2.2 and using the enclosing classes of the denoted
> class). The rest of the name (e.g., B or B.C) is looked up among the declared named elements of
> the temporary flattened class. The lookup will only find the element (assuming it exists) in the
> following cases:
> – If the class is declared as package or operator (but not operator record or operator
> function) all elements can be found.
> – An element can be found if it is declared as encapsulated.

Is the following allowed:

```
model Test
  type E = enumeration(one, two);
end Test

model Test2
  Test.E e = Test.E.one;
end Test2;
```

In other words, should we add enumeration type definition to the list of exceptions, or consider them encapsulated by default.
Or are we requiring that they are declared with the encapsulated keyword, if they are meant to be used outside the local model?

**Comment by HansOlsson** [comment]
I believe you intended the example to be something like:
```
model Test
  type E = enumeration(one, two);
  parameter E e=E.one;
end Test;

model Test2
  Test.E e = Test.E.one;
end Test2;
```
Since without the extra `e` declaration the model `Test` fulfils the requirements for a package, which is the weirder deprecated case.

> Or are we requiring that they are declared with the encapsulated keyword, if they are meant to be used outside the local model?

Yes, I would say. The fewer special cases the better, and it would be better if we could also get rid off this special exception for encapsulated (but I don't know how). Additionally this can get out of hand - consider `type E2=E;` it's sort of an enumeration - should that also be treated specially?

**Comment by HansOlsson** [comment]
Phone meeting: Ok to require encapsulated.
