### ISSUE TITLE
Unit definitions: FMI Standard Vs Modelica Language

### ISSUE THREAD

**Issue by BasilioPV** [modelica/ModelicaSpecification#3524]
I like the way of define units and displayUnits of FMI Standard:
- unit name
- BaseUnit definition (dimensions of the unit, as example (kg^1 / m^2 / s^-2) and factor & offset)
- displayUnit definition (name, factor & offset)

It is noted that on FMI standard quantity is defined into each variable.

On Modelica Language, there is no definition of BaseUnit, only the name and displayunit as strings.
I observe that is not possible export a Modelica model into FMU using the definitions provided by the Modelica Language Specification only, since it requires additional data that is not defined. (I suppose that each vendor tool "translates" the MSL definitions into FMU definitions by adding these missing attributes).

It is possible to add attributes similar to FMI standard into Modelica Language Specification that enables (in the future) more control on units, such as:
- Correctly export to FMU without custom tool vendor aid
- Perform unit check when connect two ports
- Unit check of variables that have not units declared

Thanks in advance.

**Comment by HansOlsson** [comment]
> I like the way of define units and displayUnits of FMI Standard:
> 
> * unit name
> * BaseUnit definition (dimensions of the unit, as example (kg^1 / m^2 / s^-2) and factor & offset)
> * displayUnit definition (name, factor & offset)
> 
> It is noted that on FMI standard quantity is defined into each variable.
> 
> On Modelica Language, there is no definition of BaseUnit, only the name and displayunit as strings. I observe that is not possible export a Modelica model into FMU using the definitions provided by the Modelica Language Specification only, since it requires additional data that is not defined. 

The Modelica Language Specification references the BIPM definition of units, where derived units, e.g., "W" for "Watt" are defined (in terms of other units, 1 W=1 J/s, 1 J= 1 N.m).
- Forcing users to write "W" as kg^1 m^2 s^-3 does not seem helpful.
- Duplicating all of the definition of derived units etc from BIPM into the specification would be problematic for several reasons. Just updating the new prefixes and constant definitions in MSL takes time.

> It is possible to add attributes similar to FMI standard into Modelica Language Specification that enables (in the future) more control on units, such as:
> 
> * Correctly export to FMU without custom tool vendor aid

That should already be possible. If a tool cannot do that it is a tool issue.

> * Perform unit check when connect two ports

That should sort of already be possible, but it needs to be further specified (see next item).

Note that for connections the quantity-attributes should be the same (if existing) - that is a stricter check, since it allows checking that different media cannot be connected (and in theory other quantities with matching units - such as Work and Torque; although such a mismatch seems rare).

> * Unit check of variables that have not units declared

Deducing units for variables is being worked on, but it requires more work.

**Comment by HansOlsson** [comment]
Apart from the tool-issues it is already worked on in the MCP.
