### ISSUE TITLE
Status of enumerations described for annotations

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3620]
With #3448 having set out a direction for a more formalized presentation of annotations, I have been asked to seek some additional clarifications about annotation handling in general.  This issue is regarding the status of the enumerations described for annotations.  Example:
```
model SmoothParameter
  parameter Smooth smooth = Smooth.Bezier;
  annotation(Icon(graphics = {Polygon(smooth = smooth, points = {{-50, -16.667}, {0, 33.333}, {50, -16.667}})}));
end SmoothParameter;
```

To my understanding, https://specification.modelica.org/master/class-predefined-types-and-declarations.html#other-predefined-types should be interpreted as `StateSelect` and `AssertionLevel` being the only actual predefined enumeration types, and the enumerations presented for annotations are only possible to reference in more or less specific annotation contexts.  Hence, the `SmoothParameter` has an invalid declaration of the `smooth` parameter, and consequently the icon `Polygon` is also broken.

But what if the user uses a compatible, properly defined, enumeration type?
```
model SmoothParameter2
  type MySmooth = enumeration(None, Bezier);
  parameter MySmooth smooth = MySmooth.Bezier;
  annotation(Icon(graphics = {Polygon(smooth = smooth, points = {{-50, -16.667}, {0, 33.333}, {50, -16.667}})}));
end SmoothParameter2;
```

Or if the user tries to hack the system by defining an enumeration with the same name as in the specification?
```
model SmoothParameter3
  type Smooth = enumeration(Bezier);
  parameter Smooth smooth = Smooth.Bezier;
  annotation(Icon(graphics = {Polygon(smooth = smooth, points = {{-50, -16.667}, {0, 33.333}, {50, -16.667}})}));
end SmoothParameter3;
```

It would be good if https://specification.modelica.org/master/annotations.html#notation-for-annotation-definitions would be followed by a similar small section about general evaluation/lookup rules for annotations.  For initial content, we could describe the status of the enumerations.

Edit: One more example related to lookup:
```
model SmoothParameter4
  type Smooth = enumeration(Linear, Quadratic, Cubic); /* Will this break evaluation of 'smooth' */
  parameter Boolean bezier = true;
  annotation(Icon(graphics = {Polygon(smooth = if bezier then Smooth.Bezier else Smooth.None, points = {{-50, -16.667}, {0, 33.333}, {50, -16.667}})}));
end SmoothParameter4;
```
Would fully qualified references provide a workaround?  (This would imply that tools that generate annotations should always use fully qualified references to the enumerations described for annotations.)
```
  Polygon(smooth = if bezier then .Smooth.Bezier else .Smooth.None, …)
```

**Comment by henrikt-ma** [comment]
In System Modeler, `SmoothParameter` is rejected due to the use of the undefined type `Smooth`, and the other two variants result in an icon where line is drawn as if it had `smooth = None`.  Is it working similarly in other tools?

**Comment by HansOlsson** [comment]
In Dymola (specifically Dymola 2025x) only show smooth line for `SmoothParameter4` (when modifying it to have `bezier = true`, took me some time to find that...).

Requiring fully qualified references would break compatibility, and generally be confusing.

The best solution I can quickly think of is to have all of these types in some internal package, and state that all graphical annotations have an import of that package.

**Comment by perost** [comment]
In OpenModelica we define all of the annotation types in a separate scope which is checked first when looking up names in an annotation. This was done to avoid having userdefined types and annotation types interfer with each other. So the behaviour we get is:
* SmoothParameter: Rejected because `Smooth` isn't defined outside annotations.
* SmoothParameter2: Doesn't work, type is fine but I assume the rendering code specifically checks for `Smooth`.
* SmoothParameter3: Doesn't work due to type mismatch on `smooth = smooth`, but does work if the enumeration is defined same as the builtin `Smooth`.
* SmoothParameter4: Doesn't work, though I'm not sure why. If the if-expression is changed to just `Smooth.Bezier` it works, i.e. the userdefined `Smooth` does not interfer since we find the builtin `Smooth` first.

**Comment by HansOlsson** [comment]
> In OpenModelica we define all of the annotation types in a separate scope which is checked first when looking up names in an annotation. This was done to avoid having userdefined types and annotation types interfer with each other. So the behaviour we get is:
...
> * SmoothParameter4: Doesn't work, though I'm not sure why. If the if-expression is changed to just `Smooth.Bezier` it works, i.e. the userdefined `Smooth` does not interfer since we find the builtin `Smooth` first.

Just to be sure - you changed bezier to true, right?

**Comment by perost** [comment]
> Just to be sure - you changed bezier to true, right?

I did not, so that explains that. Changing it to true makes the lines smooth in OpenModelica.

Btw, the reason for OpenModelica's current behaviour is due to [this issue](https://github.com/OpenModelica/OpenModelica/issues/12077), i.e. we actually encountered a user library that defined its own `Smooth` class that broke the rendering at the time.

**Comment by henrikt-ma** [comment]
> In Dymola (specifically Dymola 2025x) only show smooth line for `SmoothParameter4` (when modifying it to have `bezier = true`, took me some time to find that...).

Sorry.  I'll correct this in the opening comment.
